namespace Nerv.IIP.Iam.Domain;

public sealed record OrganizationFact(string OrganizationId, string Name, string Status);
public sealed record IamEnvironmentFact(string EnvironmentId, string OrganizationId, string Name, string Status);
public sealed record UserFact(
    string UserId,
    string LoginName,
    string Email,
    string PasswordHash,
    bool Enabled,
    string SecurityStamp,
    int PermissionVersion,
    int FailedLoginCount = 0,
    DateTimeOffset? LastFailedLoginAtUtc = null,
    DateTimeOffset? LockoutUntilUtc = null);
public sealed record RoleFact(string RoleId, string RoleName, IReadOnlySet<string> PermissionCodes);
public sealed record MembershipFact(string UserId, string OrganizationId, string EnvironmentId, IReadOnlySet<string> RoleIds);
public sealed record UserSessionFact(
    string SessionId,
    string UserId,
    string RefreshTokenHash,
    DateTimeOffset IssuedAtUtc,
    DateTimeOffset ExpiresAtUtc,
    DateTimeOffset? RevokedAtUtc,
    int PermissionVersion,
    string AuthenticationMethod,
    string? ExternalProvider,
    string? ExternalSubject,
    DateTimeOffset? MfaVerifiedAtUtc);
public sealed record ConnectorHostCredentialFact(string ConnectorHostId, string OrganizationId, string EnvironmentId, IReadOnlySet<string> CapabilityScope, string SecretHash, DateTimeOffset ValidFromUtc, DateTimeOffset? ValidToUtc);

public static class NervIipSeedPermissions
{
    public static readonly string[] All =
    [
        "iam.users.read",
        "iam.users.manage",
        "iam.roles.read",
        "iam.roles.manage",
        "iam.sessions.read",
        "iam.sessions.revoke",
        "iam.security-audit.read",
        "connectors.registrations.write",
        "connectors.heartbeats.write",
        "connectors.state-snapshots.write",
        "apphub.instances.read",
        "files.upload",
        "files.read",
        "files.download-grants.create",
        "files.archive",
        "ops.tasks.create",
        "ops.tasks.read",
        "ops.results.write",
        "ops.audit.read",
        "observability.logs.read",
        "business.masterdata.products.read",
        "business.masterdata.products.manage",
        "business.masterdata.partners.read",
        "business.masterdata.partners.manage",
        "business.masterdata.resources.read",
        "business.masterdata.resources.manage",
        "business.quality.inspection-plans.manage",
        "business.quality.inspection-records.create",
        "business.quality.inspection-records.read",
        "business.quality.ncr.read",
        "business.quality.ncr.manage",
        "business.inventory.locations.manage",
        "business.inventory.movements.create",
        "business.inventory.ledger.read",
        "business.inventory.counts.manage",
        "business.mes.foundation.read",
        "business.mes.overview.read",
        "business.mes.plans.read",
        "business.mes.work-orders.read",
        "business.mes.work-orders.manage",
        "business.mes.materials.read",
        "business.mes.materials.manage",
        "business.mes.dispatch.read",
        "business.mes.dispatch.manage",
        "business.mes.operations.read",
        "business.mes.operations.manage",
        "business.mes.reporting.read",
        "business.mes.reporting.write",
        "business.mes.quality.read",
        "business.mes.quality.write",
        "business.mes.receipts.read",
        "business.mes.receipts.manage",
        "business.mes.downtime.read",
        "business.mes.downtime.manage",
        "business.mes.handovers.read",
        "business.mes.handovers.manage",
        "business.mes.traceability.read",
        "business.mes.schedules.read",
        "business.mes.schedules.manage",
        "business.mes.capacity.read",
        "business.engineering.documents.read",
        "business.engineering.documents.manage",
        "business.engineering.items.read",
        "business.engineering.items.manage",
        "business.engineering.boms.read",
        "business.engineering.boms.manage",
        "business.engineering.routings.read",
        "business.engineering.routings.manage",
        "business.engineering.standard-operations.read",
        "business.engineering.standard-operations.manage",
        "business.engineering.production-versions.read",
        "business.engineering.production-versions.manage",
        "business.engineering.changes.read",
        "business.engineering.changes.manage",
        "business.planning.demands.read",
        "business.planning.demands.manage",
        "business.planning.mps.read",
        "business.planning.mps.manage",
        "business.planning.mps.release",
        "business.planning.mrp.read",
        "business.planning.mrp.run",
        "business.planning.suggestions.manage",
        "business.barcodes.templates.manage",
        "business.barcodes.print",
        "business.barcodes.scans.write",
        "business.approvals.read",
        "business.approvals.manage",
        "business.erp.procurement.read",
        "business.erp.procurement.manage",
        "business.erp.sales.read",
        "business.erp.sales.manage",
        "business.erp.finance.read",
        "business.erp.finance.manage",
        "business.scheduling.plans.read",
        "business.scheduling.plans.manage",
        "business.scheduling.plans.release",
        "business.wms.receipts.read",
        "business.wms.receipts.manage",
        "business.wms.shipments.read",
        "business.wms.shipments.manage",
        "business.wms.automation.manage",
        "business.iiot.tags.manage",
        "business.iiot.alarm-rules.manage",
        "business.iiot.telemetry.read",
        "business.iiot.telemetry.write",
        "business.iiot.alarms.read",
        "business.iiot.alarms.write",
        "business.maintenance.work-orders.read",
        "business.maintenance.work-orders.manage",
        "business.maintenance.plans.read",
        "business.maintenance.plans.manage",
        "notifications.intents.submit",
        "notifications.dlq.read",
        "notifications.dlq.manage",
        "notifications.messages.read",
        "notifications.messages.mark-read",
        "notifications.tasks.read"
    ];
}
