// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nerv.IIP.Business.Inventory.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nerv.IIP.Business.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nerv.IIP.Business.Inventory.Domain.AggregatesModel.StockCountAdjustmentAggregate.StockCountAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Stock count adjustment aggregate id.");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc")
                        .HasComment("UTC time when the count adjustment was confirmed.");

                    b.Property<string>("CountTaskCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("count_task_code")
                        .HasComment("Business count task code that produced the adjustment.");

                    b.Property<decimal>("CountedQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("counted_quantity")
                        .HasComment("Confirmed physical counted quantity.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the count adjustment was confirmed.");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key")
                        .HasComment("Idempotency key supplied when confirming the count variance; expected to be a UUID-like or producer-stable token.");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_code")
                        .HasComment("Inventory stock location code.");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_no")
                        .HasComment("Optional lot or batch number dimension.");

                    b.Property<string>("MovementId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("movement_id")
                        .HasComment("Stock movement id generated for the count variance.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the count adjustment.");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_id")
                        .HasComment("Optional public owner reference id.");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_type")
                        .HasComment("Stock ownership type such as company, customer or supplier.");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quality_status")
                        .HasComment("Quality status carried by adjusted stock.");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_no")
                        .HasComment("Optional serial number dimension.");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_code")
                        .HasComment("MasterData site code.");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code")
                        .HasComment("MasterData SKU code.");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uom_code")
                        .HasComment("MasterData unit of measure code for counted quantity.");

                    b.Property<decimal>("VarianceQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("variance_quantity")
                        .HasComment("Confirmed variance quantity against ledger on-hand.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "CountTaskCode", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "SkuCode", "SiteCode", "LocationCode", "ConfirmedAtUtc");

                    b.ToTable("stock_count_adjustments", "inventory", t =>
                        {
                            t.HasComment("Inventory stock count adjustment facts generated from confirmed count variances.");

                            t.HasCheckConstraint("ck_stock_count_adjustments_location_code_format", "location_code ~ '^[A-Za-z0-9_.:-]+$'");

                            t.HasCheckConstraint("ck_stock_count_adjustments_site_code_format", "site_code ~ '^[A-Za-z0-9_.:-]+$'");

                            t.HasCheckConstraint("ck_stock_count_adjustments_sku_code_format", "sku_code ~ '^[A-Za-z0-9_.:-]+$'");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Inventory.Domain.AggregatesModel.StockCountTaskAggregate.StockCountTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Stock count task aggregate id.");

                    b.Property<string>("CountTaskCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("count_task_code")
                        .HasComment("Business count task code.");

                    b.Property<decimal?>("CountedQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("counted_quantity")
                        .HasComment("Confirmed physical counted quantity.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the count task was created.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the count task was created.");

                    b.Property<long>("ExpectedLedgerVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_ledger_version")
                        .HasComment("Ledger version captured when the count task was created.");

                    b.Property<string>("LedgerEnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ledger_environment_id")
                        .HasComment("Environment id of the ledger snapshot.");

                    b.Property<string>("LedgerOrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ledger_organization_id")
                        .HasComment("Organization id of the ledger snapshot.");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_code")
                        .HasComment("Inventory stock location code.");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_no")
                        .HasComment("Optional lot or batch number dimension.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the count task.");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_id")
                        .HasComment("Optional public owner reference id.");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_type")
                        .HasComment("Stock ownership type such as company, customer or supplier.");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quality_status")
                        .HasComment("Quality status carried by counted stock.");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_no")
                        .HasComment("Optional serial number dimension.");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_code")
                        .HasComment("MasterData site code.");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code")
                        .HasComment("MasterData SKU code.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Stock count task lifecycle status.");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uom_code")
                        .HasComment("MasterData unit of measure code for counted quantity.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the count task was last changed.");

                    b.Property<decimal?>("VarianceQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("variance_quantity")
                        .HasComment("Confirmed variance quantity against ledger on-hand.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "CountTaskCode")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "Status", "SiteCode", "LocationCode");

                    b.ToTable("stock_count_tasks", "inventory", t =>
                        {
                            t.HasComment("Inventory stock count tasks, expected ledger version snapshots and confirmed variances.");

                            t.HasCheckConstraint("ck_stock_count_tasks_location_code_format", "location_code ~ '^[A-Za-z0-9_.:-]+$'");

                            t.HasCheckConstraint("ck_stock_count_tasks_site_code_format", "site_code ~ '^[A-Za-z0-9_.:-]+$'");

                            t.HasCheckConstraint("ck_stock_count_tasks_sku_code_format", "sku_code ~ '^[A-Za-z0-9_.:-]+$'");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Inventory.Domain.AggregatesModel.StockLedgerAggregate.StockLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Stock ledger aggregate id.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the balance is valid.");

                    b.Property<long>("LedgerVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("ledger_version")
                        .HasComment("Monotonic ledger version incremented when movements are applied.");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_code")
                        .HasComment("Inventory stock location code.");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_no")
                        .HasComment("Optional lot or batch number dimension.");

                    b.Property<decimal>("OnHandQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("on_hand_quantity")
                        .HasComment("Current on-hand stock quantity.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the ledger balance.");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_id")
                        .HasComment("Optional public owner reference id.");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_type")
                        .HasComment("Stock ownership type such as company, customer or supplier.");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quality_status")
                        .HasComment("Quality status carried by stock facts.");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("reserved_quantity")
                        .HasComment("Current reserved quantity; always zero in Inventory MVP.");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version")
                        .HasComment("Optimistic row version for concurrent stock balance updates.");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_no")
                        .HasComment("Optional serial number dimension.");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_code")
                        .HasComment("MasterData site code.");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code")
                        .HasComment("MasterData SKU code.");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uom_code")
                        .HasComment("MasterData unit of measure code for the quantity.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the ledger was last changed.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "SkuCode", "UomCode", "SiteCode", "LocationCode", "LotNo", "SerialNo", "QualityStatus", "OwnerType", "OwnerId")
                        .IsUnique();

                    b.ToTable("stock_ledgers", "inventory", t =>
                        {
                            t.HasComment("Inventory current stock ledger balances by SKU, UOM, site, location, lot, serial, quality and owner dimensions.");

                            t.HasCheckConstraint("ck_stock_ledgers_location_code_format", "location_code ~ '^[A-Za-z0-9_.:-]+$'");

                            t.HasCheckConstraint("ck_stock_ledgers_site_code_format", "site_code ~ '^[A-Za-z0-9_.:-]+$'");

                            t.HasCheckConstraint("ck_stock_ledgers_sku_code_format", "sku_code ~ '^[A-Za-z0-9_.:-]+$'");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Inventory.Domain.AggregatesModel.StockLocationAggregate.StockLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Stock location aggregate id.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the location was created.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the location is valid.");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_code")
                        .HasComment("Business stock location code.");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location_type")
                        .HasComment("Location type such as warehouse, zone, bin or logical.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the location.");

                    b.Property<string>("ParentLocationCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_location_code")
                        .HasComment("Optional parent stock location code.");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_code")
                        .HasComment("MasterData site code associated with this location.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Location lifecycle status.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the location was last changed.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "LocationCode")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "SiteCode", "Status");

                    b.ToTable("stock_locations", "inventory", t =>
                        {
                            t.HasComment("Inventory stock locations such as warehouse, zone, bin or logical stock area.");

                            t.HasCheckConstraint("ck_stock_locations_location_code_format", "location_code ~ '^[A-Za-z0-9_.:-]+$'");

                            t.HasCheckConstraint("ck_stock_locations_site_code_format", "site_code ~ '^[A-Za-z0-9_.:-]+$'");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Inventory.Domain.AggregatesModel.StockMovementAggregate.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Stock movement aggregate id.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the movement was posted.");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key")
                        .HasComment("Idempotency key unique within organization, environment, source service and source document; expected to be a UUID-like or producer-stable token.");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_code")
                        .HasComment("Inventory stock location code.");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_no")
                        .HasComment("Optional lot or batch number dimension.");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_type")
                        .HasComment("Movement type: inbound, outbound, transfer, adjustment or count-adjustment.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the movement.");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_id")
                        .HasComment("Optional public owner reference id.");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_type")
                        .HasComment("Stock ownership type such as company, customer or supplier.");

                    b.Property<DateTime>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc")
                        .HasComment("UTC time when the movement was posted.");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quality_status")
                        .HasComment("Quality status carried by stock facts.");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity")
                        .HasComment("Signed movement quantity.");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_no")
                        .HasComment("Optional serial number dimension.");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_code")
                        .HasComment("MasterData site code.");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code")
                        .HasComment("MasterData SKU code.");

                    b.Property<string>("SourceDocumentId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("source_document_id")
                        .HasComment("Source document id supplied by the producer.");

                    b.Property<string>("SourceDocumentLineId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("source_document_line_id")
                        .HasComment("Optional source document line id supplied by the producer.");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_service")
                        .HasComment("Source service that requested the movement.");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uom_code")
                        .HasComment("MasterData unit of measure code for the quantity.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "SourceService", "SourceDocumentId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "SkuCode", "SiteCode", "LocationCode", "PostedAtUtc");

                    b.ToTable("stock_movements", "inventory", t =>
                        {
                            t.HasComment("Append-only Inventory stock movement facts with source document and idempotency key.");

                            t.HasCheckConstraint("ck_stock_movements_location_code_format", "location_code ~ '^[A-Za-z0-9_.:-]+$'");

                            t.HasCheckConstraint("ck_stock_movements_site_code_format", "site_code ~ '^[A-Za-z0-9_.:-]+$'");

                            t.HasCheckConstraint("ck_stock_movements_sku_code_format", "sku_code ~ '^[A-Za-z0-9_.:-]+$'");
                        });
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.CapLock", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Instance")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastLockTime")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Key");

                    b.ToTable("cap_locks", "inventory");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.PublishedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName");

                    b.ToTable("cap_published_messages", "inventory");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.ReceivedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Group")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_ExpiresAt_StatusName1");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_Version_ExpiresAt_StatusName1");

                    b.ToTable("cap_received_messages", "inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
