// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nerv.IIP.Business.Scheduling.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nerv.IIP.Business.Scheduling.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722154723_HardenOrderUrgencyArchiveLifecycle")]
    partial class HardenOrderUrgencyArchiveLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.OrderUrgencyAggregate.OrderUrgencyBusinessPriority", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Business-priority row id.");

                    b.Property<string>("BusinessReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("business_reference")
                        .HasComment("Stable upstream business reference used across ERP, planning, MES, and scheduling.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc")
                        .HasComment("Optional UTC expiry for the manual priority.");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level")
                        .HasComment("Current P0-P3 business priority.");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("order_id")
                        .HasComment("Scheduling order/work-order id.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason")
                        .HasComment("Human-readable reason for the priority.");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasComment("Monotonic audit revision and optimistic concurrency token.");

                    b.Property<DateTimeOffset>("SetAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_at_utc")
                        .HasComment("UTC timestamp when the priority was set.");

                    b.Property<string>("SetBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("set_by")
                        .HasComment("Authenticated actor reference that set the priority.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "BusinessReference");

                    b.HasIndex("OrganizationId", "EnvironmentId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_order_urgency_business_priorities_organization_id_environm~1");

                    b.ToTable("order_urgency_business_priorities", "scheduling", t =>
                        {
                            t.HasComment("Current audited business-priority input for the unified order urgency model.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.OrderUrgencyAggregate.OrderUrgencyBusinessPriorityChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Priority-change row id.");

                    b.Property<string>("BusinessReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("business_reference")
                        .HasComment("Stable upstream business reference used across ERP, planning, MES, and scheduling.");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc")
                        .HasComment("UTC change timestamp.");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("changed_by")
                        .HasComment("Authenticated actor reference.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc")
                        .HasComment("Optional UTC expiry for the new priority.");

                    b.Property<string>("NewLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("new_level")
                        .HasComment("Priority after the change.");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("order_id")
                        .HasComment("Scheduling order/work-order id.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<string>("PreviousLevel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("previous_level")
                        .HasComment("Priority before the change; null for the initial setting.");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason")
                        .HasComment("Human-readable change reason.");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasComment("Monotonic priority revision.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "OrderId", "Revision")
                        .IsUnique();

                    b.ToTable("order_urgency_business_priority_changes", "scheduling", t =>
                        {
                            t.HasComment("Append-only business-priority audit history for the unified order urgency model.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.OrderUrgencyAggregate.OrderUrgencySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Urgency snapshot row id.");

                    b.Property<long>("BusinessPriorityRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("business_priority_revision")
                        .HasComment("Priority revision used by this calculation.");

                    b.Property<string>("BusinessReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("business_reference")
                        .HasComment("Stable upstream business reference used across ERP, planning, MES, and scheduling.");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at_utc")
                        .HasComment("UTC model calculation timestamp.");

                    b.Property<DateTimeOffset>("CalculationBucketUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculation_bucket_utc")
                        .HasComment("Deterministic UTC time bucket used for idempotent recalculation.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_fingerprint")
                        .HasComment("Fingerprint of authoritative source facts.");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("level")
                        .HasComment("Unified urgency level.");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_version")
                        .HasComment("Versioned deterministic calculation model.");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("order_id")
                        .HasComment("Scheduling order/work-order id.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json")
                        .HasComment("Explainable contributions, reason codes, and source timestamps.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "CalculatedAtUtc")
                        .HasDatabaseName("ix_order_urgency_snapshot_retention_scan");

                    b.HasIndex("OrganizationId", "EnvironmentId", "BusinessReference", "CalculatedAtUtc");

                    b.HasIndex("OrganizationId", "EnvironmentId", "OrderId", "CalculatedAtUtc");

                    b.HasIndex("OrganizationId", "EnvironmentId", "OrderId", "ModelVersion", "InputFingerprint", "BusinessPriorityRevision", "CalculationBucketUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_order_urgency_snapshots_organization_id_environment_id_ord~1");

                    b.ToTable("order_urgency_snapshots", "scheduling", t =>
                        {
                            t.HasComment("Immutable explainable urgency calculation snapshots and input audit evidence.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.ScheduleOperationOverrideAggregate.ScheduleOperationOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Override row id.");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor")
                        .HasComment("Actor that created the current fact.");

                    b.Property<DateTimeOffset?>("ClearedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at_utc")
                        .HasComment("Optional MES timestamp at which the manual dispatch was cleared.");

                    b.Property<string>("ClearedReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cleared_reason_code")
                        .HasComment("Optional MES reason code that made this projection an inactive tombstone.");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_utc")
                        .HasComment("Fixed end timestamp in UTC.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active")
                        .HasComment("Whether this override currently contributes an active scheduling lock.");

                    b.Property<string>("LockReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lock_reason_code")
                        .HasComment("Explainable lock reason code.");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation_id")
                        .HasComment("Real operation public id.");

                    b.Property<int>("OperationSequence")
                        .HasColumnType("integer")
                        .HasColumnName("operation_sequence")
                        .HasComment("Operation sequence within the work order.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("resource_id")
                        .HasComment("Fixed executable resource id.");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_event_id")
                        .HasComment("Optional source integration event id.");

                    b.Property<DateTimeOffset>("SourceOccurredAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_occurred_at_utc")
                        .HasComment("Source ordering timestamp and optimistic concurrency token used to reject stale updates.");

                    b.Property<long?>("SourceRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision")
                        .HasComment("Optional positive MES manual-dispatch lifecycle revision and optimistic concurrency token used as the ordering watermark.");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type")
                        .HasComment("Scheduling API or MES dispatch source type.");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc")
                        .HasComment("Fixed start timestamp in UTC.");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("Last persistence update timestamp in UTC.");

                    b.Property<string>("WorkCenterId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("work_center_id")
                        .HasComment("Work center owning the fixed resource.");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("work_order_id")
                        .HasComment("Real work-order public id.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "OperationId")
                        .IsUnique();

                    b.ToTable("schedule_operation_overrides", "scheduling", t =>
                        {
                            t.HasComment("Operation override projections, including active locks and inactive MES revocation tombstones.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Schedule plan aggregate row id.");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("algorithm_version")
                        .HasComment("APS lite algorithm version used to generate the plan.");

                    b.Property<int>("AssignedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_minutes")
                        .HasComment("Total resource occupied minutes, including operation processing plus setup/changeover time.");

                    b.Property<decimal>("AverageResourceUtilization")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("average_resource_utilization")
                        .HasComment("Total assigned minutes divided by total available minutes across resource load windows.");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer")
                        .HasColumnName("contract_version")
                        .HasComment("Schedule plan contract version.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc")
                        .HasComment("UTC timestamp when the plan was generated.");

                    b.Property<int>("LateOperationCount")
                        .HasColumnType("integer")
                        .HasColumnName("late_operation_count")
                        .HasComment("Number of non-locked assigned operations finishing after their due dates.");

                    b.Property<int>("LockedOperationCount")
                        .HasColumnType("integer")
                        .HasColumnName("locked_operation_count")
                        .HasComment("Number of fixed locked operations retained by this plan.");

                    b.Property<int>("MakespanMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("makespan_minutes")
                        .HasComment("Minutes between the earliest resource occupancy start and latest assignment end.");

                    b.Property<decimal>("OnTimeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("on_time_rate")
                        .HasComment("Non-locked operations completed on or before due date divided by non-locked assigned operations.");

                    b.Property<int>("OptimizableOperationCount")
                        .HasColumnType("integer")
                        .HasColumnName("optimizable_operation_count")
                        .HasComment("Number of non-locked scheduled operations included in optimization KPIs.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("plan_id")
                        .HasComment("Public schedule plan id.");

                    b.Property<string>("ProblemFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("problem_fingerprint")
                        .HasComment("Deterministic fingerprint of the scheduling problem input.");

                    b.Property<string>("ProblemId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("problem_id")
                        .HasComment("Public scheduling problem id used to generate this plan.");

                    b.Property<long?>("ReleaseRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("release_revision")
                        .HasComment("Monotonic release revision within the organization and environment scope.");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc")
                        .HasComment("UTC timestamp when the plan was released.");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revocation_reason")
                        .HasComment("Released plan withdrawal reason: Superseded or Explicit.");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc")
                        .HasComment("UTC timestamp when the released plan was superseded or explicitly revoked.");

                    b.Property<int>("ScheduledOperationCount")
                        .HasColumnType("integer")
                        .HasColumnName("scheduled_operation_count")
                        .HasComment("Number of operations assigned by this plan.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status")
                        .HasComment("Persisted plan lifecycle status.");

                    b.Property<string>("SupersededByPlanId")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("superseded_by_plan_id")
                        .HasComment("Successor schedule plan id for automatic supersession; null for explicit revoke.");

                    b.Property<int>("TotalTardinessMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_tardiness_minutes")
                        .HasComment("Total minutes by which non-locked assigned operations finish after their due dates.");

                    b.Property<int>("UnscheduledOperationCount")
                        .HasColumnType("integer")
                        .HasColumnName("unscheduled_operation_count")
                        .HasComment("Number of operations left unscheduled by this plan.");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_schedule_plans_scope_active_release")
                        .HasFilter("status = 'Released'");

                    b.HasIndex("OrganizationId", "EnvironmentId", "ReleaseRevision")
                        .IsUnique()
                        .HasDatabaseName("ux_schedule_plans_scope_release_revision")
                        .HasFilter("release_revision IS NOT NULL");

                    b.ToTable("schedule_plans", "scheduling", t =>
                        {
                            t.HasComment("BusinessScheduling generated, released, superseded, and revoked schedule plan headers.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlanAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Schedule plan assignment row id.");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("assignment_id")
                        .HasComment("Public assignment id.");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_utc")
                        .HasComment("Assignment end timestamp in UTC.");

                    b.Property<string>("ExplanationCode")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("explanation_code")
                        .HasComment("Scheduling explanation code.");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked")
                        .HasComment("Whether this assignment came from a locked input.");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("operation_id")
                        .HasComment("Public operation reference.");

                    b.Property<int>("OperationSequence")
                        .HasColumnType("integer")
                        .HasColumnName("operation_sequence")
                        .HasComment("Operation sequence within the work order route.");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("resource_id")
                        .HasComment("Assigned resource id.");

                    b.Property<Guid>("SchedulePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_plan_id")
                        .HasComment("Owning schedule plan aggregate id.");

                    b.Property<string>("StandardOperationCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("standard_operation_code")
                        .HasComment("ProductEngineering standard operation code used by MES to resolve current SOP or electronic work instructions.");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc")
                        .HasComment("Assignment start timestamp in UTC.");

                    b.Property<string>("WorkCenterId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("work_center_id")
                        .HasComment("Assigned work center id.");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("work_order_id")
                        .HasComment("Public work order reference.");

                    b.HasKey("Id");

                    b.HasIndex("SchedulePlanId", "AssignmentId")
                        .IsUnique();

                    b.ToTable("schedule_plan_assignments", "scheduling", t =>
                        {
                            t.HasComment("BusinessScheduling operation assignments in a schedule plan.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlanConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Schedule plan conflict row id.");

                    b.Property<string>("ConflictPublicId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("conflict_id")
                        .HasComment("Public conflict id.");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message")
                        .HasComment("Human-readable conflict explanation.");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("operation_id")
                        .HasComment("Affected operation reference.");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code")
                        .HasComment("Conflict reason code.");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("resource_id")
                        .HasComment("Affected resource reference.");

                    b.Property<Guid>("SchedulePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_plan_id")
                        .HasComment("Owning schedule plan aggregate id.");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity")
                        .HasComment("Conflict severity.");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("work_order_id")
                        .HasComment("Affected work order reference.");

                    b.HasKey("Id");

                    b.HasIndex("SchedulePlanId");

                    b.ToTable("schedule_plan_conflicts", "scheduling", t =>
                        {
                            t.HasComment("BusinessScheduling conflicts detected while generating a schedule plan.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlanInvalidation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Schedule plan invalidation row id.");

                    b.Property<string>("AffectedOperationId")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("affected_operation_id")
                        .HasComment("Affected operation id when available.");

                    b.Property<string>("AffectedResourceId")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("affected_resource_id")
                        .HasComment("Affected resource or device asset id when the event targets equipment.");

                    b.Property<string>("AffectedSkuCode")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("affected_sku_code")
                        .HasComment("Affected SKU code when the event changes material readiness.");

                    b.Property<string>("AffectedWorkOrderId")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("affected_work_order_id")
                        .HasComment("Affected work order id when the event targets a work order.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc")
                        .HasComment("UTC time when the source event occurred.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("plan_id")
                        .HasComment("Generated schedule plan invalidated by the upstream event.");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code")
                        .HasComment("Scheduling invalidation reason code.");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc")
                        .HasComment("UTC time when BusinessScheduling recorded the invalidation.");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_event_id")
                        .HasComment("Source integration event identifier.");

                    b.Property<string>("SourceEventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_event_type")
                        .HasComment("Source integration event type.");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_service")
                        .HasComment("Service that produced the source event.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "PlanId", "RecordedAtUtc")
                        .HasDatabaseName("ix_schedule_plan_invalidations_plan_recorded_at");

                    b.HasIndex("OrganizationId", "EnvironmentId", "PlanId", "SourceEventType", "SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_schedule_plan_invalidations_source_event");

                    b.ToTable("schedule_plan_invalidations", "scheduling", t =>
                        {
                            t.HasComment("Event-driven Scheduling plan invalidation projection for APS replan decisions.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlanResourceLoad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Schedule plan resource load row id.");

                    b.Property<int>("AssignedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_minutes")
                        .HasComment("Resource occupied minutes in the window, including processing plus setup/changeover time.");

                    b.Property<int>("AvailableMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("available_minutes")
                        .HasComment("Available capacity minutes in the window.");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("resource_id")
                        .HasComment("Resource id for the load window.");

                    b.Property<Guid>("SchedulePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_plan_id")
                        .HasComment("Owning schedule plan aggregate id.");

                    b.Property<decimal>("Utilization")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("utilization")
                        .HasComment("Assigned minutes divided by available minutes.");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end_utc")
                        .HasComment("Load window end timestamp in UTC.");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start_utc")
                        .HasComment("Load window start timestamp in UTC.");

                    b.HasKey("Id");

                    b.HasIndex("SchedulePlanId");

                    b.ToTable("schedule_plan_resource_loads", "scheduling", t =>
                        {
                            t.HasComment("BusinessScheduling resource load windows for a schedule plan.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlanUnscheduledOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Schedule plan unscheduled operation row id.");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message")
                        .HasComment("Human-readable unscheduled operation explanation.");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("operation_id")
                        .HasComment("Public operation reference.");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code")
                        .HasComment("Reason code explaining why the operation was not scheduled.");

                    b.Property<Guid>("SchedulePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_plan_id")
                        .HasComment("Owning schedule plan aggregate id.");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("work_order_id")
                        .HasComment("Public work order reference.");

                    b.HasKey("Id");

                    b.HasIndex("SchedulePlanId");

                    b.ToTable("schedule_plan_unscheduled_operations", "scheduling", t =>
                        {
                            t.HasComment("BusinessScheduling operations that could not be assigned inside the plan horizon.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.ScheduleProblemSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Scheduling problem snapshot row id.");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc")
                        .HasComment("UTC timestamp when the problem snapshot was captured.");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer")
                        .HasColumnName("contract_version")
                        .HasComment("Scheduling problem contract version.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<DateTimeOffset>("HorizonEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horizon_end_utc")
                        .HasComment("Scheduling horizon end timestamp in UTC.");

                    b.Property<DateTimeOffset>("HorizonStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horizon_start_utc")
                        .HasComment("Scheduling horizon start timestamp in UTC.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<string>("ProblemFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("problem_fingerprint")
                        .HasComment("Deterministic fingerprint of the scheduling problem input.");

                    b.Property<string>("ProblemId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("problem_id")
                        .HasComment("Public scheduling problem id.");

                    b.Property<string>("ProblemJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("problem_json")
                        .HasComment("Normalized scheduling problem payload used to validate later operation locks and overrides.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "ProblemId")
                        .IsUnique();

                    b.ToTable("schedule_problems", "scheduling", t =>
                        {
                            t.HasComment("BusinessScheduling normalized scheduling problem snapshots.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Infrastructure.IntegrationEvents.ProcessedIntegrationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Processed integration event identifier.");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("BusinessScheduling integration event consumer name.");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Source integration event identifier retained for traceability; idempotency uses IdempotencyKey.");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Integration event type.");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasComment("Integration event contract version.");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Deterministic BusinessScheduling idempotency key unique within a consumer.");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC time when BusinessScheduling processed the event.");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Service that produced the integration event.");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerName", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_processed_integration_events_consumer_idempotency_key");

                    b.HasIndex("SourceService", "EventType", "ProcessedAtUtc")
                        .HasDatabaseName("ix_processed_integration_events_source_type_processed_at");

                    b.ToTable("processed_integration_events", "scheduling", t =>
                        {
                            t.HasComment("Integration events already processed by BusinessScheduling for idempotent consumption.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Infrastructure.Urgency.OrderUrgencyArchiveBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Archive batch audit row id.");

                    b.Property<DateTimeOffset?>("ArchiveDeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archive_deleted_at_utc")
                        .HasComment("UTC timestamp when authorized exact object-version deletion completed.");

                    b.Property<string>("ArchiveDeletionActor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("archive_deletion_actor")
                        .HasComment("Actor recorded for exact archive-version deletion.");

                    b.Property<string>("ArchiveDeletionAuthorizationReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("archive_deletion_authorization_reference")
                        .HasComment("Independent authorization/change reference used for exact archive-version deletion.");

                    b.Property<string>("ArchiveDeletionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("archive_deletion_reason")
                        .HasComment("Reason recorded for exact archive-version deletion.");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc")
                        .HasComment("UTC timestamp when exact-version read-back evidence completed.");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count")
                        .HasComment("Number of archive attempts for this stable batch.");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("batch_id")
                        .HasComment("Stable source-row-generation-derived archive batch id.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC timestamp when this batch was first attempted.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code")
                        .HasComment("Stable failure classification for the latest attempt.");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message")
                        .HasComment("Sanitized latest failure detail.");

                    b.Property<DateTimeOffset>("MaxCalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_calculated_at_utc")
                        .HasComment("Newest UTC calculation time in the batch.");

                    b.Property<DateTimeOffset>("MinCalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("min_calculated_at_utc")
                        .HasComment("Oldest UTC calculation time in the batch.");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key")
                        .HasComment("Internal FileStorage object key; never exposed publicly.");

                    b.Property<string>("ObjectVersionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("object_version_id")
                        .HasComment("Exact immutable object-storage version id verified by FileStorage.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasComment("Monotonic optimistic concurrency revision protecting lifecycle transitions.");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256")
                        .HasComment("Lowercase SHA-256 of the archived JSON bytes.");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes")
                        .HasComment("Verified archive object size in bytes.");

                    b.Property<int>("SnapshotCount")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_count")
                        .HasComment("Number of snapshots represented by the archive batch.");

                    b.Property<string>("SnapshotIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_ids_json")
                        .HasComment("JSON array of Scheduling-owned source snapshot ids; produced and consumed by the retention worker with additive compatibility.");

                    b.Property<DateTimeOffset?>("SourceDeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_deleted_at_utc")
                        .HasComment("UTC timestamp when authorized source-row deletion committed.");

                    b.Property<string>("SourceDeletionActor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_deletion_actor")
                        .HasComment("Actor recorded for source-row deletion.");

                    b.Property<string>("SourceDeletionAuthorizationReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_deletion_authorization_reference")
                        .HasComment("Explicit authorization/change reference used for source-row deletion.");

                    b.Property<string>("SourceDeletionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_deletion_reason")
                        .HasComment("Reason recorded for source-row deletion.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status")
                        .HasComment("Retention lifecycle status: pending, archived, failed, source-deleted, or archive-deleted.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "BatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_urgency_archive_scope_batch");

                    b.HasIndex("OrganizationId", "EnvironmentId", "Status", "MaxCalculatedAtUtc")
                        .HasDatabaseName("ix_urgency_archive_scope_status_watermark");

                    b.ToTable("order_urgency_archive_batches", "scheduling", t =>
                        {
                            t.HasComment("Durable archive, deletion, and failure evidence for urgency snapshot retention batches.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Infrastructure.Urgency.OrderUrgencyRestoreAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Restore audit row id.");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor")
                        .HasComment("Authenticated operator reference.");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("batch_id")
                        .HasComment("Restored archive batch id.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<string>("ObjectVersionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("object_version_id")
                        .HasComment("Exact object version read during restore.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason")
                        .HasComment("Operator-provided restore reason.");

                    b.Property<DateTimeOffset>("RestoredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("restored_at_utc")
                        .HasComment("UTC restore completion timestamp.");

                    b.Property<int>("RestoredSnapshotCount")
                        .HasColumnType("integer")
                        .HasColumnName("restored_snapshot_count")
                        .HasComment("Number of missing snapshots rehydrated.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "BatchId", "RestoredAtUtc")
                        .HasDatabaseName("ix_urgency_restore_scope_batch_time");

                    b.ToTable("order_urgency_restore_audits", "scheduling", t =>
                        {
                            t.HasComment("Append-only operator audit for exact-version urgency archive restores.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Infrastructure.Urgency.OrderUrgencyRetentionLease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Lease row id.");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at_utc")
                        .HasComment("UTC timestamp when the current owner acquired the lease.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_id")
                        .HasComment("Business environment id.");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc")
                        .HasComment("UTC lease expiry; an expired lease may be taken over.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("organization_id")
                        .HasComment("Tenant organization id.");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_id")
                        .HasComment("Worker instance currently holding the lease.");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasComment("Monotonic optimistic concurrency revision.");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_urgency_retention_lease_expiry");

                    b.HasIndex("OrganizationId", "EnvironmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_urgency_retention_lease_scope");

                    b.ToTable("order_urgency_retention_leases", "scheduling", t =>
                        {
                            t.HasComment("Database-backed expiring leases preventing concurrent retention work per organization and environment.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Messaging.CAP.IntegrationEventDeadLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Dead-letter message id.");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name")
                        .HasComment("Integration event consumer name that rejected the message.");

                    b.Property<DateTimeOffset>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at_utc")
                        .HasComment("UTC time when the service stored the dead-letter message.");

                    b.Property<string>("EventClrType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_clr_type")
                        .HasComment("CLR contract type captured for replay diagnostics.");

                    b.Property<string>("EventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_id")
                        .HasComment("Rejected integration event id when present.");

                    b.Property<string>("EventJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_json")
                        .HasComment("Serialized rejected integration event envelope and payload.");

                    b.Property<string>("EventType")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("event_type")
                        .HasComment("Rejected integration event type when present.");

                    b.Property<int?>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version")
                        .HasComment("Rejected integration event envelope version when present.");

                    b.Property<string>("FailureCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failure_code")
                        .HasComment("Machine-readable reason the consumer rejected the message.");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_message")
                        .HasComment("Operator-readable rejection detail.");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("idempotency_key")
                        .HasComment("Rejected integration event idempotency key when present.");

                    b.Property<DateTimeOffset?>("ReplayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replayed_at_utc")
                        .HasComment("UTC time when the dead-letter message was marked replayed.");

                    b.Property<string>("SourceService")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("source_service")
                        .HasComment("Source service from the rejected event envelope when present.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasComment("Dead-letter status: Pending, Replayed, Failed, or Ignored.");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerName", "EventId");

                    b.HasIndex("ConsumerName", "Status", "DeadLetteredAtUtc");

                    b.ToTable("integration_event_dead_letters", "scheduling", t =>
                        {
                            t.HasComment("Integration events rejected before business handling and retained for replay triage.");
                        });
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.CapLock", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Instance")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastLockTime")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Key");

                    b.ToTable("cap_locks", "scheduling");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.PublishedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName");

                    b.ToTable("cap_published_messages", "scheduling");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.ReceivedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Group")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_ExpiresAt_StatusName1");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_Version_ExpiresAt_StatusName1");

                    b.ToTable("cap_received_messages", "scheduling");
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlanAssignment", b =>
                {
                    b.HasOne("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlan", null)
                        .WithMany("Assignments")
                        .HasForeignKey("SchedulePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlanConflict", b =>
                {
                    b.HasOne("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlan", null)
                        .WithMany("Conflicts")
                        .HasForeignKey("SchedulePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlanResourceLoad", b =>
                {
                    b.HasOne("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlan", null)
                        .WithMany("ResourceLoads")
                        .HasForeignKey("SchedulePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlanUnscheduledOperation", b =>
                {
                    b.HasOne("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlan", null)
                        .WithMany("UnscheduledOperations")
                        .HasForeignKey("SchedulePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Business.Scheduling.Domain.AggregatesModel.SchedulePlanAggregate.SchedulePlan", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Conflicts");

                    b.Navigation("ResourceLoads");

                    b.Navigation("UnscheduledOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
