services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: nerv
      POSTGRES_PASSWORD: nerv
      POSTGRES_DB: nerv_iip
    ports:
      - "${NERV_IIP_POSTGRES_PORT:-15432}:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: nervminio
      MINIO_ROOT_PASSWORD: nervminio
    ports:
      - "9000:9000"
      - "9001:9001"

  otel-collector:
    image: otel/opentelemetry-collector:0.116.1
    ports:
      - "4317:4317"
      - "4318:4318"
