// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nerv.IIP.Iam.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nerv.IIP.Iam.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525055540_AddExternalClientAuthorizationGrant")]
    partial class AddExternalClientAuthorizationGrant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("iam")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.ConnectorHostCredentialAggregate.ConnectorHostCredential", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Connector Host credential identifier.");

                    b.Property<string>("ConnectorHostId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Unique Connector Host identifier.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Credential environment identifier.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Credential organization identifier.");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Connector Host secret hash.");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Credential validity start time in UTC.");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Credential validity end time in UTC.");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorHostId")
                        .IsUnique();

                    b.ToTable("connector_host_credentials", "iam", t =>
                        {
                            t.HasComment("IAM credentials that authenticate Connector Hosts.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.ConnectorHostCredentialAggregate.ConnectorHostCredentialCapability", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Connector Host credential capability identifier.");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasComment("Capability code granted to the Connector Host credential.");

                    b.Property<string>("ConnectorHostCredentialId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Owning Connector Host credential identifier.");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorHostCredentialId", "CapabilityCode")
                        .IsUnique();

                    b.ToTable("connector_host_credential_capabilities", "iam", t =>
                        {
                            t.HasComment("IAM capability codes owned by Connector Host credentials.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.ExternalClientAggregate.AuthorizationGrant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Authorization grant identifier.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Grant environment scope.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Grant organization scope.");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasComment("Granted permission code.");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Principal identifier.");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Principal type, for example external-client.");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Grant revocation time in UTC.");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Grant validity start time in UTC.");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Grant validity end time in UTC.");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalType", "PrincipalId", "OrganizationId", "EnvironmentId", "PermissionCode")
                        .IsUnique();

                    b.ToTable("authorization_grants", "iam", t =>
                        {
                            t.HasComment("IAM authorization grants for non-user principals and scoped access.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.ExternalClientAggregate.ExternalClient", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("External client record identifier.");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Public client identifier used for client_credentials.");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasComment("External client display name.");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasComment("Whether the external client can authenticate.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("External client environment scope.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("External client organization scope.");

                    b.Property<int>("PermissionVersion")
                        .HasColumnType("integer")
                        .HasComment("External client permission version for token invalidation.");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("External client secret hash.");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("External client credential validity start time in UTC.");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("External client credential validity end time in UTC.");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("external_clients", "iam", t =>
                        {
                            t.HasComment("IAM external clients that can use client_credentials tokens.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.MembershipAggregate.Membership", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Membership identifier.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Membership environment identifier.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Membership organization identifier.");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Member user identifier.");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OrganizationId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("memberships", "iam", t =>
                        {
                            t.HasComment("IAM user memberships scoped to organization and environment.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.MembershipAggregate.MembershipRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasComment("Membership role assignment identifier.");

                    b.Property<string>("MembershipId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Owning membership identifier.");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Assigned role identifier.");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId", "RoleId")
                        .IsUnique();

                    b.ToTable("membership_roles", "iam", t =>
                        {
                            t.HasComment("IAM role assignments owned by memberships.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.OrganizationAggregate.IamEnvironment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Environment identifier.");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasComment("Soft delete flag.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Environment display name.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Owning organization identifier.");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasComment("Optimistic row version.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("Environment lifecycle status.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Id")
                        .IsUnique();

                    b.ToTable("environments", "iam", t =>
                        {
                            t.HasComment("IAM environments owned by organizations for access scoping.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.OrganizationAggregate.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Organization identifier.");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasComment("Soft delete flag.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Organization display name.");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasComment("Optimistic row version.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("Organization lifecycle status.");

                    b.HasKey("Id");

                    b.ToTable("organizations", "iam", t =>
                        {
                            t.HasComment("IAM organizations that scope tenants and their environments.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.RoleAggregate.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Role identifier.");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasComment("Soft delete flag.");

                    b.Property<string>("NormalizedRoleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Case-insensitive normalized role name.");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Unique role name.");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasComment("Optimistic row version.");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedRoleName")
                        .IsUnique();

                    b.ToTable("roles", "iam", t =>
                        {
                            t.HasComment("IAM roles that group permission codes for assignment.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.RoleAggregate.RolePermission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Role permission identifier.");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasComment("Permission code granted by the role.");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Owning role identifier.");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionCode")
                        .IsUnique();

                    b.ToTable("role_permissions", "iam", t =>
                        {
                            t.HasComment("IAM permission codes owned by roles.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.SeedAggregate.SeedManifest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Seed manifest identifier.");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Seed application time in UTC.");

                    b.Property<string>("OwnerService")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Service that owns the seed data.");

                    b.Property<string>("SeedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasComment("Seed data name.");

                    b.Property<string>("SeedVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Seed data version.");

                    b.HasKey("Id");

                    b.HasIndex("SeedName", "SeedVersion")
                        .IsUnique();

                    b.ToTable("seed_manifests", "iam", t =>
                        {
                            t.HasComment("IAM seed manifests recording applied seed data versions.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.UserAggregate.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("User identifier.");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasComment("Soft delete flag.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Unique user email address.");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasComment("Whether the user can authenticate.");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasComment("Consecutive failed login count.");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last successful login time in UTC.");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Unique login name used for authentication.");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Password hash used for credential verification.");

                    b.Property<int>("PermissionVersion")
                        .HasColumnType("integer")
                        .HasComment("Permission version embedded into issued credentials.");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasComment("Optimistic row version.");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Security stamp invalidating stale access tokens.");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LoginName")
                        .IsUnique();

                    b.ToTable("users", "iam", t =>
                        {
                            t.HasComment("IAM users that authenticate and receive scoped permissions.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.UserSessionAggregate.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("User session identifier.");

                    b.Property<string>("ClientInfo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Client information supplied during session creation.");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Session expiration time in UTC.");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Client IP address supplied during session creation.");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Session issue time in UTC.");

                    b.Property<int>("PermissionVersion")
                        .HasColumnType("integer")
                        .HasComment("Permission version captured when the session was issued.");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Refresh token hash used to rotate sessions.");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Session revocation time in UTC.");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Reason the session was revoked.");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Authenticated user identifier.");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash");

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("user_sessions", "iam", t =>
                        {
                            t.HasComment("IAM refresh sessions issued to authenticated users.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.ConnectorHostCredentialAggregate.ConnectorHostCredentialCapability", b =>
                {
                    b.HasOne("Nerv.IIP.Iam.Domain.AggregatesModel.ConnectorHostCredentialAggregate.ConnectorHostCredential", null)
                        .WithMany("Capabilities")
                        .HasForeignKey("ConnectorHostCredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.MembershipAggregate.MembershipRole", b =>
                {
                    b.HasOne("Nerv.IIP.Iam.Domain.AggregatesModel.MembershipAggregate.Membership", null)
                        .WithMany("Roles")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.RoleAggregate.RolePermission", b =>
                {
                    b.HasOne("Nerv.IIP.Iam.Domain.AggregatesModel.RoleAggregate.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.ConnectorHostCredentialAggregate.ConnectorHostCredential", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.MembershipAggregate.Membership", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Nerv.IIP.Iam.Domain.AggregatesModel.RoleAggregate.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
