// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nerv.IIP.Ops.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nerv.IIP.Ops.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626130722_AddOpsAuditHashChain")]
    partial class AddOpsAuditHashChain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ops")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.AuditRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Audit record identifier.");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Audit action.");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Audit actor.");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Correlation identifier.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Environment scope for the Ops audit chain.");

                    b.Property<string>("IntegrityHash")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasComment("Tamper-evident SHA-256 hash over immutable audit fields plus sequence and previous hash.");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Audit occurrence time in UTC.");

                    b.Property<string>("OperationTaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Operation task identifier.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Organization scope for the Ops audit chain.");

                    b.Property<string>("PreviousIntegrityHash")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasComment("Previous audit record integrity hash in the organization and environment chain; empty for genesis.");

                    b.Property<long>("SequenceNo")
                        .HasColumnType("bigint")
                        .HasComment("Monotonic Ops audit chain sequence number within organization and environment scope.");

                    b.HasKey("Id");

                    b.HasIndex("OperationTaskId", "OccurredAtUtc");

                    b.HasIndex("OrganizationId", "EnvironmentId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("audit_records", "ops", t =>
                        {
                            t.HasComment("Ops audit records for operation task lifecycle events and user-visible traceability.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationAttempt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Operation attempt identifier.");

                    b.Property<string>("AbandonReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Reason recorded when the attempt lease is abandoned or times out.");

                    b.Property<int?>("AttemptNo")
                        .HasColumnType("integer")
                        .HasComment("One-based attempt number for this operation task.");

                    b.Property<string>("ConnectorHostId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Connector host identifier.");

                    b.Property<string>("FailureJson")
                        .HasColumnType("text")
                        .HasComment("JSON failure details produced by Connector Host execution, consumed by Ops and Gateway diagnostics; additive optional keys are compatible, removing or changing key semantics requires Ops contract versioning.");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Attempt finish time in UTC.");

                    b.Property<string>("LeaseId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Lease identifier returned by Ops claim and required for heartbeat or abandon updates; null for legacy attempts created before lease claim protocol fields existed.");

                    b.Property<DateTimeOffset?>("LeasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC time when Ops granted this lease.");

                    b.Property<DateTimeOffset?>("LeasedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC time when the lease expires and becomes eligible for requeue.");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasComment("Maximum attempts allowed before an expired or abandoned task becomes failed.");

                    b.Property<string>("OperationTaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Operation task identifier.");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Attempt start time in UTC.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("Attempt status.");

                    b.HasKey("Id");

                    b.HasIndex("OperationTaskId");

                    b.HasIndex("Status", "LeasedUntilUtc");

                    b.ToTable("operation_attempts", "ops", t =>
                        {
                            t.HasComment("Ops operation execution attempts created when connector hosts claim operation tasks.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Operation task identifier.");

                    b.Property<DateTimeOffset?>("ApprovalDecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Approval decision time in UTC.");

                    b.Property<string>("ApprovalDecidedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Actor that approved or rejected the operation.");

                    b.Property<string>("ApprovalDecisionReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Approval decision reason.");

                    b.Property<DateTimeOffset?>("ApprovalRequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Approval request time in UTC.");

                    b.Property<string>("ApprovalRequestedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Actor that requested approval for a high-risk operation.");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("Operation approval status when approval is required.");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Correlation identifier.");

                    b.Property<int>("DefaultLeaseDurationSeconds")
                        .HasColumnType("integer")
                        .HasComment("Template-provided default connector lease duration captured at task creation.");

                    b.Property<int>("DefaultMaxAttempts")
                        .HasColumnType("integer")
                        .HasComment("Template-provided default maximum execution attempts captured at task creation.");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasComment("Soft delete flag.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Environment identifier.");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Request idempotency key.");

                    b.Property<string>("IdempotencyScope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Organization and environment scoped idempotency key.");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Target instance key.");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Operation code.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Organization identifier.");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("JSON operation parameter dictionary produced by Gateway and Ops task creation, consumed by Connector Host execution; additive optional keys are compatible, required key or semantic changes require Ops contract versioning.");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Requested time in UTC.");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Requester.");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasComment("Whether the selected template requires approval before task execution.");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasComment("Optimistic row version.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("Operation task status.");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyScope")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "Status", "RequestedAtUtc");

                    b.ToTable("operation_tasks", "ops", t =>
                        {
                            t.HasComment("Ops operation task aggregate roots requested through Gateway and executed by connector hosts.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTemplateAggregate.OperationTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Operation template identifier.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Template creation time in UTC.");

                    b.Property<int>("DefaultLeaseDurationSeconds")
                        .HasColumnType("integer")
                        .HasComment("Default connector lease duration in seconds.");

                    b.Property<int>("DefaultMaxAttempts")
                        .HasColumnType("integer")
                        .HasComment("Default maximum execution attempts.");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasComment("Soft delete flag.");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Operation display name.");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasComment("Whether this operation template can create new tasks.");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Registered operation code.");

                    b.Property<string>("ParameterSchemaJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("JSON schema describing accepted operation parameters.");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasComment("Whether this template requires manual approval before execution.");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("Operation risk level.");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasComment("Optimistic row version.");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Template last update time in UTC.");

                    b.HasKey("Id");

                    b.HasIndex("OperationCode")
                        .IsUnique();

                    b.HasIndex("Enabled", "RiskLevel");

                    b.ToTable("operation_templates", "ops", t =>
                        {
                            t.HasComment("Ops operation templates registering supported operation codes and execution defaults.");
                        });
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.CapLock", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Instance")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLockTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("cap_locks", "ops");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.PublishedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("DataSourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cap_published_messages", "ops");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.ReceivedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cap_received_messages", "ops");
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.AuditRecord", b =>
                {
                    b.HasOne("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationTask", null)
                        .WithMany("AuditRecords")
                        .HasForeignKey("OperationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationAttempt", b =>
                {
                    b.HasOne("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationTask", null)
                        .WithMany("Attempts")
                        .HasForeignKey("OperationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationTask", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("AuditRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
