// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nerv.IIP.Ops.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nerv.IIP.Ops.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ops")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.AuditRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Audit record identifier.");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Audit action.");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Audit actor.");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Correlation identifier.");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Audit occurrence time in UTC.");

                    b.Property<string>("OperationTaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Operation task identifier.");

                    b.HasKey("Id");

                    b.HasIndex("OperationTaskId", "OccurredAtUtc");

                    b.ToTable("audit_records", "ops");
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationAttempt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Operation attempt identifier.");

                    b.Property<string>("ConnectorHostId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Connector host identifier.");

                    b.Property<string>("FailureJson")
                        .HasColumnType("text")
                        .HasComment("Serialized failure reason.");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Attempt finish time in UTC.");

                    b.Property<string>("OperationTaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Operation task identifier.");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Attempt start time in UTC.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("Attempt status.");

                    b.HasKey("Id");

                    b.HasIndex("OperationTaskId");

                    b.ToTable("operation_attempts", "ops");
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Operation task identifier.");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Correlation identifier.");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasComment("Soft delete flag.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Environment identifier.");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Request idempotency key.");

                    b.Property<string>("IdempotencyScope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Organization and environment scoped idempotency key.");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Target instance key.");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Operation code.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Organization identifier.");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Serialized operation parameters.");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Requested time in UTC.");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Requester.");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasComment("Optimistic row version.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("Operation task status.");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyScope")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "Status", "RequestedAtUtc");

                    b.ToTable("operation_tasks", "ops");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.CapLock", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Instance")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLockTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("cap_locks", "ops");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.PublishedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("DataSourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cap_published_messages", "ops");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.ReceivedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cap_received_messages", "ops");
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.AuditRecord", b =>
                {
                    b.HasOne("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationTask", null)
                        .WithMany("AuditRecords")
                        .HasForeignKey("OperationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationAttempt", b =>
                {
                    b.HasOne("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationTask", null)
                        .WithMany("Attempts")
                        .HasForeignKey("OperationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Ops.Domain.AggregatesModel.OperationTaskAggregate.OperationTask", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("AuditRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
