export const BUSINESS_PERMISSION_CODES = {
  masterDataProductsRead: 'business.masterdata.products.read',
  masterDataResourcesRead: 'business.masterdata.resources.read',
  engineeringDocumentsRead: 'business.engineering.documents.read',
  engineeringItemsRead: 'business.engineering.items.read',
  engineeringBomsRead: 'business.engineering.boms.read',
  engineeringRoutingsRead: 'business.engineering.routings.read',
  engineeringStandardOperationsRead: 'business.engineering.standard-operations.read',
  engineeringChangesRead: 'business.engineering.changes.read',
  engineeringProductionVersionsRead: 'business.engineering.production-versions.read',
  planningDemandsRead: 'business.planning.demands.read',
  planningMrpRead: 'business.planning.mrp.read',
  planningSuggestionsManage: 'business.planning.suggestions.manage',
  schedulingPlansRead: 'business.scheduling.plans.read',
  schedulingPlansManage: 'business.scheduling.plans.manage',
  schedulingPlansRelease: 'business.scheduling.plans.release',
  mesFoundationRead: 'business.mes.foundation.read',
  mesOverviewRead: 'business.mes.overview.read',
  mesPlansRead: 'business.mes.plans.read',
  mesWorkOrdersRead: 'business.mes.work-orders.read',
  mesMaterialsRead: 'business.mes.materials.read',
  mesDispatchRead: 'business.mes.dispatch.read',
  mesOperationsRead: 'business.mes.operations.read',
  mesReportingRead: 'business.mes.reporting.read',
  mesQualityRead: 'business.mes.quality.read',
  mesReceiptsRead: 'business.mes.receipts.read',
  mesDowntimeRead: 'business.mes.downtime.read',
  mesHandoversRead: 'business.mes.handovers.read',
  mesTraceabilityRead: 'business.mes.traceability.read',
  mesSchedulesRead: 'business.mes.schedules.read',
  mesSchedulesManage: 'business.mes.schedules.manage',
  mesCapacityRead: 'business.mes.capacity.read',
  qualityInspectionRecordsRead: 'business.quality.inspection-records.read',
  qualityNcrRead: 'business.quality.ncr.read',
  qualityNcrManage: 'business.quality.ncr.manage',
  inventoryLedgerRead: 'business.inventory.ledger.read',
  inventoryMovementsCreate: 'business.inventory.movements.create',
  inventoryCountsManage: 'business.inventory.counts.manage',
  wmsReceiptsRead: 'business.wms.receipts.read',
  wmsShipmentsRead: 'business.wms.shipments.read',
  wmsAutomationManage: 'business.wms.automation.manage',
  erpProcurementRead: 'business.erp.procurement.read',
  erpSalesRead: 'business.erp.sales.read',
  erpFinanceRead: 'business.erp.finance.read',
  iiotTelemetryRead: 'business.iiot.telemetry.read',
  iiotAlarmsRead: 'business.iiot.alarms.read',
  maintenanceWorkOrdersRead: 'business.maintenance.work-orders.read',
  maintenancePlansRead: 'business.maintenance.plans.read',
  approvalsRead: 'business.approvals.read',
  approvalsManage: 'business.approvals.manage',
  notificationMessagesRead: 'notifications.messages.read',
  notificationTasksRead: 'notifications.tasks.read',
} as const

export type BusinessPermissionCode =
  (typeof BUSINESS_PERMISSION_CODES)[keyof typeof BUSINESS_PERMISSION_CODES]

const P = BUSINESS_PERMISSION_CODES

export const BUSINESS_DOMAIN_PERMISSIONS = {
  workbench: Object.values(P),
  masterData: [
    P.masterDataProductsRead,
    P.masterDataResourcesRead,
  ],
  engineering: [
    P.engineeringDocumentsRead,
    P.engineeringItemsRead,
    P.engineeringBomsRead,
    P.engineeringRoutingsRead,
    P.engineeringStandardOperationsRead,
    P.engineeringChangesRead,
    P.engineeringProductionVersionsRead,
  ],
  planning: [
    P.planningDemandsRead,
    P.planningMrpRead,
    P.planningSuggestionsManage,
    P.schedulingPlansRead,
    P.schedulingPlansManage,
    P.schedulingPlansRelease,
  ],
  mes: [
    P.mesFoundationRead,
    P.mesOverviewRead,
    P.mesPlansRead,
    P.mesWorkOrdersRead,
    P.mesMaterialsRead,
    P.mesDispatchRead,
    P.mesOperationsRead,
    P.mesReportingRead,
    P.mesQualityRead,
    P.mesReceiptsRead,
    P.mesDowntimeRead,
    P.mesHandoversRead,
    P.mesTraceabilityRead,
    P.mesSchedulesRead,
    P.mesSchedulesManage,
    P.mesCapacityRead,
  ],
  quality: [
    P.qualityInspectionRecordsRead,
    P.qualityNcrRead,
    P.qualityNcrManage,
  ],
  inventory: [
    P.inventoryLedgerRead,
    P.inventoryMovementsCreate,
    P.inventoryCountsManage,
  ],
  wms: [
    P.wmsReceiptsRead,
    P.wmsShipmentsRead,
    P.wmsAutomationManage,
  ],
  erp: [
    P.erpProcurementRead,
    P.erpSalesRead,
    P.erpFinanceRead,
  ],
  equipment: [
    P.iiotTelemetryRead,
    P.iiotAlarmsRead,
    P.maintenanceWorkOrdersRead,
    P.maintenancePlansRead,
  ],
  approval: [
    P.approvalsRead,
    P.approvalsManage,
  ],
} as const satisfies Record<string, readonly BusinessPermissionCode[]>
