import type { SchedulePlanContract } from '@nerv-iip/api-client'

// 开发预览用样例计划(非产品数据,仅供 dev preview / 视觉确认)。
const H = 3_600_000
const base = Date.parse('2026-06-10T08:00:00.000Z')
const iso = (offsetH: number) => new Date(base + offsetH * H).toISOString()

export const previewPlan: SchedulePlanContract = {
  planId: 'preview-1',
  status: 'generated',
  algorithmVersion: 'heuristic-1',
  generatedAtUtc: iso(0),
  assignments: [
    {
      assignmentId: 'WO1-10',
      orderId: 'WO-2026-001',
      operationId: '下料',
      operationSequence: 10,
      resourceId: '激光切割-01',
      workCenterId: '激光切割-01',
      startUtc: iso(0),
      endUtc: iso(3),
      isLocked: false,
    },
    {
      assignmentId: 'WO1-20',
      orderId: 'WO-2026-001',
      operationId: '折弯',
      operationSequence: 20,
      resourceId: '折弯-02',
      workCenterId: '折弯-02',
      startUtc: iso(3),
      endUtc: iso(6),
      isLocked: false,
    },
    {
      assignmentId: 'WO1-30',
      orderId: 'WO-2026-001',
      operationId: '焊接',
      operationSequence: 30,
      resourceId: '焊接-01',
      workCenterId: '焊接-01',
      startUtc: iso(6),
      endUtc: iso(11),
      isLocked: true,
    },
    {
      assignmentId: 'WO2-10',
      orderId: 'WO-2026-002',
      operationId: '下料',
      operationSequence: 10,
      resourceId: '激光切割-01',
      workCenterId: '激光切割-01',
      startUtc: iso(3),
      endUtc: iso(7),
      isLocked: false,
    },
    {
      assignmentId: 'WO2-20',
      orderId: 'WO-2026-002',
      operationId: '机加工',
      operationSequence: 20,
      resourceId: '加工中心-03',
      workCenterId: '加工中心-03',
      startUtc: iso(7),
      endUtc: iso(13),
      isLocked: false,
    },
    {
      assignmentId: 'WO3-10',
      orderId: 'WO-2026-003',
      operationId: '装配',
      operationSequence: 10,
      resourceId: '焊接-01',
      workCenterId: '焊接-01',
      startUtc: iso(11),
      endUtc: iso(16),
      isLocked: false,
    },
    {
      assignmentId: 'WO3-20',
      orderId: 'WO-2026-003',
      operationId: '总装',
      operationSequence: 20,
      resourceId: '加工中心-03',
      workCenterId: '加工中心-03',
      startUtc: iso(13),
      endUtc: iso(20),
      isLocked: false,
    },
    // 下游四道:装配 / 表面处理 / 包装 / 检测。补进来是为了让预览能真正**看见八个色槽**——
    // 此前预览只有 切割/折弯/焊接/机加 四个工作中心,恰好绕开了 assy↔cut、insp↔bend、
    // pack↔cut 三组撞色,视觉确认自然发现不了(#1399 M1)。八族齐了才是有效的分色回归面。
    {
      assignmentId: 'WO3-30',
      orderId: 'WO-2026-003',
      operationId: '部装',
      operationSequence: 30,
      resourceId: '装配-04',
      workCenterId: '装配-04',
      startUtc: iso(20),
      endUtc: iso(24),
      isLocked: false,
    },
    {
      assignmentId: 'WO3-40',
      orderId: 'WO-2026-003',
      operationId: '喷涂',
      operationSequence: 40,
      resourceId: '涂装-05',
      workCenterId: '涂装-05',
      startUtc: iso(24),
      endUtc: iso(28),
      isLocked: false,
    },
    {
      assignmentId: 'WO3-50',
      orderId: 'WO-2026-003',
      operationId: '终检',
      operationSequence: 50,
      resourceId: '检测-06',
      workCenterId: '检测-06',
      startUtc: iso(28),
      endUtc: iso(31),
      isLocked: false,
    },
    {
      assignmentId: 'WO3-60',
      orderId: 'WO-2026-003',
      operationId: '装箱',
      operationSequence: 60,
      resourceId: '包装-07',
      workCenterId: '包装-07',
      startUtc: iso(31),
      endUtc: iso(34),
      isLocked: false,
    },
  ],
  resourceLoads: [
    {
      resourceId: '激光切割-01',
      windowStartUtc: iso(0),
      windowEndUtc: iso(24),
      assignedMinutes: 420,
      availableMinutes: 480,
      utilization: 0.88,
    },
    {
      resourceId: '折弯-02',
      windowStartUtc: iso(0),
      windowEndUtc: iso(24),
      assignedMinutes: 180,
      availableMinutes: 480,
      utilization: 0.38,
    },
    {
      resourceId: '焊接-01',
      windowStartUtc: iso(0),
      windowEndUtc: iso(24),
      assignedMinutes: 600,
      availableMinutes: 480,
      utilization: 1.25,
    },
    {
      resourceId: '加工中心-03',
      windowStartUtc: iso(0),
      windowEndUtc: iso(24),
      assignedMinutes: 540,
      availableMinutes: 480,
      utilization: 1.13,
    },
  ],
  conflicts: [
    {
      conflictId: 'cf1',
      reasonCode: 'capacity',
      severity: 'warning',
      orderId: 'WO-2026-003',
      operationId: '装配',
      resourceId: '焊接-01',
      message: '焊接-01 在该时段超出可用产能',
    },
    {
      conflictId: 'cf2',
      reasonCode: 'dueDate',
      severity: 'error',
      orderId: 'WO-2026-003',
      operationId: '总装',
      resourceId: '加工中心-03',
      message: '预计完工晚于交期',
    },
  ],
  unscheduledOperations: [
    {
      orderId: 'WO-2026-004',
      operationId: '喷涂',
      reasonCode: 'material',
      message: '面漆未齐套,等待采购到货',
    },
  ],
  changeSummary: [
    {
      orderId: 'WO-2026-001',
      operationId: '焊接',
      changeType: 'preserved',
      message: '锁定,保持原计划',
    },
    {
      orderId: 'WO-2026-003',
      operationId: '总装',
      changeType: 'delayed',
      message: '受前序占用,后移 3 小时',
    },
  ],
  ganttItems: [],
}
