// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nerv.IIP.Business.ProductEngineering.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nerv.IIP.Business.ProductEngineering.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("product_engineering")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.EngineeringBomAggregate.EngineeringBom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Engineering BOM aggregate id.");

                    b.Property<string>("BomCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bom_code")
                        .HasComment("Engineering BOM business code.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the EBOM was created.");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date")
                        .HasComment("First effective date after release.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the EBOM is valid.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<string>("ParentItemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_item_code")
                        .HasComment("Parent engineering item code.");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revision")
                        .HasComment("Engineering BOM revision.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Engineering BOM lifecycle status.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the EBOM was last updated.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "BomCode", "Revision")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "ParentItemCode", "Status");

                    b.ToTable("engineering_boms", "product_engineering", t =>
                        {
                            t.HasComment("ProductEngineering released and draft engineering BOM versions.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.EngineeringChangeAggregate.EngineeringChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Engineering change aggregate id.");

                    b.Property<string>("ApprovalReferenceId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("approval_reference_id")
                        .HasComment("Business approval chain or approval result reference id.");

                    b.Property<string>("ChangeNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("change_number")
                        .HasComment("Engineering change order or notice number.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the engineering change was opened.");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date")
                        .HasComment("First effective date after release.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the change applies.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason")
                        .HasComment("Engineering change reason.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Engineering change lifecycle status.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the engineering change was last updated.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "ChangeNumber")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "Status");

                    b.ToTable("engineering_changes", "product_engineering", t =>
                        {
                            t.HasComment("ProductEngineering ECO and ECN change release facts.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.EngineeringDocumentAggregate.EngineeringDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Engineering document aggregate id.");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("content_type")
                        .HasComment("File content type.");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_number")
                        .HasComment("Business document number.");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_type")
                        .HasComment("Engineering document type such as CAD drawing or process sheet.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the document is valid.");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("file_id")
                        .HasComment("File Storage public file id; object keys are not stored.");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name")
                        .HasComment("Original or display file name.");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_code")
                        .HasComment("Optional engineering item code this document revision describes.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc")
                        .HasComment("UTC time when the document reference was registered.");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revision")
                        .HasComment("Document revision.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "DocumentNumber", "Revision")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "FileId", "Revision")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "ItemCode", "DocumentType");

                    b.ToTable("engineering_documents", "product_engineering", t =>
                        {
                            t.HasComment("ProductEngineering engineering document references to File Storage files such as CAD drawings and design packages.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.EngineeringItemAggregate.EngineeringItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Engineering item aggregate id.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the item revision was created.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the item revision is valid.");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_code")
                        .HasComment("Engineering item code.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name")
                        .HasComment("Engineering item display name.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revision")
                        .HasComment("Engineering item revision.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Engineering item lifecycle status.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the item revision was last updated.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "Status");

                    b.HasIndex("OrganizationId", "EnvironmentId", "ItemCode", "Revision")
                        .IsUnique();

                    b.ToTable("engineering_items", "product_engineering", t =>
                        {
                            t.HasComment("ProductEngineering versioned engineering item revisions used by EBOM authoring.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.ManufacturingBomAggregate.ManufacturingBom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Manufacturing BOM aggregate id.");

                    b.Property<string>("BomCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bom_code")
                        .HasComment("Manufacturing BOM business code.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the MBOM was created.");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date")
                        .HasComment("First effective date after release.");

                    b.Property<string>("EngineeringBomVersionId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("engineering_bom_version_id")
                        .HasComment("Released EBOM version id used as design source.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the MBOM is valid.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revision")
                        .HasComment("Manufacturing BOM revision.");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code")
                        .HasComment("Produced SKU code.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Manufacturing BOM lifecycle status.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the MBOM was last updated.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "BomCode", "Revision")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "SkuCode", "Status");

                    b.ToTable("manufacturing_boms", "product_engineering", t =>
                        {
                            t.HasComment("ProductEngineering manufacturing BOM versions that reference released EBOM facts and process recipe lines.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.ProductionVersionAggregate.ProductionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Production version aggregate id.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the version was created.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the version is valid.");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default")
                        .HasComment("Default version flag for the SKU and effective window.");

                    b.Property<decimal?>("LotSizeMax")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("lot_size_max")
                        .HasComment("Maximum lot size covered by this version.");

                    b.Property<decimal?>("LotSizeMin")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("lot_size_min")
                        .HasComment("Minimum lot size covered by this version.");

                    b.Property<string>("MbomVersionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mbom_version_id")
                        .HasComment("Released manufacturing BOM version id.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority")
                        .HasComment("Selection priority among matching production versions.");

                    b.Property<string>("RoutingVersionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("routing_version_id")
                        .HasComment("Released routing version id.");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code")
                        .HasComment("Finished or semi-finished SKU code.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasComment("Production version lifecycle status.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the version was last updated.");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from")
                        .HasComment("First effective production date.");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to")
                        .HasComment("Last effective production date, null for open-ended.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "MbomVersionId", "RoutingVersionId");

                    b.HasIndex("OrganizationId", "EnvironmentId", "SkuCode", "Status");

                    b.HasIndex("OrganizationId", "EnvironmentId", "SkuCode", "IsDefault", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_production_versions_organization_id_environment_id_sku_cod~1");

                    b.ToTable("production_versions", "product_engineering", t =>
                        {
                            t.HasComment("ProductEngineering production versions binding released MBOM and routing versions for planning and MES work order creation.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.RoutingAggregate.Routing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Routing aggregate id.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the routing was created.");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date")
                        .HasComment("First effective date after release.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the routing is valid.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revision")
                        .HasComment("Routing revision.");

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("routing_code")
                        .HasComment("Routing business code.");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code")
                        .HasComment("Produced SKU code.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Routing lifecycle status.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the routing was last updated.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "RoutingCode", "Revision")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "SkuCode", "Status");

                    b.ToTable("routings", "product_engineering", t =>
                        {
                            t.HasComment("ProductEngineering routing versions with ordered work center operation steps.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Coding.CodeCounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Code counter surrogate identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CurrentValue")
                        .HasColumnType("bigint")
                        .HasColumnName("current_value")
                        .HasComment("Last allocated sequence value within the counter scope.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment scope for the code counter.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization scope for the code counter.");

                    b.Property<string>("ResetKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reset_key")
                        .HasComment("Sequence reset bucket derived from the active code rule.");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_key")
                        .HasComment("Code rule key governed by this counter.");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_code")
                        .HasComment("Optional site or plant scope; empty string means global within organization and environment.");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Optimistic concurrency token incremented whenever the counter advances.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "RuleKey", "SiteCode", "ResetKey")
                        .IsUnique()
                        .HasDatabaseName("ux_code_counters_scope");

                    b.ToTable("code_counters", "product_engineering", t =>
                        {
                            t.HasComment("Service-local code counters scoped by organization, environment, rule key, optional site and reset bucket.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Coding.CodeIdempotencyKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Code idempotency record surrogate identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code")
                        .HasComment("Allocated business code returned for this idempotency key.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC timestamp when the idempotency key was first recorded.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment scope for the idempotency key.");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("idempotency_key")
                        .HasComment("Client supplied stable idempotency key for ordinary create requests.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization scope for the idempotency key.");

                    b.Property<string>("PayloadFingerprint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("payload_fingerprint")
                        .HasComment("Canonical request payload fingerprint used to reject key reuse with different create data.");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_key")
                        .HasComment("Code rule key governed by the idempotency key.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "RuleKey", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_code_idempotency_keys_scope");

                    b.ToTable("code_idempotency_keys", "product_engineering", t =>
                        {
                            t.HasComment("Service-local idempotency records that bind create request keys to allocated codes.");
                        });
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.CapLock", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Instance")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastLockTime")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Key");

                    b.ToTable("cap_locks", "product_engineering");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.PublishedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName");

                    b.ToTable("cap_published_messages", "product_engineering");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.ReceivedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Group")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_ExpiresAt_StatusName1");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_Version_ExpiresAt_StatusName1");

                    b.ToTable("cap_received_messages", "product_engineering");
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.EngineeringBomAggregate.EngineeringBom", b =>
                {
                    b.OwnsMany("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.EngineeringBomAggregate.EngineeringBomLine", "Lines", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("ChildItemCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("child_item_code")
                                .HasComment("Child engineering item code.");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("quantity")
                                .HasComment("Component quantity.");

                            b1.Property<string>("UnitOfMeasureCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit_of_measure_code")
                                .HasComment("Quantity unit of measure code.");

                            b1.Property<Guid>("engineering_bom_id")
                                .HasColumnType("uuid")
                                .HasColumnName("engineering_bom_id")
                                .HasComment("Owning engineering BOM id.");

                            b1.HasKey("id");

                            b1.HasIndex("engineering_bom_id", "ChildItemCode")
                                .IsUnique();

                            b1.ToTable("engineering_bom_lines", "product_engineering", t =>
                                {
                                    t.HasComment("Engineering BOM component lines.");
                                });

                            b1.WithOwner()
                                .HasForeignKey("engineering_bom_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.EngineeringChangeAggregate.EngineeringChange", b =>
                {
                    b.OwnsMany("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.EngineeringChangeAggregate.EngineeringChangeAffectedVersion", "AffectedVersions", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("VersionId")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("version_id")
                                .HasComment("Affected version id.");

                            b1.Property<string>("VersionKind")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("version_kind")
                                .HasComment("Affected version kind such as document, engineering-bom, manufacturing-bom, routing or production-version.");

                            b1.Property<Guid>("engineering_change_id")
                                .HasColumnType("uuid")
                                .HasColumnName("engineering_change_id")
                                .HasComment("Owning engineering change id.");

                            b1.HasKey("id");

                            b1.HasIndex("engineering_change_id", "VersionKind", "VersionId")
                                .IsUnique();

                            b1.ToTable("engineering_change_affected_versions", "product_engineering", t =>
                                {
                                    t.HasComment("Engineering change affected document, BOM, routing or production version references.");
                                });

                            b1.WithOwner()
                                .HasForeignKey("engineering_change_id");
                        });

                    b.Navigation("AffectedVersions");
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.ManufacturingBomAggregate.ManufacturingBom", b =>
                {
                    b.OwnsMany("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.ManufacturingBomAggregate.ManufacturingBomMaterialLine", "MaterialLines", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("quantity")
                                .HasComment("Consumed material quantity.");

                            b1.Property<decimal>("ScrapRate")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("scrap_rate")
                                .HasComment("Expected scrap rate for the material line.");

                            b1.Property<string>("SkuCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("sku_code")
                                .HasComment("Consumed SKU code.");

                            b1.Property<string>("UnitOfMeasureCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit_of_measure_code")
                                .HasComment("Quantity unit of measure code.");

                            b1.Property<Guid>("manufacturing_bom_id")
                                .HasColumnType("uuid")
                                .HasColumnName("manufacturing_bom_id")
                                .HasComment("Owning manufacturing BOM id.");

                            b1.HasKey("id");

                            b1.HasIndex("manufacturing_bom_id", "SkuCode")
                                .IsUnique();

                            b1.ToTable("manufacturing_bom_material_lines", "product_engineering", t =>
                                {
                                    t.HasComment("Manufacturing BOM SKU material lines.");
                                });

                            b1.WithOwner()
                                .HasForeignKey("manufacturing_bom_id");
                        });

                    b.OwnsMany("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.ManufacturingBomAggregate.ManufacturingBomRecipeLine", "RecipeLines", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("ParameterCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("parameter_code")
                                .HasComment("Process parameter code.");

                            b1.Property<string>("TargetValue")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("target_value")
                                .HasComment("Target process parameter value.");

                            b1.Property<string>("UnitOfMeasureCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit_of_measure_code")
                                .HasComment("Parameter unit of measure code.");

                            b1.Property<Guid>("manufacturing_bom_id")
                                .HasColumnType("uuid")
                                .HasColumnName("manufacturing_bom_id")
                                .HasComment("Owning manufacturing BOM id.");

                            b1.HasKey("id");

                            b1.HasIndex("manufacturing_bom_id", "ParameterCode")
                                .IsUnique();

                            b1.ToTable("manufacturing_bom_recipe_lines", "product_engineering", t =>
                                {
                                    t.HasComment("Manufacturing BOM process recipe and formula parameter lines.");
                                });

                            b1.WithOwner()
                                .HasForeignKey("manufacturing_bom_id");
                        });

                    b.Navigation("MaterialLines");

                    b.Navigation("RecipeLines");
                });

            modelBuilder.Entity("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.RoutingAggregate.Routing", b =>
                {
                    b.OwnsMany("Nerv.IIP.Business.ProductEngineering.Domain.AggregatesModel.RoutingAggregate.RoutingOperation", "Operations", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("OperationCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("operation_code")
                                .HasComment("MasterData reference-data operation code.");

                            b1.Property<string>("OperationName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("operation_name")
                                .HasComment("Operation display name submitted with routing release.");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence")
                                .HasComment("Positive operation sequence number.");

                            b1.Property<int>("StandardMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("standard_minutes")
                                .HasComment("Standard operation duration in minutes.");

                            b1.Property<string>("WorkCenterCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("work_center_code")
                                .HasComment("MasterData work center code reference.");

                            b1.Property<Guid>("routing_id")
                                .HasColumnType("uuid")
                                .HasColumnName("routing_id")
                                .HasComment("Owning routing id.");

                            b1.HasKey("id");

                            b1.HasIndex("routing_id", "Sequence")
                                .IsUnique();

                            b1.ToTable("routing_operations", "product_engineering", t =>
                                {
                                    t.HasComment("Routing ordered operation steps and work center references.");
                                });

                            b1.WithOwner()
                                .HasForeignKey("routing_id");
                        });

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
