// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Nerv.IIP.Business.Mes.Infrastructure;

#nullable disable

namespace Nerv.IIP.Business.Mes.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801170000_AddMesLineSideReceiptSourceAllocations")]
    partial class AddMesLineSideReceiptSourceAllocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Reuse the checked-in current model snapshot so this migration keeps the same
            // target-model metadata as EF scaffolding without duplicating the service model here.
            new ModelSnapshotBridge().Build(modelBuilder);
        }

        private sealed class ModelSnapshotBridge : ApplicationDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder) => BuildModel(modelBuilder);
        }
    }
}
