// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nerv.IIP.Business.Mes.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nerv.IIP.Business.Mes.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mes")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nerv.IIP.Business.Mes.Domain.AggregatesModel.FinishedGoodsReceiptRequestAggregate.FinishedGoodsReceiptRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Finished goods receipt request aggregate id.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id for the receipt request.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity")
                        .HasComment("Finished goods quantity requested for receipt.");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc")
                        .HasComment("UTC time when MES requested finished goods receipt.");

                    b.Property<string>("SkuId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_id")
                        .HasComment("MasterData SKU public id to receive.");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uom_code")
                        .HasComment("MasterData unit of measure code for the receipt quantity.");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("work_order_id")
                        .HasComment("MES business work order id that produced finished goods.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "WorkOrderId", "SkuId", "RequestedAtUtc");

                    b.ToTable("finished_goods_receipt_requests", "mes", t =>
                        {
                            t.HasComment("MES finished goods receipt request facts exposed for WMS or inventory movement boundaries.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Mes.Domain.AggregatesModel.OperationTaskAggregate.OperationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Operation task aggregate id.");

                    b.Property<string>("AlternativeWorkCenterIds")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("alternative_work_center_ids")
                        .HasComment("Pipe-delimited alternate work center public ids copied from routing snapshot.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the operation task fact was created.");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ticks")
                        .HasComment("Operation duration stored as .NET ticks for deterministic scheduler reconstruction.");

                    b.Property<DateTimeOffset>("EarliestStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earliest_start_utc")
                        .HasComment("Earliest UTC start time allowed for this operation.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id for the operation execution context.");

                    b.Property<DateTimeOffset?>("ExistingEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("existing_end_utc")
                        .HasComment("Existing UTC end time for in-progress operation preservation.");

                    b.Property<DateTimeOffset?>("ExistingStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("existing_start_utc")
                        .HasComment("Existing UTC start time for in-progress operation preservation.");

                    b.Property<int>("OperationSequence")
                        .HasColumnType("integer")
                        .HasColumnName("operation_sequence")
                        .HasComment("Routing operation sequence used for deterministic scheduling order.");

                    b.Property<string>("OperationTaskIdValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_task_id")
                        .HasComment("Business operation task id unique within organization and environment.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Operation lifecycle status used by the scheduler.");

                    b.Property<string>("WorkCenterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("work_center_id")
                        .HasComment("Primary MasterData work center public id.");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("work_order_id")
                        .HasComment("MES business work order id this operation belongs to.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "OperationTaskIdValue")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "WorkOrderId", "OperationSequence");

                    b.ToTable("operation_tasks", "mes", t =>
                        {
                            t.HasComment("MES operation task facts created from routing step snapshots for scheduling and execution tracking.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Mes.Domain.AggregatesModel.ProductionReportAggregate.ProductionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Production report aggregate id.");

                    b.Property<bool>("CompletesOperation")
                        .HasColumnType("boolean")
                        .HasColumnName("completes_operation")
                        .HasComment("Whether this report marks the operation as completed.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id for the production report.");

                    b.Property<decimal>("GoodQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("good_quantity")
                        .HasComment("Good quantity reported for the operation.");

                    b.Property<string>("OperationTaskId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_task_id")
                        .HasComment("MES operation task id reported against.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<DateTimeOffset>("ReportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at_utc")
                        .HasComment("UTC time when production was reported.");

                    b.Property<decimal>("ScrapQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("scrap_quantity")
                        .HasComment("Scrap quantity reported for the operation.");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("work_order_id")
                        .HasComment("MES business work order id reported against.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "WorkOrderId", "OperationTaskId", "ReportedAtUtc");

                    b.ToTable("production_reports", "mes", t =>
                        {
                            t.HasComment("MES production report facts recording good and scrap quantities for operation execution.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Mes.Domain.AggregatesModel.ScheduleAggregate.DeviceAssetWorkCenterMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Device asset work center mapping aggregate id.");

                    b.Property<string>("DeviceAssetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_asset_id")
                        .HasComment("Maintenance device asset public id.");

                    b.Property<string>("EnvironmentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id; null means the mapping is global.");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id; null means the mapping is global.");

                    b.Property<string>("WorkCenterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("work_center_id")
                        .HasComment("MasterData work center public id used by MES scheduling.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "DeviceAssetId")
                        .IsUnique();

                    b.ToTable("device_asset_work_center_mappings", "mes", t =>
                        {
                            t.HasComment("MES local mapping from Maintenance device asset public ids to MasterData work center public ids.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Mes.Domain.AggregatesModel.ScheduleAggregate.ScheduleResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Schedule result aggregate id.");

                    b.Property<string>("AffectedWorkOrderIdsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("affected_work_order_ids_json")
                        .HasComment("JSON affected work order id list produced by MES scheduler; producer is MES, consumers are MES/WMS/read APIs, compatibility is append-only fields.");

                    b.Property<string>("AssignmentsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignments_json")
                        .HasComment("JSON schedule assignments produced by MES scheduler; producer is MES, consumers are MES/WMS/read APIs, compatibility is append-only fields.");

                    b.Property<int>("ScheduleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_version")
                        .HasComment("Monotonic schedule version preserving current MES behavior.");

                    b.Property<DateTimeOffset>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc")
                        .HasComment("UTC time requested for the schedule run.");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("trigger")
                        .HasComment("Business trigger that caused the schedule run.");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleVersion")
                        .IsUnique();

                    b.HasIndex("Trigger", "ScheduledAtUtc");

                    b.ToTable("schedule_results", "mes", t =>
                        {
                            t.HasComment("MES schedule result facts produced by the deterministic rule scheduler.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Mes.Domain.AggregatesModel.ScheduleAggregate.WorkCenterUnavailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Work center unavailability aggregate id.");

                    b.Property<string>("DeviceAssetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_asset_id")
                        .HasComment("Maintenance device asset public id that produced the unavailable window, when applicable.");

                    b.Property<string>("EnvironmentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id; null means the scheduling constraint is global.");

                    b.Property<DateTimeOffset>("FromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("from_utc")
                        .HasComment("UTC start of the unavailable window.");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id; null means the scheduling constraint is global.");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason")
                        .HasComment("Business reason for the scheduling constraint.");

                    b.Property<DateTimeOffset?>("ToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to_utc")
                        .HasComment("UTC end of the unavailable window; null means still unavailable.");

                    b.Property<string>("WorkCenterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("work_center_id")
                        .HasComment("MasterData work center public id unavailable for scheduling.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "DeviceAssetId", "ToUtc");

                    b.HasIndex("OrganizationId", "EnvironmentId", "WorkCenterId", "FromUtc", "ToUtc")
                        .HasDatabaseName("IX_work_center_unavailabilities_organization_id_environment_i~1");

                    b.ToTable("work_center_unavailabilities", "mes", t =>
                        {
                            t.HasComment("MES scheduling constraint facts for unavailable work centers from maintenance or manual inputs.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.Mes.Domain.AggregatesModel.WorkOrderAggregate.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Work order aggregate id.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the MES work order fact was created.");

                    b.Property<DateTimeOffset>("DueUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_utc")
                        .HasComment("UTC due time used by the deterministic rule scheduler.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id for the work order execution context.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id.");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority")
                        .HasComment("Scheduling priority; rush work orders use a high priority value.");

                    b.Property<string>("ProductionVersionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("production_version_id")
                        .HasComment("ProductEngineering production version public id; MES does not duplicate engineering facts.");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity")
                        .HasComment("Planned production quantity.");

                    b.Property<string>("SkuId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_id")
                        .HasComment("MasterData SKU public id for the item being produced.");

                    b.Property<string>("WorkOrderIdValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("work_order_id")
                        .HasComment("Business work order id unique within organization and environment.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "WorkOrderIdValue")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "SkuId", "DueUtc");

                    b.ToTable("work_orders", "mes", t =>
                        {
                            t.HasComment("MES durable work orders created from business demand and ProductEngineering production version references.");
                        });
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.CapLock", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Instance")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastLockTime")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Key");

                    b.ToTable("cap_locks", "mes");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.PublishedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName");

                    b.ToTable("cap_published_messages", "mes");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.ReceivedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Group")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_ExpiresAt_StatusName1");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_Version_ExpiresAt_StatusName1");

                    b.ToTable("cap_received_messages", "mes");
                });
#pragma warning restore 612, 618
        }
    }
}
