namespace Nerv.IIP.Contracts.MasterData;

public sealed record MasterDataResourceItem(
    string ResourceType,
    string Code,
    string DisplayName,
    bool Active,
    string SnapshotVersion,
    string? PartnerType = null,
    IReadOnlyCollection<string>? PartnerRoles = null,
    string? SiteCode = null,
    string? PlantCode = null,
    string? LineCode = null,
    string? WorkshopCode = null,
    int? CapacityMinutesPerDay = null,
    string? WorkCenterCode = null,
    string? Status = null,
    string? Category = null,
    string? MaterialType = null,
    string? CodeSet = null,
    string? BaseUomCode = null,
    string? TaxId = null,
    string? ParentDepartmentCode = null,
    string? DepartmentCode = null,
    string? ShiftCode = null,
    string? UserId = null,
    string? SkillCode = null,
    string? SkillLevel = null,
    DateOnly? EffectiveFrom = null,
    DateOnly? EffectiveTo = null,
    string? FromUomCode = null,
    string? ToUomCode = null,
    decimal? Factor = null,
    decimal? Offset = null,
    int? Precision = null,
    string? RoundingMode = null,
    string? DeviceAssetId = null,
    DateOnly? PurchaseDate = null,
    decimal? PurchaseCost = null,
    string? PurchaseCurrencyCode = null,
    DateOnly? WarrantyExpiresOn = null,
    string? SupplierPartnerCode = null,
    string? StationCode = null,
    string? ParentDeviceId = null,
    DateOnly? RetiredOn = null,
    decimal? CreditLimit = null,
    string? CreditCurrencyCode = null,
    string? JobTitle = null,
    string? EmploymentStatus = null,
    string? Phone = null,
    string? Timezone = null,
    TimeOnly? StartsAt = null,
    TimeOnly? EndsAt = null,
    bool? CrossesMidnight = null,
    int? PaidMinutes = null,
    int? BreakMinutes = null);

public sealed record ListMasterDataResourcesResponse(
    IReadOnlyCollection<MasterDataResourceItem> Resources,
    int Total,
    bool Truncated = false,
    int? Limit = null);
