// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nerv.IIP.Business.BarcodeLabel.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nerv.IIP.Business.BarcodeLabel.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("barcode")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.BarcodeRuleAggregate.BarcodeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Barcode rule aggregate id.");

                    b.PrimitiveCollection<List<string>>("AllowedSourceDocumentTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_source_document_types")
                        .HasComment("Allowed source document types for this barcode rule.");

                    b.Property<string>("BarcodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode_type")
                        .HasComment("Barcode symbology such as code128, qr or datamatrix.");

                    b.Property<string>("ChecksumRule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("checksum_rule")
                        .HasComment("Checksum policy name for generated barcode values.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the rule was created.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the barcode rule applies.");

                    b.Property<int?>("Gs1CompanyPrefixLength")
                        .HasColumnType("integer")
                        .HasColumnName("gs1_company_prefix_length")
                        .HasComment("Explicit GS1 company prefix length used to split SGTIN EPC URI values for GS1 barcode rules.");

                    b.Property<int>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length")
                        .HasComment("Maximum generated barcode length.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the barcode rule.");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("prefix")
                        .HasComment("Barcode prefix included in generated label values.");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_code")
                        .HasComment("Business barcode rule code unique in an organization and environment.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Rule lifecycle status: active or inactive.");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the rule was last changed.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "RuleCode")
                        .IsUnique();

                    b.ToTable("barcode_rules", "barcode", t =>
                        {
                            t.HasComment("Barcode rule facts for deterministic label value generation.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.LabelPrintBatchAggregate.LabelPrintBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Label print batch aggregate id.");

                    b.Property<Guid>("BarcodeRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("barcode_rule_id")
                        .HasComment("Barcode rule id used for deterministic label generation.");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc")
                        .HasComment("UTC time when the print batch finished generation.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the print batch was created.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the print batch was created.");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key")
                        .HasComment("Client supplied idempotency key for print batch creation.");

                    b.Property<Guid>("LabelTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_template_id")
                        .HasComment("Label template id used for the print batch.");

                    b.Property<string>("LabelValuesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_values_json")
                        .HasComment("Label variable values JSON captured for repeatable printing.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the print batch.");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("requested_quantity")
                        .HasComment("Requested number of labels generated for the batch.");

                    b.Property<string>("SourceDocumentId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("source_document_id")
                        .HasComment("Source business document public id.");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_document_type")
                        .HasComment("Source workflow or document type requesting label printing.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Print batch status such as completed.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EnvironmentId", "SourceDocumentType", "SourceDocumentId");

                    b.ToTable("label_print_batches", "barcode", t =>
                        {
                            t.HasComment("Label print batch facts and idempotency records.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.LabelPrintBatchAggregate.LabelPrintItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Label print item id.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the print item was generated.");

                    b.Property<string>("EpcUri")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("epc_uri")
                        .HasComment("EPC URI derived from GTIN and serial number for EPCIS traceability.");

                    b.Property<string>("FileId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("file_id")
                        .HasComment("Optional FileStorage file id for rendered label output.");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin")
                        .HasComment("Parsed or generated GS1 GTIN including check digit for serialized labels.");

                    b.Property<Guid>("LabelPrintBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_print_batch_id")
                        .HasComment("Owning label print batch id.");

                    b.Property<string>("LabelValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label_value")
                        .HasComment("Generated deterministic barcode or label value.");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_no")
                        .HasComment("Batch or lot number encoded in the generated GS1 label.");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no")
                        .HasComment("Generated label sequence number within the print batch.");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("serial_number")
                        .HasComment("Serialized unit identifier encoded in the generated GS1 label.");

                    b.HasKey("Id");

                    b.HasIndex("LabelValue");

                    b.HasIndex("LabelPrintBatchId", "SequenceNo")
                        .IsUnique();

                    b.HasIndex("Gtin", "LotNo", "SerialNumber");

                    b.ToTable("label_print_items", "barcode", t =>
                        {
                            t.HasComment("Generated label print item facts for a print batch.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.LabelTemplateAggregate.LabelTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Label template aggregate id.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC time when the template was created.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the template applies.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the template.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Template lifecycle status: active or inactive.");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_code")
                        .HasComment("Business label template code unique in an organization and environment.");

                    b.Property<string>("TemplateFileId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("template_file_id")
                        .HasComment("FileStorage file id for the template asset; object keys are not stored publicly.");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_name")
                        .HasComment("Human readable label template name.");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC time when the template was last changed.");

                    b.Property<string>("VariableSchemaJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variable_schema_json")
                        .HasComment("Template variable schema JSON consumed by print clients.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "Status");

                    b.HasIndex("OrganizationId", "EnvironmentId", "TemplateCode")
                        .IsUnique();

                    b.ToTable("label_templates", "barcode", t =>
                        {
                            t.HasComment("Label template metadata with FileStorage file id references only.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.ScanRecordAggregate.ScanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Scan record aggregate id.");

                    b.Property<string>("BusinessAction")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_action")
                        .HasComment("Downstream business action selected for the accepted scan.");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_code")
                        .HasComment("Device or PDA code that captured the scan.");

                    b.Property<string>("DownstreamEventId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("downstream_event_id")
                        .HasComment("Deterministic downstream event id for idempotent business action routing.");

                    b.Property<string>("DownstreamProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("downstream_processing_status")
                        .HasComment("Downstream processing status for the scan, such as observed, requested or not-required.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the scan occurred.");

                    b.Property<string>("EpcUri")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("epc_uri")
                        .HasComment("EPC URI derived from parsed GTIN and serial number.");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin")
                        .HasComment("GS1 GTIN parsed from an accepted scan value.");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key")
                        .HasComment("Client supplied idempotency key for scan creation.");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_code")
                        .HasComment("Inventory or workflow location supplied by scan context.");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_no")
                        .HasComment("GS1 lot or batch parsed from an accepted scan value.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the scan fact.");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("owner_id")
                        .HasComment("Optional inventory owner id supplied by scan context.");

                    b.Property<string>("OwnerType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_type")
                        .HasComment("Inventory owner type supplied by scan context.");

                    b.Property<string>("QualityStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("quality_status")
                        .HasComment("Quality status supplied by scan context for inventory movement routing.");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity")
                        .HasComment("Quantity parsed from GS1 AI 30 or supplied by the scan workflow.");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason")
                        .HasComment("Reason for rejected scans.");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("result")
                        .HasComment("Scan result: accepted or rejected.");

                    b.Property<DateTimeOffset>("ScannedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at_utc")
                        .HasComment("UTC time when the scan was recorded.");

                    b.Property<string>("ScannedValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scanned_value")
                        .HasComment("Raw barcode value scanned by the device.");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("serial_number")
                        .HasComment("GS1 serial number parsed from an accepted scan value.");

                    b.Property<string>("SiteCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site_code")
                        .HasComment("Site code supplied by scan context for downstream business action routing.");

                    b.Property<string>("SkuCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code")
                        .HasComment("SKU code supplied by scan context for downstream business action routing.");

                    b.Property<string>("SourceDocumentId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("source_document_id")
                        .HasComment("Source business document public id associated with the scan.");

                    b.Property<string>("SourceWorkflow")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_workflow")
                        .HasComment("Workflow that produced the scan fact, such as receiving or picking.");

                    b.Property<string>("Sscc")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("sscc")
                        .HasComment("GS1 SSCC-18 logistic unit identifier parsed from AI 00 when present.");

                    b.Property<string>("UomCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uom_code")
                        .HasComment("Unit of measure supplied by scan context for downstream business action routing.");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EnvironmentId", "EpcUri")
                        .IsUnique()
                        .HasDatabaseName("UX_scan_records_epc_uri")
                        .HasFilter("epc_uri IS NOT NULL");

                    b.HasIndex("OrganizationId", "EnvironmentId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_scan_records_idempotency");

                    b.HasIndex("OrganizationId", "EnvironmentId", "Sscc");

                    b.HasIndex("OrganizationId", "EnvironmentId", "DeviceCode", "ScannedAtUtc");

                    b.HasIndex("OrganizationId", "EnvironmentId", "Gtin", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_scan_records_gtin_serial_no_lot")
                        .HasFilter("gtin IS NOT NULL AND lot_no IS NULL AND serial_number IS NOT NULL");

                    b.HasIndex("OrganizationId", "EnvironmentId", "SourceWorkflow", "SourceDocumentId");

                    b.HasIndex("OrganizationId", "EnvironmentId", "Gtin", "LotNo", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_scan_records_gtin_lot_serial")
                        .HasFilter("gtin IS NOT NULL AND lot_no IS NOT NULL AND serial_number IS NOT NULL");

                    b.HasIndex("OrganizationId", "EnvironmentId", "ScannedValue", "SourceWorkflow", "SourceDocumentId")
                        .IsUnique()
                        .HasDatabaseName("UX_scan_records_accepted_scan_natural_key")
                        .HasFilter("result = 'accepted'");

                    b.ToTable("scan_records", "barcode", t =>
                        {
                            t.HasComment("Append-only barcode scan facts captured from devices and workflows.");
                        });
                });

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.TraceabilityAggregate.EpcisEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("EPCIS event id.");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action")
                        .HasComment("EPCIS action value such as ADD or OBSERVE.");

                    b.Property<string>("BusinessStep")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_step")
                        .HasComment("Business step represented by the EPCIS event.");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("disposition")
                        .HasComment("Disposition associated with the EPCIS event.");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_id")
                        .HasComment("Environment id where the EPCIS event occurred.");

                    b.Property<string>("EpcUri")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("epc_uri")
                        .HasComment("EPC URI associated with the serialized event.");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type")
                        .HasComment("EPCIS event type such as commissioning or objectEvent.");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin")
                        .HasComment("GS1 GTIN associated with the event.");

                    b.Property<Guid?>("LabelPrintBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_print_batch_id")
                        .HasComment("Optional label print batch id that owns commissioning events.");

                    b.Property<Guid?>("LabelPrintItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_print_item_id")
                        .HasComment("Optional label print item id that caused a commissioning event.");

                    b.Property<string>("LabelValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label_value")
                        .HasComment("Raw barcode value or generated label value associated with the event.");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_no")
                        .HasComment("Lot or batch associated with the event.");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc")
                        .HasComment("UTC time when the EPCIS event occurred.");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_id")
                        .HasComment("Organization tenant id that owns the EPCIS event.");

                    b.Property<string>("ParentEpcUri")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("parent_epc_uri")
                        .HasComment("Parent EPC URI for aggregation events when a standards-compliant parent URI is available.");

                    b.Property<string>("ParentSscc")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("parent_sscc")
                        .HasComment("Parent SSCC-18 logistic unit for EPCIS aggregation or disaggregation events.");

                    b.Property<Guid?>("ScanRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_record_id")
                        .HasComment("Optional scan record id that caused an object event.");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("serial_number")
                        .HasComment("Serialized unit associated with the event.");

                    b.Property<string>("SourceDocumentId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("source_document_id")
                        .HasComment("Source business document public id associated with the event.");

                    b.Property<string>("SourceWorkflow")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_workflow")
                        .HasComment("Source workflow that created the event.");

                    b.HasKey("Id");

                    b.HasIndex("LabelPrintBatchId");

                    b.HasIndex("LabelPrintItemId");

                    b.HasIndex("ScanRecordId");

                    b.HasIndex("OrganizationId", "EnvironmentId", "ParentSscc");

                    b.HasIndex("OrganizationId", "EnvironmentId", "EventType", "EpcUri")
                        .IsUnique()
                        .HasDatabaseName("UX_epcis_events_epc_uri")
                        .HasFilter("epc_uri IS NOT NULL");

                    b.HasIndex("OrganizationId", "EnvironmentId", "SourceWorkflow", "SourceDocumentId");

                    b.HasIndex("OrganizationId", "EnvironmentId", "EventType", "Gtin", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_epcis_events_gtin_serial_no_lot")
                        .HasFilter("gtin IS NOT NULL AND lot_no IS NULL AND serial_number IS NOT NULL");

                    b.HasIndex("OrganizationId", "EnvironmentId", "EventType", "Gtin", "LotNo", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_epcis_events_gtin_lot_serial")
                        .HasFilter("gtin IS NOT NULL AND lot_no IS NOT NULL AND serial_number IS NOT NULL");

                    b.ToTable("epcis_events", "barcode", t =>
                        {
                            t.HasComment("EPCIS traceability events generated from serialized label commissioning and accepted scans.");
                        });
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.CapLock", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Instance")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastLockTime")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Key");

                    b.ToTable("CAPLock", "barcode");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.PublishedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName");

                    b.ToTable("CAPPublishedMessage", "barcode");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.ReceivedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Group")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_ExpiresAt_StatusName1");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_Version_ExpiresAt_StatusName1");

                    b.ToTable("CAPReceivedMessage", "barcode");
                });

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.LabelPrintBatchAggregate.LabelPrintItem", b =>
                {
                    b.HasOne("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.LabelPrintBatchAggregate.LabelPrintBatch", null)
                        .WithMany("Items")
                        .HasForeignKey("LabelPrintBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.TraceabilityAggregate.EpcisEvent", b =>
                {
                    b.HasOne("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.LabelPrintBatchAggregate.LabelPrintBatch", null)
                        .WithMany("EpcisEvents")
                        .HasForeignKey("LabelPrintBatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.ScanRecordAggregate.ScanRecord", null)
                        .WithMany("EpcisEvents")
                        .HasForeignKey("ScanRecordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.LabelPrintBatchAggregate.LabelPrintBatch", b =>
                {
                    b.Navigation("EpcisEvents");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Nerv.IIP.Business.BarcodeLabel.Domain.AggregatesModel.ScanRecordAggregate.ScanRecord", b =>
                {
                    b.Navigation("EpcisEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
