# Script-Governance:
#   Category: check
#   SideEffects:
#     - Reads C# test sources belonging to projects in backend/Nerv.IIP.sln
#     - Reads and validates the backend test-determinism baseline
#   Writes:
#     - None
#   Cleanup:
#     - None
#   Requires:
#     - PowerShell 7
#     - .NET SDK 10

[CmdletBinding()]
param(
    [string] $SourceRoot = (Join-Path $PSScriptRoot '../backend'),

    [string] $BaselinePath = (Join-Path $PSScriptRoot '../backend/test-determinism-baseline.json')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

. (Join-Path $PSScriptRoot 'lib/ScriptAutomation.ps1')

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$backendRoot = (Resolve-Path (Join-Path $repoRoot 'backend')).Path
$solutionPath = Join-Path $backendRoot 'Nerv.IIP.sln'
$allowedPatterns = @('Task.Delay', 'Thread.Sleep', 'ShortLease', 'UnreachableAddress', 'StaticSetter')
$requiredBaselineFields = @('path', 'pattern', 'lineTextSha256', 'ownerIssue', 'reason', 'exitCondition', 'expiresOn')

function Resolve-RepoInputPath {
    param(
        [Parameter(Mandatory)]
        [string] $InputPath
    )

    $candidate = if ([System.IO.Path]::IsPathRooted($InputPath)) {
        $InputPath
    }
    else {
        Join-Path $repoRoot $InputPath
    }

    return (Resolve-Path -LiteralPath $candidate -ErrorAction Stop).Path
}

function Get-RepoRelativePath {
    param(
        [Parameter(Mandatory)]
        [string] $Path
    )

    return ([System.IO.Path]::GetRelativePath($repoRoot, $Path) -replace '\\', '/')
}

function Get-LineTextSha256 {
    param(
        [Parameter(Mandatory)]
        [string] $LineText
    )

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($LineText.Trim())
    $hash = [System.Security.Cryptography.SHA256]::HashData($bytes)
    return [System.Convert]::ToHexString($hash).ToLowerInvariant()
}

function Test-GeneratedSource {
    param(
        [Parameter(Mandatory)]
        [System.IO.FileInfo] $File
    )

    $relativePath = Get-RepoRelativePath -Path $File.FullName
    if ($relativePath -match '(?i)(^|/)(obj|bin|migrations)(/|$)') {
        return $true
    }

    if ($File.Name -match '(?i)(\.g|\.generated|\.designer|\.AssemblyInfo|\.GlobalUsings)\.cs$') {
        return $true
    }

    $head = @(Get-Content -LiteralPath $File.FullName -TotalCount 5)
    return ($head -join "`n") -match '(?i)<auto-generated'
}

function Get-DirectSourceFiles {
    param(
        [Parameter(Mandatory)]
        [string] $ResolvedSourceRoot
    )

    if (Test-Path -LiteralPath $ResolvedSourceRoot -PathType Leaf) {
        if ([System.IO.Path]::GetExtension($ResolvedSourceRoot) -cne '.cs') {
            return @()
        }

        return @((Get-Item -LiteralPath $ResolvedSourceRoot))
    }

    return @(Get-ChildItem -LiteralPath $ResolvedSourceRoot -Recurse -File -Filter '*.cs')
}

function Test-IsTestProject {
    param(
        [Parameter(Mandatory)]
        [string] $ProjectPath
    )

    if ([System.IO.Path]::GetFileNameWithoutExtension($ProjectPath) -match '(?i)Tests$') {
        return $true
    }

    $projectContent = Get-Content -LiteralPath $ProjectPath -Raw
    return $projectContent -match '(?is)<IsTestProject>\s*true\s*</IsTestProject>'
}

function Get-SolutionTestSourceFiles {
    $solutionList = Invoke-DotNetOutput `
        -Arguments @('sln', $solutionPath, 'list') `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 60 `
        -Name 'backend-test-determinism-solution-list'

    $projectPaths = @(
        $solutionList.Stdout -split "`r?`n" |
            ForEach-Object { $_.Trim() } |
            Where-Object { $_ -match '(?i)\.csproj$' } |
            ForEach-Object { Join-Path $backendRoot ($_ -replace '\\', [System.IO.Path]::DirectorySeparatorChar) } |
            Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
            Where-Object { Test-IsTestProject -ProjectPath $_ } |
            Sort-Object -Unique
    )

    if ($projectPaths.Count -eq 0) {
        throw "No C# test projects were returned for solution '$solutionPath'."
    }

    $files = foreach ($projectPath in $projectPaths) {
        $projectDirectory = Split-Path -Parent $projectPath
        Get-ChildItem -LiteralPath $projectDirectory -Recurse -File -Filter '*.cs'
    }

    return @($files | Sort-Object FullName -Unique)
}

function Test-IsIgnoredCommentLine {
    param(
        [Parameter(Mandatory)]
        [string] $TrimmedLine
    )

    return $TrimmedLine.StartsWith('//') -or
        $TrimmedLine.StartsWith('/*') -or
        $TrimmedLine.StartsWith('*')
}

function Test-ShortLeaseWindow {
    param(
        [Parameter(Mandatory)]
        [string] $Line,

        [Parameter(Mandatory)]
        [string] $Lookahead
    )

    $milliseconds = [regex]::Match(
        $Lookahead,
        '(?i)\b\w*(?:Lease|Renew)\w*\b\s*(?:=|:|\()\s*TimeSpan\s*\.\s*FromMilliseconds\s*\(\s*(?<value>\d+(?:\.\d+)?)\s*\)'
    )
    if ($milliseconds.Success -and $milliseconds.Index -ge $Line.Length) {
        $milliseconds = [System.Text.RegularExpressions.Match]::Empty
    }
    if ($milliseconds.Success -and [decimal] $milliseconds.Groups['value'].Value -lt 1000) {
        return $true
    }

    $seconds = [regex]::Match(
        $Lookahead,
        '(?i)\b\w*(?:Lease|Renew)\w*\b\s*(?:=|:|\()\s*TimeSpan\s*\.\s*FromSeconds\s*\(\s*(?<value>\d+(?:\.\d+)?)\s*\)'
    )
    if ($seconds.Success -and $seconds.Index -ge $Line.Length) {
        $seconds = [System.Text.RegularExpressions.Match]::Empty
    }
    if ($seconds.Success -and [decimal] $seconds.Groups['value'].Value -lt 1) {
        return $true
    }

    $numericWindow = [regex]::Match(
        $Line,
        '(?i)\b(?:\w*Lease\w*|\w*Renew\w*)(?:Milliseconds|Ms|Seconds)\s*=\s*(?<value>\d+(?:\.\d+)?)'
    )
    if (-not $numericWindow.Success) {
        return $false
    }

    $value = [decimal] $numericWindow.Groups['value'].Value
    return ($numericWindow.Value -match '(?i)(Milliseconds|Ms)\s*=') -and $value -lt 1000 -or
        ($numericWindow.Value -match '(?i)Seconds\s*=') -and $value -lt 1
}

function Test-LookaheadPatternStartsOnLine {
    param(
        [Parameter(Mandatory)]
        [string] $Line,

        [Parameter(Mandatory)]
        [string] $Lookahead,

        [Parameter(Mandatory)]
        [string] $Pattern
    )

    $match = [regex]::Match($Lookahead, $Pattern)
    return $match.Success -and $match.Index -lt $Line.Length
}

function Get-LinePatterns {
    param(
        [Parameter(Mandatory)]
        [string] $Line,

        [Parameter(Mandatory)]
        [string] $Lookahead
    )

    $patterns = New-Object System.Collections.Generic.List[string]

    if ($Line -match '(?<![\w.])(?:System\.Threading\.Tasks\.)?Task\s*\.\s*Delay\s*\(') {
        $patterns.Add('Task.Delay')
    }
    if ($Line -match '(?<![\w.])(?:System\.Threading\.)?Thread\s*\.\s*Sleep\s*\(') {
        $patterns.Add('Thread.Sleep')
    }
    if (Test-ShortLeaseWindow -Line $Line -Lookahead $Lookahead) {
        $patterns.Add('ShortLease')
    }
    if (
        $Line -match '(?i)127\.0\.0\.1\s*:\s*1(?!\d)' -or
        $Line -match '(?i)\bPort\s*=\s*1(?=\s*[,;"'']|\s*$)'
    ) {
        $patterns.Add('UnreachableAddress')
    }
    if (
        $Line -match '(?<![\w.])(?:System\.)?Environment\s*\.\s*SetEnvironmentVariable\s*\(' -or
        ($Line -match '\bValidatorOptions\s*\.\s*Global\b' -and
            (Test-LookaheadPatternStartsOnLine -Line $Line -Lookahead $Lookahead -Pattern '\bValidatorOptions\s*\.\s*Global\b(?:\s*\.\s*\w+)+\s*=')) -or
        ($Line -match '\bCultureInfo\s*\.\s*(?:CurrentCulture|CurrentUICulture|DefaultThreadCurrentCulture|DefaultThreadCurrentUICulture)\b' -and
            (Test-LookaheadPatternStartsOnLine -Line $Line -Lookahead $Lookahead -Pattern '\bCultureInfo\s*\.\s*(?:CurrentCulture|CurrentUICulture|DefaultThreadCurrentCulture|DefaultThreadCurrentUICulture)\b\s*=')) -or
        ($Line -match '\bThread\s*\.\s*CurrentThread\s*\.\s*(?:CurrentCulture|CurrentUICulture)\b' -and
            (Test-LookaheadPatternStartsOnLine -Line $Line -Lookahead $Lookahead -Pattern '\bThread\s*\.\s*CurrentThread\s*\.\s*(?:CurrentCulture|CurrentUICulture)\b\s*='))
    ) {
        $patterns.Add('StaticSetter')
    }

    return @($patterns | Sort-Object -Unique)
}

function Get-SourceFindings {
    param(
        [Parameter(Mandatory)]
        [System.IO.FileInfo[]] $Files
    )

    $findings = New-Object System.Collections.Generic.List[object]

    foreach ($file in $Files) {
        if (Test-GeneratedSource -File $file) {
            continue
        }

        $relativePath = Get-RepoRelativePath -Path $file.FullName
        $lines = @(Get-Content -LiteralPath $file.FullName)
        for ($index = 0; $index -lt $lines.Count; $index++) {
            $trimmedLine = "$($lines[$index])".Trim()
            if ([string]::IsNullOrWhiteSpace($trimmedLine) -or (Test-IsIgnoredCommentLine -TrimmedLine $trimmedLine)) {
                continue
            }

            $lookaheadEnd = [Math]::Min($index + 2, $lines.Count - 1)
            $lookahead = (($lines[$index..$lookaheadEnd] | ForEach-Object { "$($_)".Trim() }) -join "`n")
            foreach ($pattern in (Get-LinePatterns -Line $trimmedLine -Lookahead $lookahead)) {
                $findings.Add([pscustomobject]@{
                    Path = $relativePath
                    Pattern = $pattern
                    Line = $index + 1
                    LineText = $trimmedLine
                    LineTextSha256 = Get-LineTextSha256 -LineText $trimmedLine
                })
            }
        }
    }

    return @($findings | Sort-Object Path, Line, Pattern)
}

function Get-PropertyValue {
    param(
        [Parameter(Mandatory)]
        [object] $Object,

        [Parameter(Mandatory)]
        [string] $Name
    )

    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) {
        return $null
    }

    return ,$property.Value
}

function Read-Baseline {
    param(
        [Parameter(Mandatory)]
        [string] $ResolvedBaselinePath,

        [Parameter(Mandatory)]
        [AllowEmptyCollection()]
        [System.Collections.Generic.List[string]] $Errors
    )

    try {
        $baseline = Get-Content -LiteralPath $ResolvedBaselinePath -Raw | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        $Errors.Add("could not parse JSON: $($_.Exception.Message)")
        return @()
    }

    $schema = Get-PropertyValue -Object $baseline -Name 'schema'
    if ($schema -isnot [long] -or $schema -ne 1) {
        $Errors.Add('schema must equal 1 as a JSON number.')
    }

    $exceptionsValue = Get-PropertyValue -Object $baseline -Name 'exceptions'
    if ($null -eq $exceptionsValue -or $exceptionsValue -isnot [System.Array]) {
        $Errors.Add('exceptions must be a JSON array.')
        return @()
    }

    $rows = New-Object System.Collections.Generic.List[object]
    $seen = @{}
    $today = [DateOnly]::FromDateTime([DateTime]::UtcNow)

    for ($index = 0; $index -lt $exceptionsValue.Count; $index++) {
        $exception = $exceptionsValue[$index]
        $missing = @(
            $requiredBaselineFields |
                Where-Object { [string]::IsNullOrWhiteSpace("$(Get-PropertyValue -Object $exception -Name $_)") }
        )
        if ($missing.Count -gt 0) {
            $Errors.Add("exception[$index] missing required field(s): $($missing -join ', ').")
            continue
        }

        $path = "$(Get-PropertyValue -Object $exception -Name 'path')".Trim() -replace '\\', '/'
        $pattern = "$(Get-PropertyValue -Object $exception -Name 'pattern')".Trim()
        $hash = "$(Get-PropertyValue -Object $exception -Name 'lineTextSha256')".Trim()
        $ownerIssue = "$(Get-PropertyValue -Object $exception -Name 'ownerIssue')".Trim()
        $reason = "$(Get-PropertyValue -Object $exception -Name 'reason')".Trim()
        $exitCondition = "$(Get-PropertyValue -Object $exception -Name 'exitCondition')".Trim()
        $expiresOn = "$(Get-PropertyValue -Object $exception -Name 'expiresOn')".Trim()
        $rowValid = $true

        if ([System.IO.Path]::IsPathRooted($path) -or $path -match '(^|/)\.\.(/|$)') {
            $Errors.Add("exception[$index] path must be repo-relative: '$path'.")
            $rowValid = $false
        }
        if ($allowedPatterns -notcontains $pattern) {
            $Errors.Add("exception[$index] pattern '$pattern' is not supported.")
            $rowValid = $false
        }
        if ($hash -cnotmatch '^[0-9a-f]{64}$') {
            $Errors.Add("exception[$index] lineTextSha256 must be a lowercase SHA-256 hash.")
            $rowValid = $false
        }
        if ($ownerIssue -notmatch '^MAN-\d+$') {
            $Errors.Add("exception[$index] ownerIssue must be a MAN issue key.")
            $rowValid = $false
        }

        $expiry = [DateOnly]::MinValue
        if (-not [DateOnly]::TryParseExact($expiresOn, 'yyyy-MM-dd', [Globalization.CultureInfo]::InvariantCulture, [Globalization.DateTimeStyles]::None, [ref] $expiry)) {
            $Errors.Add("exception[$index] expiresOn must use yyyy-MM-dd.")
            $rowValid = $false
        }
        elseif ($expiry -lt $today) {
            $Errors.Add("exception[$index] expired on $expiresOn.")
            $rowValid = $false
        }

        $identity = "$path|$pattern|$hash"
        if ($seen.ContainsKey($identity)) {
            $Errors.Add("exception[$index] is a duplicate baseline row for $path [$pattern] $hash.")
            $rowValid = $false
        }
        else {
            $seen[$identity] = $true
        }

        if ($rowValid) {
            $rows.Add([pscustomobject]@{
                Path = $path
                Pattern = $pattern
                LineTextSha256 = $hash
                OwnerIssue = $ownerIssue
                Reason = $reason
                ExitCondition = $exitCondition
                ExpiresOn = $expiresOn
            })
        }
    }

    return $rows.ToArray()
}

$baselineErrors = New-Object System.Collections.Generic.List[string]

try {
    $resolvedSourceRoot = Resolve-RepoInputPath -InputPath $SourceRoot
    $resolvedBaselinePath = Resolve-RepoInputPath -InputPath $BaselinePath

    $sourceFiles = if ([System.IO.Path]::GetFullPath($resolvedSourceRoot) -ceq [System.IO.Path]::GetFullPath($backendRoot)) {
        Get-SolutionTestSourceFiles
    }
    else {
        Get-DirectSourceFiles -ResolvedSourceRoot $resolvedSourceRoot
    }

    $sourceFiles = @($sourceFiles | Where-Object { -not (Test-GeneratedSource -File $_) } | Sort-Object FullName -Unique)
    $findings = @(Get-SourceFindings -Files $sourceFiles)
    $baselineRows = @(Read-Baseline -ResolvedBaselinePath $resolvedBaselinePath -Errors $baselineErrors)

    $matchedFindingKeys = @{}
    foreach ($row in $baselineRows) {
        $exactMatches = @(
            $findings |
                Where-Object {
                    $_.Path -ceq $row.Path -and
                    $_.Pattern -ceq $row.Pattern -and
                    $_.LineTextSha256 -ceq $row.LineTextSha256
                }
        )
        if ($exactMatches.Count -gt 0) {
            foreach ($match in $exactMatches) {
                $matchedFindingKeys["$($match.Path)|$($match.Pattern)|$($match.LineTextSha256)"] = $true
            }
            continue
        }

        $sameSourcePattern = @($findings | Where-Object { $_.Path -ceq $row.Path -and $_.Pattern -ceq $row.Pattern })
        if ($sameSourcePattern.Count -gt 0) {
            $baselineErrors.Add("$($row.Path) [$($row.Pattern)] hash no longer matches a current source line.")
        }
        else {
            $baselineErrors.Add("$($row.Path) [$($row.Pattern)] does not match a current finding.")
        }
    }

    $unexplained = @(
        $findings |
            Where-Object { -not $matchedFindingKeys.ContainsKey("$($_.Path)|$($_.Pattern)|$($_.LineTextSha256)") }
    )

    if ($baselineErrors.Count -gt 0 -or $unexplained.Count -gt 0) {
        [Console]::Error.WriteLine(
            "Backend test determinism check failed: findings=$($findings.Count), admitted=$($matchedFindingKeys.Count), unexplained=$($unexplained.Count), baselineErrors=$($baselineErrors.Count)."
        )
        foreach ($errorMessage in $baselineErrors) {
            [Console]::Error.WriteLine("Baseline: $errorMessage")
        }
        foreach ($finding in $unexplained) {
            [Console]::Error.WriteLine(
                "$($finding.Path):$($finding.Line) [$($finding.Pattern)] unexplained source finding; lineTextSha256=$($finding.LineTextSha256); line=$($finding.LineText)"
            )
        }
        exit 1
    }

    Write-Host "Backend test determinism check passed: files=$($sourceFiles.Count), findings=$($findings.Count), admitted=$($matchedFindingKeys.Count)."
    exit 0
}
catch {
    [Console]::Error.WriteLine("Backend test determinism check could not run: $($_.Exception.Message)")
    exit 1
}
