# Script-Governance:
#   Category: check
#   SideEffects:
#     - Reads C# test sources belonging to projects in backend/Nerv.IIP.sln
#     - Reads and validates the backend test-determinism baseline
#   Writes:
#     - None
#   Cleanup:
#     - None
#   Requires:
#     - PowerShell 7
#     - .NET SDK 10

[CmdletBinding()]
param(
    [string] $SourceRoot = (Join-Path $PSScriptRoot '../backend'),

    [string] $BaselinePath = (Join-Path $PSScriptRoot '../backend/test-determinism-baseline.json'),

    # Files where a process-global mutation IS the behaviour under test, so the finding can never be
    # removed and dating it would be theatre. This list is deliberately hard-coded rather than read
    # from the baseline: a `permanent` row must be countersigned by the checker, otherwise the
    # classification degrades into a self-served exemption. The parameter exists so the checker's own
    # fixture harness can exercise both sides of the rule; CI invokes the script with no arguments.
    [string[]] $PermanentPathAllowlist = @(
        'backend/tests/Nerv.IIP.Testing.Tests/GlobalTestStateScopeTests.cs'
    )
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

. (Join-Path $PSScriptRoot 'lib/ScriptAutomation.ps1')

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$backendRoot = (Resolve-Path (Join-Path $repoRoot 'backend')).Path
$solutionPath = Join-Path $backendRoot 'Nerv.IIP.sln'
$allowedPatterns = @('Task.Delay', 'Thread.Sleep', 'ShortLease', 'UnreachableAddress', 'StaticSetter')

# Two classifications, deliberately disjoint metadata:
#   expiring-debt — an admitted debt. Carries an owner who outlives the registering change, an exit
#                   condition, and a date after which the checker fails. This is the default and the
#                   only classification that may grow.
#   permanent     — the mutation is the behaviour under test (the isolation mechanism's own tests).
#                   There is nothing to expire towards, so a date would be a lie; instead it carries a
#                   rationale and is only legal on an allow-listed path (see $PermanentPathAllowlist).
$expiringClassification = 'expiring-debt'
$permanentClassification = 'permanent'
$allowedClassifications = @($expiringClassification, $permanentClassification)
$commonBaselineFields = @('path', 'pattern', 'lineTextSha256', 'occurrenceCount', 'classification', 'reason')
$commonStringBaselineFields = @('path', 'pattern', 'lineTextSha256', 'classification', 'reason')
$expiringOnlyFields = @('ownerIssue', 'exitCondition', 'expiresOn')
$permanentOnlyFields = @('rationale')

function Resolve-RepoInputPath {
    param(
        [Parameter(Mandatory)]
        [string] $InputPath
    )

    $candidate = if ([System.IO.Path]::IsPathRooted($InputPath)) {
        $InputPath
    }
    else {
        Join-Path $repoRoot $InputPath
    }

    return (Resolve-Path -LiteralPath $candidate -ErrorAction Stop).Path
}

function Get-RepoRelativePath {
    param(
        [Parameter(Mandatory)]
        [string] $Path
    )

    return ([System.IO.Path]::GetRelativePath($repoRoot, $Path) -replace '\\', '/')
}

function Get-LineTextSha256 {
    param(
        [Parameter(Mandatory)]
        [string] $LineText
    )

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($LineText.Trim())
    $hash = [System.Security.Cryptography.SHA256]::HashData($bytes)
    return [System.Convert]::ToHexString($hash).ToLowerInvariant()
}

function Test-GeneratedSource {
    param(
        [Parameter(Mandatory)]
        [System.IO.FileInfo] $File
    )

    $relativePath = Get-RepoRelativePath -Path $File.FullName
    if ($relativePath -match '(?i)(^|/)(obj|bin|migrations)(/|$)') {
        return $true
    }

    if ($File.Name -match '(?i)(\.g|\.generated|\.designer|\.AssemblyInfo|\.GlobalUsings)\.cs$') {
        return $true
    }

    $head = @(Get-Content -LiteralPath $File.FullName -TotalCount 5)
    return ($head -join "`n") -match '(?i)<auto-generated'
}

function Get-DirectSourceFiles {
    param(
        [Parameter(Mandatory)]
        [string] $ResolvedSourceRoot
    )

    if (Test-Path -LiteralPath $ResolvedSourceRoot -PathType Leaf) {
        if ([System.IO.Path]::GetExtension($ResolvedSourceRoot) -cne '.cs') {
            return @()
        }

        return @((Get-Item -LiteralPath $ResolvedSourceRoot))
    }

    return @(Get-ChildItem -LiteralPath $ResolvedSourceRoot -Recurse -File -Filter '*.cs')
}

function Test-IsTestProject {
    param(
        [Parameter(Mandatory)]
        [string] $ProjectPath
    )

    if ([System.IO.Path]::GetFileNameWithoutExtension($ProjectPath) -match '(?i)Tests$') {
        return $true
    }

    $projectContent = Get-Content -LiteralPath $ProjectPath -Raw
    return $projectContent -match '(?is)<IsTestProject>\s*true\s*</IsTestProject>'
}

function Get-SolutionTestSourceFiles {
    $solutionList = Invoke-DotNetOutput `
        -Arguments @('sln', $solutionPath, 'list') `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 60 `
        -Name 'backend-test-determinism-solution-list'

    $projectPaths = @(
        $solutionList.Stdout -split "`r?`n" |
            ForEach-Object { $_.Trim() } |
            Where-Object { $_ -match '(?i)\.csproj$' } |
            ForEach-Object { Join-Path $backendRoot ($_ -replace '\\', [System.IO.Path]::DirectorySeparatorChar) } |
            Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
            Where-Object { Test-IsTestProject -ProjectPath $_ } |
            Sort-Object -Unique
    )

    if ($projectPaths.Count -eq 0) {
        throw "No C# test projects were returned for solution '$solutionPath'."
    }

    $files = foreach ($projectPath in $projectPaths) {
        $projectDirectory = Split-Path -Parent $projectPath
        Get-ChildItem -LiteralPath $projectDirectory -Recurse -File -Filter '*.cs'
    }

    return @($files | Sort-Object FullName -Unique)
}

function Get-CSharpSanitizedText {
    param(
        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string] $Text,

        [switch] $PreserveStringContent
    )

    $characters = $Text.ToCharArray()
    $length = $characters.Length
    $index = 0

    while ($index -lt $length) {
        $character = $characters[$index]
        $next = if ($index + 1 -lt $length) { $characters[$index + 1] } else { [char] 0 }

        if ($character -eq '/' -and $next -eq '/') {
            while ($index -lt $length -and $characters[$index] -ne "`r" -and $characters[$index] -ne "`n") {
                $characters[$index] = ' '
                $index++
            }
            continue
        }

        if ($character -eq '/' -and $next -eq '*') {
            $characters[$index] = ' '
            $characters[$index + 1] = ' '
            $index += 2
            while ($index -lt $length) {
                if ($index + 1 -lt $length -and $characters[$index] -eq '*' -and $characters[$index + 1] -eq '/') {
                    $characters[$index] = ' '
                    $characters[$index + 1] = ' '
                    $index += 2
                    break
                }
                if ($characters[$index] -ne "`r" -and $characters[$index] -ne "`n") {
                    $characters[$index] = ' '
                }
                $index++
            }
            continue
        }

        if ($character -eq "'") {
            $characters[$index] = ' '
            $index++
            while ($index -lt $length) {
                $current = $characters[$index]
                if ($current -ne "`r" -and $current -ne "`n") {
                    $characters[$index] = ' '
                }
                if ($current -eq '\' -and $index + 1 -lt $length) {
                    $index++
                    if ($characters[$index] -ne "`r" -and $characters[$index] -ne "`n") {
                        $characters[$index] = ' '
                    }
                }
                elseif ($current -eq "'") {
                    $index++
                    break
                }
                $index++
            }
            continue
        }

        if ($character -eq '"') {
            $quoteRunLength = 1
            while ($index + $quoteRunLength -lt $length -and $Text[$index + $quoteRunLength] -eq '"') {
                $quoteRunLength++
            }
            $isRawString = $quoteRunLength -ge 3

            if ($isRawString) {
                $quoteCount = $quoteRunLength
                $rawClosingIndex = -1
                $rawSearchIndex = $index + $quoteCount
                while ($rawSearchIndex -lt $length) {
                    if ($Text[$rawSearchIndex] -ne '"') {
                        $rawSearchIndex++
                        continue
                    }

                    $closingQuoteRun = 1
                    while ($rawSearchIndex + $closingQuoteRun -lt $length -and
                        $Text[$rawSearchIndex + $closingQuoteRun] -eq '"') {
                        $closingQuoteRun++
                    }
                    if ($closingQuoteRun -ge $quoteCount) {
                        $rawClosingIndex = $rawSearchIndex
                        break
                    }
                    $rawSearchIndex += $closingQuoteRun
                }

                if ($rawClosingIndex -lt 0) {
                    $rawClosingIndex = $length
                }

                $rawDollarCount = 0
                $dollarIndex = $index - 1
                while ($dollarIndex -ge 0 -and $Text[$dollarIndex] -eq '$') {
                    $rawDollarCount++
                    $dollarIndex--
                }

                if (-not $PreserveStringContent) {
                    for ($offset = 1; $offset -le $rawDollarCount; $offset++) {
                        $characters[$index - $offset] = ' '
                    }
                    for ($offset = 0; $offset -lt $quoteCount; $offset++) {
                        $characters[$index + $offset] = ' '
                    }
                }

                $rawContentIndex = $index + $quoteCount
                while ($rawContentIndex -lt $rawClosingIndex) {
                    if ($rawDollarCount -gt 0 -and $Text[$rawContentIndex] -eq '{') {
                        $openingBraceRun = 1
                        while ($rawContentIndex + $openingBraceRun -lt $rawClosingIndex -and
                            $Text[$rawContentIndex + $openingBraceRun] -eq '{') {
                            $openingBraceRun++
                        }

                        if ($openingBraceRun -ge $rawDollarCount -and $openingBraceRun -lt 2 * $rawDollarCount) {
                            $expressionStart = $rawContentIndex + $openingBraceRun
                            $expressionTail = $Text.Substring($expressionStart, $rawClosingIndex - $expressionStart)
                            $sanitizedExpressionTail = if ($PreserveStringContent) {
                                Get-CSharpSanitizedText -Text $expressionTail -PreserveStringContent
                            }
                            else {
                                Get-CSharpSanitizedText -Text $expressionTail
                            }

                            $expressionCloseOffset = -1
                            $closingBraceRun = 0
                            $nestedBraceDepth = 0
                            $expressionCursor = 0
                            while ($expressionCursor -lt $sanitizedExpressionTail.Length) {
                                if ($sanitizedExpressionTail[$expressionCursor] -eq '{') {
                                    $nestedBraceDepth++
                                    $expressionCursor++
                                    continue
                                }
                                if ($sanitizedExpressionTail[$expressionCursor] -ne '}') {
                                    $expressionCursor++
                                    continue
                                }

                                $candidateClosingRun = 1
                                while ($expressionCursor + $candidateClosingRun -lt $sanitizedExpressionTail.Length -and
                                    $sanitizedExpressionTail[$expressionCursor + $candidateClosingRun] -eq '}') {
                                    $candidateClosingRun++
                                }
                                $nestedClosingBraces = [Math]::Min($nestedBraceDepth, $candidateClosingRun)
                                $nestedBraceDepth -= $nestedClosingBraces
                                $remainingClosingBraces = $candidateClosingRun - $nestedClosingBraces
                                if ($nestedBraceDepth -eq 0 -and
                                    $remainingClosingBraces -ge $rawDollarCount -and
                                    $remainingClosingBraces -lt 2 * $rawDollarCount) {
                                    $expressionCloseOffset = $expressionCursor + $nestedClosingBraces
                                    $closingBraceRun = $remainingClosingBraces
                                    break
                                }
                                $expressionCursor += $candidateClosingRun
                            }

                            if ($expressionCloseOffset -ge 0) {
                                if (-not $PreserveStringContent) {
                                    for ($offset = 0; $offset -lt $openingBraceRun; $offset++) {
                                        $characters[$rawContentIndex + $offset] = ' '
                                    }
                                }

                                $expressionLength = $expressionCloseOffset
                                $expressionText = $Text.Substring($expressionStart, $expressionLength)
                                $sanitizedExpression = if ($PreserveStringContent) {
                                    Get-CSharpSanitizedText -Text $expressionText -PreserveStringContent
                                }
                                else {
                                    Get-CSharpSanitizedText -Text $expressionText
                                }
                                for ($offset = 0; $offset -lt $expressionLength; $offset++) {
                                    $characters[$expressionStart + $offset] = $sanitizedExpression[$offset]
                                }

                                $expressionClosingIndex = $expressionStart + $expressionCloseOffset
                                if (-not $PreserveStringContent) {
                                    for ($offset = 0; $offset -lt $closingBraceRun; $offset++) {
                                        $characters[$expressionClosingIndex + $offset] = ' '
                                    }
                                }
                                $rawContentIndex = $expressionClosingIndex + $closingBraceRun
                                continue
                            }
                        }
                    }

                    if (-not $PreserveStringContent -and
                        $Text[$rawContentIndex] -ne "`r" -and $Text[$rawContentIndex] -ne "`n") {
                        $characters[$rawContentIndex] = ' '
                    }
                    $rawContentIndex++
                }

                if (-not $PreserveStringContent -and $rawClosingIndex -lt $length) {
                    for ($offset = 0; $offset -lt $quoteCount; $offset++) {
                        $characters[$rawClosingIndex + $offset] = ' '
                    }
                }
                $index = [Math]::Min($rawClosingIndex + $quoteCount, $length)
                continue
            }

            $quoteCount = 1
            $isVerbatimString = ($index -gt 0 -and $characters[$index - 1] -eq '@') -or
                ($index -gt 1 -and $characters[$index - 1] -eq '$' -and $characters[$index - 2] -eq '@')
            $prefixIndex = $index - 1
            if ($prefixIndex -ge 0 -and $characters[$prefixIndex] -eq '@') {
                $prefixIndex--
            }
            $isInterpolatedString = $prefixIndex -ge 0 -and $characters[$prefixIndex] -eq '$'

            for ($offset = 0; $offset -lt $quoteCount; $offset++) {
                if (-not $PreserveStringContent) {
                    $characters[$index + $offset] = ' '
                }
            }
            $index += $quoteCount

            while ($index -lt $length) {
                $current = $characters[$index]
                if ($isInterpolatedString -and $current -eq '{' -and
                    $index + 1 -lt $length -and $characters[$index + 1] -eq '{') {
                    if (-not $PreserveStringContent) {
                        $characters[$index] = ' '
                        $characters[$index + 1] = ' '
                    }
                    $index += 2
                    continue
                }
                elseif ($isInterpolatedString -and $current -eq '{') {
                    $expressionStart = $index + 1
                    $expressionCloseOffset = -1
                    $candidateSearchOffset = $expressionStart
                    while ($candidateSearchOffset -lt $length) {
                        $candidateClosingIndex = $Text.IndexOf('}', $candidateSearchOffset)
                        if ($candidateClosingIndex -lt 0) {
                            break
                        }

                        $candidateLength = $candidateClosingIndex - $expressionStart + 1
                        $candidateText = $Text.Substring($expressionStart, $candidateLength)
                        $sanitizedCandidate = if ($PreserveStringContent) {
                            Get-CSharpSanitizedText -Text $candidateText -PreserveStringContent
                        }
                        else {
                            Get-CSharpSanitizedText -Text $candidateText
                        }

                        $nestedBraceDepth = 0
                        for ($expressionCursor = 0; $expressionCursor -lt $sanitizedCandidate.Length; $expressionCursor++) {
                            if ($sanitizedCandidate[$expressionCursor] -eq '{') {
                                $nestedBraceDepth++
                                continue
                            }
                            if ($sanitizedCandidate[$expressionCursor] -ne '}') {
                                continue
                            }
                            if ($nestedBraceDepth -gt 0) {
                                $nestedBraceDepth--
                                continue
                            }

                            $expressionCloseOffset = $expressionCursor
                            break
                        }
                        if ($expressionCloseOffset -ge 0) {
                            break
                        }
                        $candidateSearchOffset = $candidateClosingIndex + 1
                    }

                    if ($expressionCloseOffset -ge 0) {
                        if (-not $PreserveStringContent) {
                            $characters[$index] = ' '
                        }

                        $expressionText = $Text.Substring($expressionStart, $expressionCloseOffset)
                        $sanitizedExpression = if ($PreserveStringContent) {
                            Get-CSharpSanitizedText -Text $expressionText -PreserveStringContent
                        }
                        else {
                            Get-CSharpSanitizedText -Text $expressionText
                        }
                        for ($offset = 0; $offset -lt $expressionCloseOffset; $offset++) {
                            $characters[$expressionStart + $offset] = $sanitizedExpression[$offset]
                        }

                        $expressionClosingIndex = $expressionStart + $expressionCloseOffset
                        if (-not $PreserveStringContent) {
                            $characters[$expressionClosingIndex] = ' '
                        }
                        $index = $expressionClosingIndex + 1
                        continue
                    }
                }
                elseif ($isVerbatimString -and $current -eq '"' -and $index + 1 -lt $length -and $characters[$index + 1] -eq '"') {
                    if (-not $PreserveStringContent) {
                        $characters[$index] = ' '
                        $characters[$index + 1] = ' '
                    }
                    $index += 2
                    continue
                }
                elseif ($current -eq '"') {
                    if (-not $PreserveStringContent) {
                        $characters[$index] = ' '
                    }
                    $index++
                    break
                }
                elseif (-not $isVerbatimString -and $current -eq '\' -and $index + 1 -lt $length) {
                    if (-not $PreserveStringContent) {
                        $characters[$index] = ' '
                    }
                    $index++
                    if (-not $PreserveStringContent -and $characters[$index] -ne "`r" -and $characters[$index] -ne "`n") {
                        $characters[$index] = ' '
                    }
                    $index++
                    continue
                }

                if (-not $PreserveStringContent -and $current -ne "`r" -and $current -ne "`n") {
                    $characters[$index] = ' '
                }
                $index++
            }
            continue
        }

        $index++
    }

    return -join $characters
}

function Get-LineFindingAtOffset {
    param(
        [Parameter(Mandatory)]
        [string] $Path,

        [Parameter(Mandatory)]
        [string] $Source,

        [Parameter(Mandatory)]
        [int[]] $LineStarts,

        [Parameter(Mandatory)]
        [int] $Offset,

        [Parameter(Mandatory)]
        [string] $Pattern
    )

    $lineIndex = [Array]::BinarySearch($LineStarts, $Offset)
    if ($lineIndex -lt 0) {
        $lineIndex = -$lineIndex - 2
    }
    $lineStart = $LineStarts[$lineIndex]
    $lineEnd = $lineStart
    while ($lineEnd -lt $Source.Length -and $Source[$lineEnd] -ne "`r" -and $Source[$lineEnd] -ne "`n") {
        $lineEnd++
    }
    $lineText = $Source.Substring($lineStart, $lineEnd - $lineStart).Trim()

    return [pscustomobject]@{
        Path = $Path
        Pattern = $Pattern
        Line = $lineIndex + 1
        LineText = $lineText
        LineTextSha256 = Get-LineTextSha256 -LineText $lineText
    }
}

function Get-SourceFindings {
    param(
        [Parameter(Mandatory)]
        [System.IO.FileInfo[]] $Files
    )

    $findings = New-Object System.Collections.Generic.List[object]

    foreach ($file in $Files) {
        if (Test-GeneratedSource -File $file) {
            continue
        }

        $relativePath = Get-RepoRelativePath -Path $file.FullName
        $source = [System.IO.File]::ReadAllText($file.FullName)
        $sanitizedCode = Get-CSharpSanitizedText -Text $source
        $commentSanitizedSource = Get-CSharpSanitizedText -Text $source -PreserveStringContent
        $lineStarts = New-Object System.Collections.Generic.List[int]
        $lineStarts.Add(0)
        for ($index = 0; $index -lt $source.Length; $index++) {
            if ($source[$index] -eq "`n") {
                $lineStarts.Add($index + 1)
            }
        }

        $patternExpressions = @(
            [pscustomobject]@{ Pattern = 'Task.Delay'; Expression = '(?<![\w.])(?:(?:global\s*::\s*)?System\s*\.\s*Threading\s*\.\s*Tasks\s*\.\s*)?Task\s*\.\s*Delay\s*\(' },
            [pscustomobject]@{ Pattern = 'Thread.Sleep'; Expression = '(?<![\w.])(?:(?:global\s*::\s*)?System\s*\.\s*Threading\s*\.\s*)?Thread\s*\.\s*Sleep\s*\(' },
            [pscustomobject]@{ Pattern = 'StaticSetter'; Expression = '(?<![\w.])(?:(?:global\s*::\s*)?System\s*\.\s*)?Environment\s*\.\s*SetEnvironmentVariable\s*\(' },
            [pscustomobject]@{ Pattern = 'StaticSetter'; Expression = '\bValidatorOptions\s*\.\s*Global\b(?:\s*\.\s*[A-Za-z_]\w*)+\s*(?<![=!<>])=(?!=|>)' },
            [pscustomobject]@{ Pattern = 'StaticSetter'; Expression = '\bCultureInfo\s*\.\s*(?:CurrentCulture|CurrentUICulture|DefaultThreadCurrentCulture|DefaultThreadCurrentUICulture)\b\s*(?<![=!<>])=(?!=|>)' },
            [pscustomobject]@{ Pattern = 'StaticSetter'; Expression = '\bThread\s*\.\s*CurrentThread\s*\.\s*(?:CurrentCulture|CurrentUICulture)\b\s*(?<![=!<>])=(?!=|>)' }
        )
        foreach ($patternExpression in $patternExpressions) {
            foreach ($match in [regex]::Matches($sanitizedCode, $patternExpression.Expression)) {
                $findings.Add((Get-LineFindingAtOffset -Path $relativePath -Source $source -LineStarts $lineStarts.ToArray() -Offset $match.Index -Pattern $patternExpression.Pattern))
            }
        }

        $numberExpression = '\d(?:_?\d)*(?:\.\d(?:_?\d)*)?'
        $shortLeaseExpressions = @(
            [pscustomobject]@{ Expression = "(?i)\b\w*(?:Lease|Renew)\w*\b\s*(?:=|:|\()\s*TimeSpan\s*\.\s*FromMilliseconds\s*\(\s*(?<value>$numberExpression)\s*\)"; Limit = [decimal] 1000 },
            [pscustomobject]@{ Expression = "(?i)\b\w*(?:Lease|Renew)\w*\b\s*(?:=|:|\()\s*TimeSpan\s*\.\s*FromSeconds\s*\(\s*(?<value>$numberExpression)\s*\)"; Limit = [decimal] 1 },
            [pscustomobject]@{ Expression = "(?i)\b(?:\w*Lease\w*|\w*Renew\w*)(?:Milliseconds|Ms)\s*=\s*(?<value>$numberExpression)"; Limit = [decimal] 1000 },
            [pscustomobject]@{ Expression = "(?i)\b(?:\w*Lease\w*|\w*Renew\w*)Seconds\s*=\s*(?<value>$numberExpression)"; Limit = [decimal] 1 }
        )
        foreach ($shortLeaseExpression in $shortLeaseExpressions) {
            foreach ($match in [regex]::Matches($sanitizedCode, $shortLeaseExpression.Expression)) {
                $numericValue = [decimal]::Parse(
                    $match.Groups['value'].Value.Replace('_', ''),
                    [Globalization.CultureInfo]::InvariantCulture
                )
                if ($numericValue -lt $shortLeaseExpression.Limit) {
                    $findings.Add((Get-LineFindingAtOffset -Path $relativePath -Source $source -LineStarts $lineStarts.ToArray() -Offset $match.Index -Pattern 'ShortLease'))
                }
            }
        }

        $unreachableExpressions = @(
            '(?i)127\.0\.0\.1\s*:\s*1(?!\d)',
            '(?i)\bPort\s*=\s*1(?=\s*[,;"'']|\s*$)'
        )
        foreach ($expression in $unreachableExpressions) {
            foreach ($match in [regex]::Matches($commentSanitizedSource, $expression)) {
                $findings.Add((Get-LineFindingAtOffset -Path $relativePath -Source $source -LineStarts $lineStarts.ToArray() -Offset $match.Index -Pattern 'UnreachableAddress'))
            }
        }
    }

    return @($findings | Sort-Object Path, Line, Pattern)
}

function Get-PropertyValue {
    param(
        [Parameter(Mandatory)]
        [object] $Object,

        [Parameter(Mandatory)]
        [string] $Name
    )

    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) {
        return $null
    }

    return ,$property.Value
}

function Read-Baseline {
    param(
        [Parameter(Mandatory)]
        [string] $ResolvedBaselinePath,

        [Parameter(Mandatory)]
        [AllowEmptyCollection()]
        [System.Collections.Generic.List[string]] $Errors
    )

    try {
        $baseline = Get-Content -LiteralPath $ResolvedBaselinePath -Raw | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        $Errors.Add("could not parse JSON: $($_.Exception.Message)")
        return @()
    }

    $schema = Get-PropertyValue -Object $baseline -Name 'schema'
    if ($schema -isnot [long] -or $schema -ne 2) {
        $Errors.Add('schema must equal 2 as a JSON number.')
    }

    $exceptionsValue = Get-PropertyValue -Object $baseline -Name 'exceptions'
    if ($null -eq $exceptionsValue -or $exceptionsValue -isnot [System.Array]) {
        $Errors.Add('exceptions must be a JSON array.')
        return @()
    }

    $rows = New-Object System.Collections.Generic.List[object]
    $seen = @{}
    $today = [DateOnly]::FromDateTime([DateTime]::UtcNow)
    $normalizedPermanentPaths = @(
        $PermanentPathAllowlist |
            ForEach-Object { ($_ -replace '\\', '/').Trim() }
    )

    for ($index = 0; $index -lt $exceptionsValue.Count; $index++) {
        $exception = $exceptionsValue[$index]

        # The classification decides which metadata the row owes, so it is resolved before the
        # required-field check rather than alongside it.
        $classification = Get-PropertyValue -Object $exception -Name 'classification'
        if ($classification -isnot [string] -or $allowedClassifications -cnotcontains $classification) {
            $Errors.Add("exception[$index] classification must be one of: $($allowedClassifications -join ', ').")
            continue
        }

        $isPermanent = $classification -ceq $permanentClassification
        $classificationFields = if ($isPermanent) { $permanentOnlyFields } else { $expiringOnlyFields }
        $forbiddenFields = if ($isPermanent) { $expiringOnlyFields } else { $permanentOnlyFields }
        $requiredBaselineFields = @($commonBaselineFields + $classificationFields)
        $requiredStringBaselineFields = @($commonStringBaselineFields + $classificationFields)

        $missing = @(
            $requiredBaselineFields |
                Where-Object { $null -eq $exception.PSObject.Properties[$_] }
        )
        if ($missing.Count -gt 0) {
            $Errors.Add("exception[$index] classification '$classification' is missing required field(s): $($missing -join ', ').")
            continue
        }

        # A permanent row carrying an expiry (or a debt row carrying a rationale) reads as if it had
        # been reviewed under the other set of rules. Reject the mixture rather than pick a winner.
        $forbidden = @(
            $forbiddenFields |
                Where-Object { $null -ne $exception.PSObject.Properties[$_] }
        )
        if ($forbidden.Count -gt 0) {
            $Errors.Add("exception[$index] classification '$classification' must not carry field(s): $($forbidden -join ', ').")
            continue
        }

        $rowValid = $true
        $stringValues = @{}
        foreach ($field in $requiredStringBaselineFields) {
            $value = Get-PropertyValue -Object $exception -Name $field
            if ($value -isnot [string] -or [string]::IsNullOrWhiteSpace($value)) {
                $Errors.Add("exception[$index] $field must be a non-empty string.")
                $rowValid = $false
                continue
            }
            $stringValues[$field] = $value.Trim()
        }

        $occurrenceCount = Get-PropertyValue -Object $exception -Name 'occurrenceCount'
        if ($occurrenceCount -isnot [long] -or $occurrenceCount -le 0) {
            $Errors.Add("exception[$index] occurrenceCount must be a positive integer.")
            $rowValid = $false
        }

        if (-not $rowValid) {
            continue
        }

        $path = $stringValues['path'] -replace '\\', '/'
        $pattern = $stringValues['pattern']
        $hash = $stringValues['lineTextSha256']
        $ownerIssue = $stringValues['ownerIssue']
        $reason = $stringValues['reason']
        $exitCondition = $stringValues['exitCondition']
        $expiresOn = $stringValues['expiresOn']
        $rationale = $stringValues['rationale']

        if ([System.IO.Path]::IsPathRooted($path) -or $path -match '(^|/)\.\.(/|$)') {
            $Errors.Add("exception[$index] path must be repo-relative: '$path'.")
            $rowValid = $false
        }
        if ($allowedPatterns -notcontains $pattern) {
            $Errors.Add("exception[$index] pattern '$pattern' is not supported.")
            $rowValid = $false
        }
        if ($hash -cnotmatch '^[0-9a-f]{64}$') {
            $Errors.Add("exception[$index] lineTextSha256 must be a lowercase SHA-256 hash.")
            $rowValid = $false
        }

        if ($isPermanent) {
            # Only the checker decides which files may hold a permanent row; the baseline cannot
            # nominate itself into the allowlist.
            if ($normalizedPermanentPaths -cnotcontains $path) {
                $Errors.Add("exception[$index] permanent classification is not allowed for path '$path'.")
                $rowValid = $false
            }
        }
        else {
            # A Linear key (MAN-123) or a GitHub issue number (#123) both name a tracked owner. The
            # owner must outlive the change that registered the debt, so a row may not point at its
            # own issue.
            if ($ownerIssue -notmatch '^(MAN-\d+|#\d+)$') {
                $Errors.Add("exception[$index] ownerIssue must be a MAN issue key or a #<number> GitHub issue.")
                $rowValid = $false
            }

            $expiry = [DateOnly]::MinValue
            if (-not [DateOnly]::TryParseExact($expiresOn, 'yyyy-MM-dd', [Globalization.CultureInfo]::InvariantCulture, [Globalization.DateTimeStyles]::None, [ref] $expiry)) {
                $Errors.Add("exception[$index] expiresOn must use yyyy-MM-dd.")
                $rowValid = $false
            }
            elseif ($expiry -lt $today) {
                $Errors.Add("exception[$index] expired on $expiresOn.")
                $rowValid = $false
            }
        }

        $identity = "$path|$pattern|$hash"
        if ($seen.ContainsKey($identity)) {
            $Errors.Add("exception[$index] is a duplicate baseline row for $path [$pattern] $hash.")
            $rowValid = $false
        }
        else {
            $seen[$identity] = $true
        }

        if ($rowValid) {
            $rows.Add([pscustomobject]@{
                Path = $path
                Pattern = $pattern
                LineTextSha256 = $hash
                OccurrenceCount = $occurrenceCount
                Classification = $classification
                OwnerIssue = $ownerIssue
                Reason = $reason
                ExitCondition = $exitCondition
                ExpiresOn = $expiresOn
                Rationale = $rationale
            })
        }
    }

    return $rows.ToArray()
}

$baselineErrors = New-Object System.Collections.Generic.List[string]

try {
    $resolvedSourceRoot = Resolve-RepoInputPath -InputPath $SourceRoot
    $resolvedBaselinePath = Resolve-RepoInputPath -InputPath $BaselinePath

    $sourceFiles = if ([System.IO.Path]::GetFullPath($resolvedSourceRoot) -ceq [System.IO.Path]::GetFullPath($backendRoot)) {
        Get-SolutionTestSourceFiles
    }
    else {
        Get-DirectSourceFiles -ResolvedSourceRoot $resolvedSourceRoot
    }

    $sourceFiles = @($sourceFiles | Where-Object { -not (Test-GeneratedSource -File $_) } | Sort-Object FullName -Unique)
    $findings = @(Get-SourceFindings -Files $sourceFiles)
    $baselineRows = @(Read-Baseline -ResolvedBaselinePath $resolvedBaselinePath -Errors $baselineErrors)

    $matchedFindingKeys = @{}
    foreach ($row in $baselineRows) {
        $exactMatches = @(
            $findings |
                Where-Object {
                    $_.Path -ceq $row.Path -and
                    $_.Pattern -ceq $row.Pattern -and
                    $_.LineTextSha256 -ceq $row.LineTextSha256
                }
        )
        if ($exactMatches.Count -eq $row.OccurrenceCount) {
            foreach ($match in $exactMatches) {
                $matchedFindingKeys["$($match.Path)|$($match.Pattern)|$($match.LineTextSha256)"] = $true
            }
            continue
        }

        if ($exactMatches.Count -gt 0) {
            $baselineErrors.Add(
                "$($row.Path) [$($row.Pattern)] occurrence count changed: expected $($row.OccurrenceCount), actual $($exactMatches.Count)."
            )
            continue
        }

        $sameSourcePattern = @($findings | Where-Object { $_.Path -ceq $row.Path -and $_.Pattern -ceq $row.Pattern })
        if ($sameSourcePattern.Count -gt 0) {
            $baselineErrors.Add("$($row.Path) [$($row.Pattern)] hash no longer matches a current source line.")
        }
        else {
            $baselineErrors.Add("$($row.Path) [$($row.Pattern)] does not match a current finding.")
        }
    }

    $unexplained = @(
        $findings |
            Where-Object { -not $matchedFindingKeys.ContainsKey("$($_.Path)|$($_.Pattern)|$($_.LineTextSha256)") }
    )

    if ($baselineErrors.Count -gt 0 -or $unexplained.Count -gt 0) {
        [Console]::Error.WriteLine(
            "Backend test determinism check failed: findings=$($findings.Count), admitted=$($matchedFindingKeys.Count), unexplained=$($unexplained.Count), baselineErrors=$($baselineErrors.Count)."
        )
        foreach ($errorMessage in $baselineErrors) {
            [Console]::Error.WriteLine("Baseline: $errorMessage")
        }
        foreach ($finding in $unexplained) {
            [Console]::Error.WriteLine(
                "$($finding.Path):$($finding.Line) [$($finding.Pattern)] unexplained source finding; lineTextSha256=$($finding.LineTextSha256); line=$($finding.LineText)"
            )
        }
        exit 1
    }

    $permanentRowCount = @($baselineRows | Where-Object { $_.Classification -ceq $permanentClassification }).Count
    $expiringRowCount = @($baselineRows | Where-Object { $_.Classification -ceq $expiringClassification }).Count
    Write-Host "Backend test determinism check passed: files=$($sourceFiles.Count), findings=$($findings.Count), admitted=$($matchedFindingKeys.Count), expiringDebtRows=$expiringRowCount, permanentRows=$permanentRowCount."
    exit 0
}
catch {
    [Console]::Error.WriteLine("Backend test determinism check could not run: $($_.Exception.Message)")
    exit 1
}
