export {
  changeConsolePasswordMutationOptions,
  getConsolePrincipalQueryOptions,
  loginConsoleUserMutationOptions,
  logoutConsoleSessionMutationOptions,
  refreshConsoleSessionMutationOptions,
} from './generated/@pinia/colada.gen'

export {
  changeConsolePassword,
  getConsolePrincipal,
  loginConsoleUser,
  logoutConsoleSession,
  refreshConsoleSession,
} from './generated/sdk.gen'

import type {
  NetCorePalExtensionsDtoResponseDataOfConsoleAuthResponse,
  NetCorePalExtensionsDtoResponseDataOfConsolePrincipalResponse,
  NervIipPlatformGatewayWebApplicationAuthConsoleAuthResponse,
  NervIipPlatformGatewayWebApplicationAuthConsoleChangePasswordRequest,
  NervIipPlatformGatewayWebApplicationAuthConsoleLoginRequest,
  NervIipPlatformGatewayWebApplicationAuthConsoleLogoutRequest,
  NervIipPlatformGatewayWebApplicationAuthConsolePrincipalResponse,
  NervIipPlatformGatewayWebApplicationAuthConsoleRefreshRequest,
} from './generated/types.gen'

export type ConsoleAuthResponse = NervIipPlatformGatewayWebApplicationAuthConsoleAuthResponse
export type ConsoleChangePasswordRequest =
  NervIipPlatformGatewayWebApplicationAuthConsoleChangePasswordRequest
export type ConsoleLoginRequest = NervIipPlatformGatewayWebApplicationAuthConsoleLoginRequest
export type ConsoleLogoutRequest = NervIipPlatformGatewayWebApplicationAuthConsoleLogoutRequest
export type ConsolePrincipalResponse =
  NervIipPlatformGatewayWebApplicationAuthConsolePrincipalResponse
export type ConsoleRefreshRequest = NervIipPlatformGatewayWebApplicationAuthConsoleRefreshRequest
export type ConsoleAuthEnvelope = NetCorePalExtensionsDtoResponseDataOfConsoleAuthResponse
export type ConsolePrincipalEnvelope = NetCorePalExtensionsDtoResponseDataOfConsolePrincipalResponse
