export {
  acceptBusinessConsoleMesShiftHandoverMutationOptions,
  acceptBusinessConsolePlanningSuggestionMutationOptions,
  assignBusinessConsoleMesDispatchTaskMutationOptions,
  closeBusinessConsoleQualityNcrMutationOptions,
  completeBusinessConsoleMesOperationTaskMutationOptions,
  confirmBusinessConsoleInventoryCountAdjustmentMutationOptions,
  confirmBusinessConsoleMesDowntimeRecoveryMutationOptions,
  confirmBusinessConsoleMesLineSideMaterialReceiptMutationOptions,
  convertBusinessConsoleMesPlanToWorkOrderMutationOptions,
  createBusinessConsoleInventoryCountTaskMutationOptions,
  createBusinessConsoleMesFinishedGoodsReceiptRequestMutationOptions,
  createBusinessConsoleMesMaterialIssueRequestMutationOptions,
  createBusinessConsoleMesRushWorkOrderMutationOptions,
  createBusinessConsoleMesShiftHandoverMutationOptions,
  createBusinessConsoleQualityInspectionRecordMutationOptions,
  createOrUpdateBusinessConsolePlanningDemandMutationOptions,
  createBusinessConsoleSkuMutationOptions,
  getBusinessConsoleEquipmentAvailabilityQueryOptions,
  getBusinessConsoleEquipmentDeviceQueryOptions,
  getBusinessConsoleEquipmentOverviewQueryOptions,
  getBusinessConsoleInventoryAvailabilityQueryOptions,
  getBusinessConsoleMesBarcodeNumberingReadinessQueryOptions,
  getBusinessConsoleMesBatchTraceabilityQueryOptions,
  getBusinessConsoleMesEquipmentReadinessQueryOptions,
  getBusinessConsoleMesFoundationReadinessQueryOptions,
  getBusinessConsoleMesMasterDataReadinessQueryOptions,
  getBusinessConsoleMesMaterialLotTraceabilityQueryOptions,
  getBusinessConsoleMesMaterialReadinessQueryOptions,
  getBusinessConsoleMesOverviewQueryOptions,
  getBusinessConsoleMesProductEngineeringReadinessQueryOptions,
  getBusinessConsoleMesProductionPlanReadinessQueryOptions,
  getBusinessConsoleMesQualityReadinessQueryOptions,
  getBusinessConsoleMesSupplyReadinessQueryOptions,
  getBusinessConsoleMesWipSummaryQueryOptions,
  getBusinessConsoleMesWorkOrderDetailQueryOptions,
  getBusinessConsoleMesWorkOrderTraceabilityQueryOptions,
  getBusinessConsolePlanningMrpPeggingQueryOptions,
  listBusinessConsoleEngineeringBomsQueryOptions,
  listBusinessConsoleEngineeringProductionVersionsQueryOptions,
  listBusinessConsoleEngineeringRoutingsQueryOptions,
  listBusinessConsoleEquipmentAlarmsQueryOptions,
  listBusinessConsoleErpPurchaseOrdersQueryOptions,
  listBusinessConsoleMasterDataResourcesQueryOptions,
  listBusinessConsoleMesCapacityImpactsQueryOptions,
  listBusinessConsoleMesDispatchTasksQueryOptions,
  listBusinessConsoleMesDowntimeEventsQueryOptions,
  listBusinessConsoleMesFinishedGoodsReceiptRequestsQueryOptions,
  listBusinessConsoleMesMaterialIssueRequestsQueryOptions,
  listBusinessConsoleMesOperationTasksQueryOptions,
  listBusinessConsoleMesProductionPlansQueryOptions,
  listBusinessConsoleMesProductionReportsQueryOptions,
  listBusinessConsoleMesRelatedQualityItemsQueryOptions,
  listBusinessConsoleMesShiftHandoversQueryOptions,
  listBusinessConsoleMesWorkOrdersQueryOptions,
  listBusinessConsolePlanningDemandsQueryOptions,
  listBusinessConsolePlanningMrpRunsQueryOptions,
  listBusinessConsolePlanningSuggestionsQueryOptions,
  listBusinessConsoleQualityInspectionPlansQueryOptions,
  listBusinessConsoleQualityNcrsQueryOptions,
  listBusinessConsoleSkusQueryOptions,
  pauseBusinessConsoleMesOperationTaskMutationOptions,
  postBusinessConsoleInventoryMovementMutationOptions,
  recordBusinessConsoleMesDefectMutationOptions,
  recordBusinessConsoleMesDowntimeEventMutationOptions,
  recordBusinessConsoleMesProductionReportMutationOptions,
  releaseBusinessConsoleMesWorkOrderMutationOptions,
  resolveBusinessConsoleEngineeringProductionVersionQueryOptions,
  resumeBusinessConsoleMesOperationTaskMutationOptions,
  runBusinessConsoleMesScheduleMutationOptions,
  runBusinessConsolePlanningMrpMutationOptions,
  startBusinessConsoleMesOperationTaskMutationOptions,
  submitBusinessConsoleQualityNcrDispositionMutationOptions,
} from './generated/business-console/@pinia/colada.gen'

export {
  acceptBusinessConsoleMesShiftHandover,
  acceptBusinessConsolePlanningSuggestion,
  assignBusinessConsoleMesDispatchTask,
  closeBusinessConsoleQualityNcr,
  completeBusinessConsoleMesOperationTask,
  confirmBusinessConsoleInventoryCountAdjustment,
  confirmBusinessConsoleMesDowntimeRecovery,
  confirmBusinessConsoleMesLineSideMaterialReceipt,
  convertBusinessConsoleMesPlanToWorkOrder,
  createBusinessConsoleInventoryCountTask,
  createBusinessConsoleMesFinishedGoodsReceiptRequest,
  createBusinessConsoleMesMaterialIssueRequest,
  createBusinessConsoleMesRushWorkOrder,
  createBusinessConsoleMesShiftHandover,
  createBusinessConsoleQualityInspectionRecord,
  createBusinessConsoleSku,
  createOrUpdateBusinessConsolePlanningDemand,
  getBusinessConsoleEquipmentAvailability,
  getBusinessConsoleEquipmentDevice,
  getBusinessConsoleEquipmentOverview,
  getBusinessConsoleInventoryAvailability,
  getBusinessConsoleMesBarcodeNumberingReadiness,
  getBusinessConsoleMesBatchTraceability,
  getBusinessConsoleMesEquipmentReadiness,
  getBusinessConsoleMesFoundationReadiness,
  getBusinessConsoleMesMasterDataReadiness,
  getBusinessConsoleMesMaterialLotTraceability,
  getBusinessConsoleMesMaterialReadiness,
  getBusinessConsoleMesOverview,
  getBusinessConsoleMesProductEngineeringReadiness,
  getBusinessConsoleMesProductionPlanReadiness,
  getBusinessConsoleMesQualityReadiness,
  getBusinessConsoleMesSupplyReadiness,
  getBusinessConsoleMesWipSummary,
  getBusinessConsoleMesWorkOrderDetail,
  getBusinessConsoleMesWorkOrderTraceability,
  getBusinessConsolePlanningMrpPegging,
  listBusinessConsoleEngineeringBoms,
  listBusinessConsoleEngineeringProductionVersions,
  listBusinessConsoleEngineeringRoutings,
  listBusinessConsoleEquipmentAlarms,
  listBusinessConsoleErpPurchaseOrders,
  listBusinessConsoleMasterDataResources,
  listBusinessConsoleMesCapacityImpacts,
  listBusinessConsoleMesDispatchTasks,
  listBusinessConsoleMesDowntimeEvents,
  listBusinessConsoleMesFinishedGoodsReceiptRequests,
  listBusinessConsoleMesMaterialIssueRequests,
  listBusinessConsoleMesOperationTasks,
  listBusinessConsoleMesProductionPlans,
  listBusinessConsoleMesProductionReports,
  listBusinessConsoleMesRelatedQualityItems,
  listBusinessConsoleMesShiftHandovers,
  listBusinessConsoleMesWorkOrders,
  listBusinessConsolePlanningDemands,
  listBusinessConsolePlanningMrpRuns,
  listBusinessConsolePlanningSuggestions,
  listBusinessConsoleQualityInspectionPlans,
  listBusinessConsoleQualityNcrs,
  listBusinessConsoleSkus,
  pauseBusinessConsoleMesOperationTask,
  postBusinessConsoleInventoryMovement,
  recordBusinessConsoleMesDefect,
  recordBusinessConsoleMesDowntimeEvent,
  recordBusinessConsoleMesProductionReport,
  releaseBusinessConsoleMesWorkOrder,
  resolveBusinessConsoleEngineeringProductionVersion,
  resumeBusinessConsoleMesOperationTask,
  runBusinessConsoleMesSchedule,
  runBusinessConsolePlanningMrp,
  startBusinessConsoleMesOperationTask,
  submitBusinessConsoleQualityNcrDisposition,
} from './generated/business-console/sdk.gen'

import type {
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleAcceptedResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleConfirmStockCountAdjustmentResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateInspectionRecordResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateRushWorkOrderResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateStockCountTaskResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleDemandSourceListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleDemandSourceResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleEngineeringBomListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleEquipmentAlarmListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleEquipmentDeviceDetailResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleEquipmentOverviewResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleErpPurchaseOrderListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleInventoryAvailabilityResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesCapacityImpactListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesCreateReceiptResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesDispatchTaskListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesDowntimeEventListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesFoundationReadinessResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesMaterialIssueRequestListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesMaterialReadinessResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesOperationTaskListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesOverviewResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesProductionPlanListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesProductionReportListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesRelatedQualityItemListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesReceiptRequestListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesScheduleResult,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesShiftHandoverListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesTraceabilityResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWipSummaryResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderDetailResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMrpPeggingListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMrpRunListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsolePlanningSuggestionListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsolePostStockMovementResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleProductionVersionListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleQualityListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRecordProductionReportResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResolveProductionVersionResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceItem,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRoutingListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRunMrpResponse,
  NetCorePalExtensionsDtoResponseDataOfEquipmentRuntimeAvailabilityResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleAcceptedResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleAcceptPlanningSuggestionRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateSkuRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateOrUpdateDemandSourceRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleDemandSourceResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEngineeringBomItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEngineeringBomListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEquipmentAlarmListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEquipmentDeviceDetailResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEquipmentDeviceSummary,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEquipmentOverviewResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleErpPurchaseOrderItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleErpPurchaseOrderLineItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleErpPurchaseOrderListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInspectionCharacteristicResult,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityLineResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleListEngineeringBomsRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleListProductionVersionsRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleListRoutingsRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCapacityImpactListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCapacityImpactRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesAcceptShiftHandoverRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesAssignDispatchTaskRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesConfirmLineSideReceiptRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesConvertPlanToWorkOrderRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateMaterialIssueRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateReceiptRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateReceiptResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateShiftHandoverRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesDispatchTaskListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesDispatchTaskRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesDowntimeEventListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesDowntimeEventRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesFoundationReadinessResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialIssueRequestListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialIssueRequestRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialReadinessResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialReadinessRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskActionRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskActionResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOverviewResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionPlanListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionPlanRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionReportListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionReportRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRecordDefectRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRecordDowntimeEventRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReadinessArea,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReadinessIssue,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRecoverDowntimeEventRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRelatedQualityItemListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRelatedQualityItemRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReceiptRequestListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReceiptRequestRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesScheduleResult,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesShiftHandoverListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesShiftHandoverRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesTraceabilityEdge,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesTraceabilityNode,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesTraceabilityResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWipSummaryResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWipSummaryRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderDetailResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMrpPeggingItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMrpRunItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrCloseRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrDispositionRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePlanningSuggestionItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleProductionVersionItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleProductionVersionListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResolveProductionVersionRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResolveProductionVersionResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRoutingItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRoutingListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunMrpRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunMrpResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunScheduleRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleScheduledOperation,
  NervIipContractsEquipmentRuntimeEquipmentRuntimeAlarmSummary,
  NervIipContractsEquipmentRuntimeEquipmentRuntimeAvailabilityResponse,
  NervIipContractsEquipmentRuntimeEquipmentRuntimeAvailabilityStatus,
  NervIipContractsEquipmentRuntimeEquipmentRuntimeAvailabilityWindowContract,
  NervIipContractsEquipmentRuntimeEquipmentRuntimeCurrentStateResponse,
  NervIipContractsEquipmentRuntimeEquipmentRuntimeSeverity,
  NervIipContractsEquipmentRuntimeEquipmentRuntimeSourceType,
} from './generated/business-console/types.gen'

export type BusinessConsoleAcceptedResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleAcceptedResponse
export type BusinessConsoleConfirmStockCountAdjustmentRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentRequest
export type BusinessConsoleConfirmStockCountAdjustmentResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentResponse
export type BusinessConsoleCreateInspectionRecordRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordRequest
export type BusinessConsoleCreateInspectionRecordResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordResponse
export type BusinessConsoleCreateRushWorkOrderRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderRequest
export type BusinessConsoleCreateRushWorkOrderResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderResponse
export type BusinessConsoleCreateSkuRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateSkuRequest
export type BusinessConsoleCreateOrUpdateDemandSourceRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateOrUpdateDemandSourceRequest
export type BusinessConsoleCreateStockCountTaskRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskRequest
export type BusinessConsoleCreateStockCountTaskResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskResponse
export type BusinessConsoleEngineeringBomItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEngineeringBomItem
export type BusinessConsoleEngineeringBomListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEngineeringBomListResponse
export type BusinessConsoleEquipmentAlarmListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEquipmentAlarmListResponse
export type BusinessConsoleEquipmentDeviceDetailResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEquipmentDeviceDetailResponse
export type BusinessConsoleEquipmentDeviceSummary =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEquipmentDeviceSummary
export type BusinessConsoleEquipmentOverviewResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleEquipmentOverviewResponse
export type BusinessConsoleErpPurchaseOrderItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleErpPurchaseOrderItem
export type BusinessConsoleErpPurchaseOrderLineItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleErpPurchaseOrderLineItem
export type BusinessConsoleErpPurchaseOrderListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleErpPurchaseOrderListResponse
export type BusinessConsoleDemandSourceItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleDemandSourceResponse
export type BusinessConsoleInspectionCharacteristicResult =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInspectionCharacteristicResult
export type BusinessConsoleInventoryAvailabilityLineResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityLineResponse
export type BusinessConsoleInventoryAvailabilityResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityResponse
export type BusinessConsoleListEngineeringBomsRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleListEngineeringBomsRequest
export type BusinessConsoleListProductionVersionsRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleListProductionVersionsRequest
export type BusinessConsoleListRoutingsRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleListRoutingsRequest
export type BusinessConsoleMesCapacityImpactListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCapacityImpactListResponse
export type BusinessConsoleMesCapacityImpactRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCapacityImpactRow
export type BusinessConsoleMesAcceptShiftHandoverRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesAcceptShiftHandoverRequest
export type BusinessConsoleMesAssignDispatchTaskRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesAssignDispatchTaskRequest
export type BusinessConsoleMesConfirmLineSideReceiptRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesConfirmLineSideReceiptRequest
export type BusinessConsoleMesConvertPlanToWorkOrderRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesConvertPlanToWorkOrderRequest
export type BusinessConsoleMesCreateMaterialIssueRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateMaterialIssueRequest
export type BusinessConsoleMesCreateReceiptRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateReceiptRequest
export type BusinessConsoleMesCreateReceiptResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateReceiptResponse
export type BusinessConsoleMesCreateShiftHandoverRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateShiftHandoverRequest
export type BusinessConsoleMesDispatchTaskListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesDispatchTaskListResponse
export type BusinessConsoleMesDispatchTaskRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesDispatchTaskRow
export type BusinessConsoleMesDowntimeEventListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesDowntimeEventListResponse
export type BusinessConsoleMesDowntimeEventRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesDowntimeEventRow
export type BusinessConsoleMesFoundationReadinessResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesFoundationReadinessResponse
export type BusinessConsoleMesMaterialIssueRequestListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialIssueRequestListResponse
export type BusinessConsoleMesMaterialIssueRequestRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialIssueRequestRow
export type BusinessConsoleMesItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderItem
export type BusinessConsoleMesListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderListResponse
export type BusinessConsoleMesMaterialReadinessResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialReadinessResponse
export type BusinessConsoleMesMaterialReadinessRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialReadinessRow
export type BusinessConsoleMesOperationTaskItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskItem
export type BusinessConsoleMesOperationTaskActionRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskActionRequest
export type BusinessConsoleMesOperationTaskActionResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskActionResponse
export type BusinessConsoleMesOperationTaskListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskListResponse
export type BusinessConsoleMesOperationTaskRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskRow
export type BusinessConsoleMesOverviewResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOverviewResponse
export type BusinessConsoleMesProductionPlanListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionPlanListResponse
export type BusinessConsoleMesProductionPlanRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionPlanRow
export type BusinessConsoleMesProductionReportListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionReportListResponse
export type BusinessConsoleMesProductionReportRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionReportRow
export type BusinessConsoleMesRecordDefectRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRecordDefectRequest
export type BusinessConsoleMesRecordDowntimeEventRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRecordDowntimeEventRequest
export type BusinessConsoleMesReadinessArea =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReadinessArea
export type BusinessConsoleMesReadinessIssue =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReadinessIssue
export type BusinessConsoleMesRecoverDowntimeEventRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRecoverDowntimeEventRequest
export type BusinessConsoleMesRelatedQualityItemListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRelatedQualityItemListResponse
export type BusinessConsoleMesRelatedQualityItemRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesRelatedQualityItemRow
export type BusinessConsoleMesReceiptRequestListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReceiptRequestListResponse
export type BusinessConsoleMesReceiptRequestRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReceiptRequestRow
export type BusinessConsoleMesScheduleResult =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesScheduleResult
export type BusinessConsoleMesShiftHandoverListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesShiftHandoverListResponse
export type BusinessConsoleMesShiftHandoverRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesShiftHandoverRow
export type BusinessConsoleMesTraceabilityEdge =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesTraceabilityEdge
export type BusinessConsoleMesTraceabilityNode =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesTraceabilityNode
export type BusinessConsoleMesTraceabilityResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesTraceabilityResponse
export type BusinessConsoleMesWipSummaryResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWipSummaryResponse
export type BusinessConsoleMesWipSummaryRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWipSummaryRow
export type BusinessConsoleMesWorkOrderDetailResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderDetailResponse
export type BusinessConsoleMesWorkOrderItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderItem
export type BusinessConsoleMesWorkOrderListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderListResponse
export type BusinessConsoleMrpPeggingItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMrpPeggingItem
export type BusinessConsoleMrpRunItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMrpRunItem
export type BusinessConsoleNcrCloseRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrCloseRequest
export type BusinessConsoleNcrDispositionRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrDispositionRequest
export type BusinessConsolePlanningSuggestionItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePlanningSuggestionItem
export type BusinessConsoleAcceptPlanningSuggestionRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleAcceptPlanningSuggestionRequest
export type BusinessConsolePostStockMovementRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementRequest
export type BusinessConsolePostStockMovementResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementResponse
export type BusinessConsoleProductionVersionItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleProductionVersionItem
export type BusinessConsoleProductionVersionListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleProductionVersionListResponse
export type BusinessConsoleQualityItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityItem
export type BusinessConsoleQualityListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityListResponse
export type BusinessConsoleRecordProductionReportRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportRequest
export type BusinessConsoleRecordProductionReportResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportResponse
export type BusinessConsoleResolveProductionVersionRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResolveProductionVersionRequest
export type BusinessConsoleResolveProductionVersionResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResolveProductionVersionResponse
export type BusinessConsoleResourceItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceItem
export type BusinessConsoleResourceListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceListResponse
export type BusinessConsoleRoutingItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRoutingItem
export type BusinessConsoleRoutingListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRoutingListResponse
export type BusinessConsoleRunScheduleRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunScheduleRequest
export type BusinessConsoleRunMrpRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunMrpRequest
export type BusinessConsoleRunMrpResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunMrpResponse
export type BusinessConsoleScheduledOperation =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleScheduledOperation
export type EquipmentRuntimeAlarmSummary =
  NervIipContractsEquipmentRuntimeEquipmentRuntimeAlarmSummary
export type EquipmentRuntimeAvailabilityResponse =
  NervIipContractsEquipmentRuntimeEquipmentRuntimeAvailabilityResponse
export type EquipmentRuntimeAvailabilityStatus =
  NervIipContractsEquipmentRuntimeEquipmentRuntimeAvailabilityStatus
export type EquipmentRuntimeAvailabilityWindow =
  NervIipContractsEquipmentRuntimeEquipmentRuntimeAvailabilityWindowContract
export type EquipmentRuntimeCurrentStateResponse =
  NervIipContractsEquipmentRuntimeEquipmentRuntimeCurrentStateResponse
export type EquipmentRuntimeSeverity =
  NervIipContractsEquipmentRuntimeEquipmentRuntimeSeverity
export type EquipmentRuntimeSourceType =
  NervIipContractsEquipmentRuntimeEquipmentRuntimeSourceType

export type BusinessConsoleAcceptedEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleAcceptedResponse
export type BusinessConsoleConfirmStockCountAdjustmentEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleConfirmStockCountAdjustmentResponse
export type BusinessConsoleCreateInspectionRecordEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateInspectionRecordResponse
export type BusinessConsoleCreateRushWorkOrderEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateRushWorkOrderResponse
export type BusinessConsoleCreateStockCountTaskEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateStockCountTaskResponse
export type BusinessConsoleDemandSourceEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleDemandSourceResponse
export type BusinessConsoleDemandSourceListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleDemandSourceListResponse
export type BusinessConsoleEngineeringBomListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleEngineeringBomListResponse
export type BusinessConsoleEquipmentAlarmListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleEquipmentAlarmListResponse
export type BusinessConsoleEquipmentDeviceDetailEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleEquipmentDeviceDetailResponse
export type BusinessConsoleEquipmentOverviewEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleEquipmentOverviewResponse
export type BusinessConsoleErpPurchaseOrderListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleErpPurchaseOrderListResponse
export type EquipmentRuntimeAvailabilityEnvelope =
  NetCorePalExtensionsDtoResponseDataOfEquipmentRuntimeAvailabilityResponse
export type BusinessConsoleInventoryAvailabilityEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleInventoryAvailabilityResponse
export type BusinessConsoleMesCapacityImpactListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesCapacityImpactListResponse
export type BusinessConsoleMesCreateReceiptEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesCreateReceiptResponse
export type BusinessConsoleMesDispatchTaskListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesDispatchTaskListResponse
export type BusinessConsoleMesDowntimeEventListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesDowntimeEventListResponse
export type BusinessConsoleMesFoundationReadinessEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesFoundationReadinessResponse
export type BusinessConsoleMesMaterialIssueRequestListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesMaterialIssueRequestListResponse
export type BusinessConsoleMesMaterialReadinessEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesMaterialReadinessResponse
export type BusinessConsoleMesOperationTaskListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesOperationTaskListResponse
export type BusinessConsoleMesOverviewEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesOverviewResponse
export type BusinessConsoleMesProductionPlanListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesProductionPlanListResponse
export type BusinessConsoleMesProductionReportListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesProductionReportListResponse
export type BusinessConsoleMesRelatedQualityItemListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesRelatedQualityItemListResponse
export type BusinessConsoleMesReceiptRequestListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesReceiptRequestListResponse
export type BusinessConsoleMesScheduleEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesScheduleResult
export type BusinessConsoleMesShiftHandoverListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesShiftHandoverListResponse
export type BusinessConsoleMesTraceabilityEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesTraceabilityResponse
export type BusinessConsoleMesWipSummaryEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWipSummaryResponse
export type BusinessConsoleMesWorkOrderDetailEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderDetailResponse
export type BusinessConsoleMesWorkOrderListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderListResponse
export type BusinessConsoleMrpPeggingListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMrpPeggingListResponse
export type BusinessConsoleMrpRunListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMrpRunListResponse
export type BusinessConsolePlanningSuggestionListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsolePlanningSuggestionListResponse
export type BusinessConsolePostStockMovementEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsolePostStockMovementResponse
export type BusinessConsoleProductionVersionListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleProductionVersionListResponse
export type BusinessConsoleQualityListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleQualityListResponse
export type BusinessConsoleRecordProductionReportEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRecordProductionReportResponse
export type BusinessConsoleResolveProductionVersionEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResolveProductionVersionResponse
export type BusinessConsoleResourceItemEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceItem
export type BusinessConsoleResourceListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceListResponse
export type BusinessConsoleRoutingListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRoutingListResponse
export type BusinessConsoleRunMrpEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRunMrpResponse
