export {
  closeBusinessConsoleQualityNcrMutationOptions,
  confirmBusinessConsoleInventoryCountAdjustmentMutationOptions,
  createBusinessConsoleInventoryCountTaskMutationOptions,
  createBusinessConsoleMesRushWorkOrderMutationOptions,
  createBusinessConsoleQualityInspectionRecordMutationOptions,
  createBusinessConsoleSkuMutationOptions,
  getBusinessConsoleInventoryAvailabilityQueryOptions,
  listBusinessConsoleMasterDataResourcesQueryOptions,
  listBusinessConsoleMesWorkOrdersQueryOptions,
  listBusinessConsoleQualityInspectionPlansQueryOptions,
  listBusinessConsoleQualityNcrsQueryOptions,
  listBusinessConsoleSkusQueryOptions,
  postBusinessConsoleInventoryMovementMutationOptions,
  recordBusinessConsoleMesProductionReportMutationOptions,
  runBusinessConsoleMesScheduleMutationOptions,
  submitBusinessConsoleQualityNcrDispositionMutationOptions,
} from './generated/business-console/@pinia/colada.gen'

export {
  closeBusinessConsoleQualityNcr,
  confirmBusinessConsoleInventoryCountAdjustment,
  createBusinessConsoleInventoryCountTask,
  createBusinessConsoleMesRushWorkOrder,
  createBusinessConsoleQualityInspectionRecord,
  createBusinessConsoleSku,
  getBusinessConsoleInventoryAvailability,
  listBusinessConsoleMasterDataResources,
  listBusinessConsoleMesWorkOrders,
  listBusinessConsoleQualityInspectionPlans,
  listBusinessConsoleQualityNcrs,
  listBusinessConsoleSkus,
  postBusinessConsoleInventoryMovement,
  recordBusinessConsoleMesProductionReport,
  runBusinessConsoleMesSchedule,
  submitBusinessConsoleQualityNcrDisposition,
} from './generated/business-console/sdk.gen'

import type {
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleAcceptedResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleConfirmStockCountAdjustmentResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateInspectionRecordResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateRushWorkOrderResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateStockCountTaskResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleInventoryAvailabilityResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesScheduleResult,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsolePostStockMovementResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleQualityListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRecordProductionReportResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceItem,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleAcceptedResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateSkuRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInspectionCharacteristicResult,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityLineResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesScheduleResult,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrCloseRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrDispositionRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunScheduleRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleScheduledOperation,
} from './generated/business-console/types.gen'

export type BusinessConsoleAcceptedResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleAcceptedResponse
export type BusinessConsoleConfirmStockCountAdjustmentRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentRequest
export type BusinessConsoleConfirmStockCountAdjustmentResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentResponse
export type BusinessConsoleCreateInspectionRecordRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordRequest
export type BusinessConsoleCreateInspectionRecordResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordResponse
export type BusinessConsoleCreateRushWorkOrderRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderRequest
export type BusinessConsoleCreateRushWorkOrderResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderResponse
export type BusinessConsoleCreateSkuRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateSkuRequest
export type BusinessConsoleCreateStockCountTaskRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskRequest
export type BusinessConsoleCreateStockCountTaskResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskResponse
export type BusinessConsoleInspectionCharacteristicResult =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInspectionCharacteristicResult
export type BusinessConsoleInventoryAvailabilityLineResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityLineResponse
export type BusinessConsoleInventoryAvailabilityResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityResponse
export type BusinessConsoleMesItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderItem
export type BusinessConsoleMesListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderListResponse
export type BusinessConsoleMesOperationTaskItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskItem
export type BusinessConsoleMesScheduleResult =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesScheduleResult
export type BusinessConsoleMesWorkOrderItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderItem
export type BusinessConsoleMesWorkOrderListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderListResponse
export type BusinessConsoleNcrCloseRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrCloseRequest
export type BusinessConsoleNcrDispositionRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrDispositionRequest
export type BusinessConsolePostStockMovementRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementRequest
export type BusinessConsolePostStockMovementResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementResponse
export type BusinessConsoleQualityItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityItem
export type BusinessConsoleQualityListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityListResponse
export type BusinessConsoleRecordProductionReportRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportRequest
export type BusinessConsoleRecordProductionReportResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportResponse
export type BusinessConsoleResourceItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceItem
export type BusinessConsoleResourceListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceListResponse
export type BusinessConsoleRunScheduleRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunScheduleRequest
export type BusinessConsoleScheduledOperation =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleScheduledOperation

export type BusinessConsoleAcceptedEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleAcceptedResponse
export type BusinessConsoleConfirmStockCountAdjustmentEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleConfirmStockCountAdjustmentResponse
export type BusinessConsoleCreateInspectionRecordEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateInspectionRecordResponse
export type BusinessConsoleCreateRushWorkOrderEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateRushWorkOrderResponse
export type BusinessConsoleCreateStockCountTaskEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateStockCountTaskResponse
export type BusinessConsoleInventoryAvailabilityEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleInventoryAvailabilityResponse
export type BusinessConsoleMesScheduleEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesScheduleResult
export type BusinessConsoleMesWorkOrderListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderListResponse
export type BusinessConsolePostStockMovementEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsolePostStockMovementResponse
export type BusinessConsoleQualityListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleQualityListResponse
export type BusinessConsoleRecordProductionReportEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRecordProductionReportResponse
export type BusinessConsoleResourceItemEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceItem
export type BusinessConsoleResourceListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceListResponse
