export {
  closeBusinessConsoleQualityNcrMutationOptions,
  confirmBusinessConsoleInventoryCountAdjustmentMutationOptions,
  createBusinessConsoleInventoryCountTaskMutationOptions,
  createBusinessConsoleMesFinishedGoodsReceiptRequestMutationOptions,
  createBusinessConsoleMesRushWorkOrderMutationOptions,
  createBusinessConsoleQualityInspectionRecordMutationOptions,
  createBusinessConsoleSkuMutationOptions,
  getBusinessConsoleInventoryAvailabilityQueryOptions,
  getBusinessConsoleMesFoundationReadinessQueryOptions,
  getBusinessConsoleMesMaterialReadinessQueryOptions,
  getBusinessConsoleMesOverviewQueryOptions,
  getBusinessConsoleMesWipSummaryQueryOptions,
  getBusinessConsoleMesWorkOrderDetailQueryOptions,
  listBusinessConsoleMasterDataResourcesQueryOptions,
  listBusinessConsoleMesCapacityImpactsQueryOptions,
  listBusinessConsoleMesFinishedGoodsReceiptRequestsQueryOptions,
  listBusinessConsoleMesOperationTasksQueryOptions,
  listBusinessConsoleMesProductionReportsQueryOptions,
  listBusinessConsoleMesWorkOrdersQueryOptions,
  listBusinessConsoleQualityInspectionPlansQueryOptions,
  listBusinessConsoleQualityNcrsQueryOptions,
  listBusinessConsoleSkusQueryOptions,
  postBusinessConsoleInventoryMovementMutationOptions,
  recordBusinessConsoleMesProductionReportMutationOptions,
  runBusinessConsoleMesScheduleMutationOptions,
  submitBusinessConsoleQualityNcrDispositionMutationOptions,
} from './generated/business-console/@pinia/colada.gen'

export {
  closeBusinessConsoleQualityNcr,
  confirmBusinessConsoleInventoryCountAdjustment,
  createBusinessConsoleInventoryCountTask,
  createBusinessConsoleMesFinishedGoodsReceiptRequest,
  createBusinessConsoleMesRushWorkOrder,
  createBusinessConsoleQualityInspectionRecord,
  createBusinessConsoleSku,
  getBusinessConsoleInventoryAvailability,
  getBusinessConsoleMesFoundationReadiness,
  getBusinessConsoleMesMaterialReadiness,
  getBusinessConsoleMesOverview,
  getBusinessConsoleMesWipSummary,
  getBusinessConsoleMesWorkOrderDetail,
  listBusinessConsoleMasterDataResources,
  listBusinessConsoleMesCapacityImpacts,
  listBusinessConsoleMesFinishedGoodsReceiptRequests,
  listBusinessConsoleMesOperationTasks,
  listBusinessConsoleMesProductionReports,
  listBusinessConsoleMesWorkOrders,
  listBusinessConsoleQualityInspectionPlans,
  listBusinessConsoleQualityNcrs,
  listBusinessConsoleSkus,
  postBusinessConsoleInventoryMovement,
  recordBusinessConsoleMesProductionReport,
  runBusinessConsoleMesSchedule,
  submitBusinessConsoleQualityNcrDisposition,
} from './generated/business-console/sdk.gen'

import type {
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleAcceptedResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleConfirmStockCountAdjustmentResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateInspectionRecordResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateRushWorkOrderResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateStockCountTaskResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleInventoryAvailabilityResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesCapacityImpactListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesCreateReceiptResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesFoundationReadinessResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesMaterialReadinessResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesOperationTaskListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesOverviewResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesProductionReportListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesReceiptRequestListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesScheduleResult,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWipSummaryResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderDetailResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsolePostStockMovementResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleQualityListResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRecordProductionReportResponse,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceItem,
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleAcceptedResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateSkuRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInspectionCharacteristicResult,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityLineResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCapacityImpactListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCapacityImpactRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateReceiptRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateReceiptResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesFoundationReadinessResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialReadinessResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialReadinessRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOverviewResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionReportListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionReportRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReadinessArea,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReadinessIssue,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReceiptRequestListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReceiptRequestRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesScheduleResult,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWipSummaryResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWipSummaryRow,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderDetailResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrCloseRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrDispositionRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceItem,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceListResponse,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunScheduleRequest,
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleScheduledOperation,
} from './generated/business-console/types.gen'

export type BusinessConsoleAcceptedResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleAcceptedResponse
export type BusinessConsoleConfirmStockCountAdjustmentRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentRequest
export type BusinessConsoleConfirmStockCountAdjustmentResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleConfirmStockCountAdjustmentResponse
export type BusinessConsoleCreateInspectionRecordRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordRequest
export type BusinessConsoleCreateInspectionRecordResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateInspectionRecordResponse
export type BusinessConsoleCreateRushWorkOrderRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderRequest
export type BusinessConsoleCreateRushWorkOrderResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateRushWorkOrderResponse
export type BusinessConsoleCreateSkuRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateSkuRequest
export type BusinessConsoleCreateStockCountTaskRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskRequest
export type BusinessConsoleCreateStockCountTaskResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleCreateStockCountTaskResponse
export type BusinessConsoleInspectionCharacteristicResult =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInspectionCharacteristicResult
export type BusinessConsoleInventoryAvailabilityLineResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityLineResponse
export type BusinessConsoleInventoryAvailabilityResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleInventoryAvailabilityResponse
export type BusinessConsoleMesCapacityImpactListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCapacityImpactListResponse
export type BusinessConsoleMesCapacityImpactRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCapacityImpactRow
export type BusinessConsoleMesCreateReceiptRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateReceiptRequest
export type BusinessConsoleMesCreateReceiptResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesCreateReceiptResponse
export type BusinessConsoleMesFoundationReadinessResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesFoundationReadinessResponse
export type BusinessConsoleMesItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderItem
export type BusinessConsoleMesListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderListResponse
export type BusinessConsoleMesMaterialReadinessResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialReadinessResponse
export type BusinessConsoleMesMaterialReadinessRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesMaterialReadinessRow
export type BusinessConsoleMesOperationTaskItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskItem
export type BusinessConsoleMesOperationTaskListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskListResponse
export type BusinessConsoleMesOperationTaskRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOperationTaskRow
export type BusinessConsoleMesOverviewResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesOverviewResponse
export type BusinessConsoleMesProductionReportListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionReportListResponse
export type BusinessConsoleMesProductionReportRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesProductionReportRow
export type BusinessConsoleMesReadinessArea =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReadinessArea
export type BusinessConsoleMesReadinessIssue =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReadinessIssue
export type BusinessConsoleMesReceiptRequestListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReceiptRequestListResponse
export type BusinessConsoleMesReceiptRequestRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesReceiptRequestRow
export type BusinessConsoleMesScheduleResult =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesScheduleResult
export type BusinessConsoleMesWipSummaryResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWipSummaryResponse
export type BusinessConsoleMesWipSummaryRow =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWipSummaryRow
export type BusinessConsoleMesWorkOrderDetailResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderDetailResponse
export type BusinessConsoleMesWorkOrderItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderItem
export type BusinessConsoleMesWorkOrderListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleMesWorkOrderListResponse
export type BusinessConsoleNcrCloseRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrCloseRequest
export type BusinessConsoleNcrDispositionRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleNcrDispositionRequest
export type BusinessConsolePostStockMovementRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementRequest
export type BusinessConsolePostStockMovementResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsolePostStockMovementResponse
export type BusinessConsoleQualityItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityItem
export type BusinessConsoleQualityListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleQualityListResponse
export type BusinessConsoleRecordProductionReportRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportRequest
export type BusinessConsoleRecordProductionReportResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRecordProductionReportResponse
export type BusinessConsoleResourceItem =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceItem
export type BusinessConsoleResourceListResponse =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleResourceListResponse
export type BusinessConsoleRunScheduleRequest =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleRunScheduleRequest
export type BusinessConsoleScheduledOperation =
  NervIipBusinessGatewayWebApplicationBusinessServicesBusinessConsoleScheduledOperation

export type BusinessConsoleAcceptedEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleAcceptedResponse
export type BusinessConsoleConfirmStockCountAdjustmentEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleConfirmStockCountAdjustmentResponse
export type BusinessConsoleCreateInspectionRecordEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateInspectionRecordResponse
export type BusinessConsoleCreateRushWorkOrderEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateRushWorkOrderResponse
export type BusinessConsoleCreateStockCountTaskEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleCreateStockCountTaskResponse
export type BusinessConsoleInventoryAvailabilityEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleInventoryAvailabilityResponse
export type BusinessConsoleMesCapacityImpactListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesCapacityImpactListResponse
export type BusinessConsoleMesCreateReceiptEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesCreateReceiptResponse
export type BusinessConsoleMesFoundationReadinessEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesFoundationReadinessResponse
export type BusinessConsoleMesMaterialReadinessEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesMaterialReadinessResponse
export type BusinessConsoleMesOperationTaskListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesOperationTaskListResponse
export type BusinessConsoleMesOverviewEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesOverviewResponse
export type BusinessConsoleMesProductionReportListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesProductionReportListResponse
export type BusinessConsoleMesReceiptRequestListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesReceiptRequestListResponse
export type BusinessConsoleMesScheduleEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesScheduleResult
export type BusinessConsoleMesWipSummaryEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWipSummaryResponse
export type BusinessConsoleMesWorkOrderDetailEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderDetailResponse
export type BusinessConsoleMesWorkOrderListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleMesWorkOrderListResponse
export type BusinessConsolePostStockMovementEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsolePostStockMovementResponse
export type BusinessConsoleQualityListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleQualityListResponse
export type BusinessConsoleRecordProductionReportEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleRecordProductionReportResponse
export type BusinessConsoleResourceItemEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceItem
export type BusinessConsoleResourceListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfBusinessConsoleResourceListResponse
