export {
  getConsoleNotificationDeadLetterMetricsQueryOptions,
  getConsoleNotificationDeadLetterQueryOptions,
  ignoreConsoleNotificationDeadLetterMutationOptions,
  listConsoleNotificationDeadLettersQueryOptions,
  getConsoleInstanceDetailQueryOptions,
  getConsoleOperationTaskQueryOptions,
  listConsoleInstancesQueryOptions,
  listConsoleNotificationMessagesQueryOptions,
  listConsoleNotificationTasksQueryOptions,
  markConsoleNotificationMessageReadMutationOptions,
  replayConsoleNotificationDeadLetterMutationOptions,
  replayConsoleNotificationDeadLettersMutationOptions,
  markConsoleNotificationMessagesReadMutationOptions,
  restartConsoleInstanceMutationOptions,
  submitConsoleNotificationIntentMutationOptions,
  upsertConsoleNotificationPreferenceMutationOptions,
  upsertConsoleNotificationSubscriptionMutationOptions,
  upsertConsoleNotificationRecipientChannelBindingMutationOptions,
} from './generated/@pinia/colada.gen'

import type {
  NetCorePalExtensionsDtoResponseDataOfInstanceDetailResponse,
  NetCorePalExtensionsDtoResponseDataOfInstanceListResponse,
  NetCorePalExtensionsDtoResponseDataOfIReadOnlyCollectionOfMarkNotificationMessageReadResponse,
  NetCorePalExtensionsDtoResponseDataOfMarkNotificationMessageReadResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterBatchReplayResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterDetailResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterListResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterMetricsResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterReplayResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationIntentResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationMessageListResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationTaskListResponse,
  NetCorePalExtensionsDtoResponseDataOfOperationTaskResponse,
  NervIipContractsAppHubQueriesInstanceDetailResponse,
  NervIipContractsAppHubQueriesInstanceListItem,
  NervIipContractsAppHubQueriesInstanceListResponse,
  NervIipContractsNotificationIgnoreNotificationDeadLetterRequest,
  NervIipContractsNotificationMarkNotificationMessageReadResponse,
  NervIipContractsNotificationMarkNotificationMessagesReadRequest,
  NervIipContractsNotificationNotificationDeadLetterDetailResponse,
  NervIipContractsNotificationNotificationDeadLetterMetricsResponse,
  NervIipContractsNotificationNotificationDeadLetterReplayResponse,
  NervIipContractsNotificationNotificationDeadLetterResponse,
  NervIipContractsNotificationNotificationIntentResponse,
  NervIipContractsNotificationNotificationMessageResponse,
  NervIipContractsNotificationNotificationResourceRef,
  NervIipContractsNotificationNotificationTaskResponse,
  NervIipContractsNotificationReplayNotificationDeadLetterBatchRequest,
  NervIipContractsNotificationSubmitNotificationIntentRequest,
  NervIipContractsOpsOperationTaskResponse,
  NervIipPlatformGatewayWebEndpointsOperationsRestartInstanceRequest,
} from './generated/types.gen'

export type InstanceDetailResponse = NervIipContractsAppHubQueriesInstanceDetailResponse
export type InstanceListItem = NervIipContractsAppHubQueriesInstanceListItem
export type InstanceListResponse = NervIipContractsAppHubQueriesInstanceListResponse
export type OperationTaskResponse = NervIipContractsOpsOperationTaskResponse
export type RestartInstanceRequest =
  NervIipPlatformGatewayWebEndpointsOperationsRestartInstanceRequest
export type MarkNotificationMessageReadResponse =
  NervIipContractsNotificationMarkNotificationMessageReadResponse
export type MarkNotificationMessagesReadRequest =
  NervIipContractsNotificationMarkNotificationMessagesReadRequest
export type IgnoreNotificationDeadLetterRequest =
  NervIipContractsNotificationIgnoreNotificationDeadLetterRequest
export type ReplayNotificationDeadLetterBatchRequest =
  NervIipContractsNotificationReplayNotificationDeadLetterBatchRequest
export type NotificationDeadLetterResponse =
  NervIipContractsNotificationNotificationDeadLetterResponse
export type NotificationDeadLetterDetailResponse =
  NervIipContractsNotificationNotificationDeadLetterDetailResponse
export type NotificationDeadLetterMetricsResponse =
  NervIipContractsNotificationNotificationDeadLetterMetricsResponse
export type NotificationDeadLetterReplayResponse =
  NervIipContractsNotificationNotificationDeadLetterReplayResponse
export type NotificationIntentResponse = NervIipContractsNotificationNotificationIntentResponse
export type NotificationMessageResponse = NervIipContractsNotificationNotificationMessageResponse
export type NotificationResourceRef = NervIipContractsNotificationNotificationResourceRef
export type NotificationTaskResponse = NervIipContractsNotificationNotificationTaskResponse
export type SubmitNotificationIntentRequest =
  NervIipContractsNotificationSubmitNotificationIntentRequest
export type InstanceDetailEnvelope = NetCorePalExtensionsDtoResponseDataOfInstanceDetailResponse
export type InstanceListEnvelope = NetCorePalExtensionsDtoResponseDataOfInstanceListResponse
export type OperationTaskEnvelope = NetCorePalExtensionsDtoResponseDataOfOperationTaskResponse
export type MarkNotificationMessageReadEnvelope =
  NetCorePalExtensionsDtoResponseDataOfMarkNotificationMessageReadResponse
export type MarkNotificationMessagesReadEnvelope =
  NetCorePalExtensionsDtoResponseDataOfIReadOnlyCollectionOfMarkNotificationMessageReadResponse
export type NotificationIntentEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationIntentResponse
export type NotificationDeadLetterListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterListResponse
export type NotificationDeadLetterDetailEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterDetailResponse
export type NotificationDeadLetterMetricsEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterMetricsResponse
export type NotificationDeadLetterReplayEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterReplayResponse
export type NotificationDeadLetterBatchReplayEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationDeadLetterBatchReplayResponse
export type NotificationMessageListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationMessageListResponse
export type NotificationTaskListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationTaskListResponse
