export {
  getConsoleInstanceDetailQueryOptions,
  getConsoleOperationTaskQueryOptions,
  listConsoleInstancesQueryOptions,
  listConsoleNotificationMessagesQueryOptions,
  listConsoleNotificationTasksQueryOptions,
  markConsoleNotificationMessageReadMutationOptions,
  markConsoleNotificationMessagesReadMutationOptions,
  restartConsoleInstanceMutationOptions,
  submitConsoleNotificationIntentMutationOptions,
} from './generated/@pinia/colada.gen'

import type {
  NetCorePalExtensionsDtoResponseDataOfInstanceDetailResponse,
  NetCorePalExtensionsDtoResponseDataOfInstanceListResponse,
  NetCorePalExtensionsDtoResponseDataOfIReadOnlyCollectionOfMarkNotificationMessageReadResponse,
  NetCorePalExtensionsDtoResponseDataOfMarkNotificationMessageReadResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationIntentResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationMessageListResponse,
  NetCorePalExtensionsDtoResponseDataOfNotificationTaskListResponse,
  NetCorePalExtensionsDtoResponseDataOfOperationTaskResponse,
  NervIipContractsAppHubQueriesInstanceDetailResponse,
  NervIipContractsAppHubQueriesInstanceListItem,
  NervIipContractsAppHubQueriesInstanceListResponse,
  NervIipContractsNotificationMarkNotificationMessageReadResponse,
  NervIipContractsNotificationMarkNotificationMessagesReadRequest,
  NervIipContractsNotificationNotificationIntentResponse,
  NervIipContractsNotificationNotificationMessageResponse,
  NervIipContractsNotificationNotificationResourceRef,
  NervIipContractsNotificationNotificationTaskResponse,
  NervIipContractsNotificationSubmitNotificationIntentRequest,
  NervIipContractsOpsOperationTaskResponse,
  NervIipPlatformGatewayWebEndpointsOperationsRestartInstanceRequest,
} from './generated/types.gen'

export type InstanceDetailResponse = NervIipContractsAppHubQueriesInstanceDetailResponse
export type InstanceListItem = NervIipContractsAppHubQueriesInstanceListItem
export type InstanceListResponse = NervIipContractsAppHubQueriesInstanceListResponse
export type OperationTaskResponse = NervIipContractsOpsOperationTaskResponse
export type RestartInstanceRequest =
  NervIipPlatformGatewayWebEndpointsOperationsRestartInstanceRequest
export type MarkNotificationMessageReadResponse =
  NervIipContractsNotificationMarkNotificationMessageReadResponse
export type MarkNotificationMessagesReadRequest =
  NervIipContractsNotificationMarkNotificationMessagesReadRequest
export type NotificationIntentResponse =
  NervIipContractsNotificationNotificationIntentResponse
export type NotificationMessageResponse =
  NervIipContractsNotificationNotificationMessageResponse
export type NotificationResourceRef = NervIipContractsNotificationNotificationResourceRef
export type NotificationTaskResponse =
  NervIipContractsNotificationNotificationTaskResponse
export type SubmitNotificationIntentRequest =
  NervIipContractsNotificationSubmitNotificationIntentRequest
export type InstanceDetailEnvelope = NetCorePalExtensionsDtoResponseDataOfInstanceDetailResponse
export type InstanceListEnvelope = NetCorePalExtensionsDtoResponseDataOfInstanceListResponse
export type OperationTaskEnvelope = NetCorePalExtensionsDtoResponseDataOfOperationTaskResponse
export type MarkNotificationMessageReadEnvelope =
  NetCorePalExtensionsDtoResponseDataOfMarkNotificationMessageReadResponse
export type MarkNotificationMessagesReadEnvelope =
  NetCorePalExtensionsDtoResponseDataOfIReadOnlyCollectionOfMarkNotificationMessageReadResponse
export type NotificationIntentEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationIntentResponse
export type NotificationMessageListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationMessageListResponse
export type NotificationTaskListEnvelope =
  NetCorePalExtensionsDtoResponseDataOfNotificationTaskListResponse
