import type {
  NervIipPlatformGatewayWebApplicationIamAdminConsoleCreateIamRoleRequest,
  NervIipPlatformGatewayWebApplicationIamAdminConsoleCreateIamUserRequest,
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamPermissionCatalogResponse,
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamPermissionResponse,
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamRoleResponse,
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamSessionResponse,
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamUserResponse,
  NervIipPlatformGatewayWebApplicationIamAdminConsoleResetIamUserPasswordRequest,
  NervIipPlatformGatewayWebApplicationIamAdminConsoleUpdateIamRolePermissionsRequest,
  NervIipPlatformGatewayWebApplicationIamAdminConsoleUpdateIamUserRequest,
  NervIipPlatformGatewayWebApplicationIamAdminPagedListResponseOfConsoleIamRoleResponse,
  NervIipPlatformGatewayWebApplicationIamAdminPagedListResponseOfConsoleIamSessionResponse,
  NervIipPlatformGatewayWebApplicationIamAdminPagedListResponseOfConsoleIamUserResponse,
  NetCorePalExtensionsDtoResponseDataOfConsoleIamPermissionCatalogResponse,
  NetCorePalExtensionsDtoResponseDataOfConsoleIamRoleResponse,
  NetCorePalExtensionsDtoResponseDataOfConsoleIamUserResponse,
  NetCorePalExtensionsDtoResponseDataOfPagedListResponseOfConsoleIamRoleResponse,
  NetCorePalExtensionsDtoResponseDataOfPagedListResponseOfConsoleIamSessionResponse,
  NetCorePalExtensionsDtoResponseDataOfPagedListResponseOfConsoleIamUserResponse,
} from './generated/types.gen'

export {
  createConsoleIamRoleMutationOptions,
  createConsoleIamUserMutationOptions,
  disableConsoleIamUserMutationOptions,
  enableConsoleIamUserMutationOptions,
  listConsoleIamPermissionsQueryOptions,
  listConsoleIamRolesQueryOptions,
  listConsoleIamSessionsQueryOptions,
  listConsoleIamUsersQueryOptions,
  resetConsoleIamUserPasswordMutationOptions,
  revokeConsoleIamSessionMutationOptions,
  updateConsoleIamRolePermissionsMutationOptions,
  updateConsoleIamUserMutationOptions,
} from './generated/@pinia/colada.gen'

export {
  createConsoleIamRole,
  createConsoleIamUser,
  disableConsoleIamUser,
  enableConsoleIamUser,
  listConsoleIamPermissions,
  listConsoleIamRoles,
  listConsoleIamSessions,
  listConsoleIamUsers,
  resetConsoleIamUserPassword,
  revokeConsoleIamSession,
  updateConsoleIamRolePermissions,
  updateConsoleIamUser,
} from './generated/sdk.gen'

export type ConsoleIamUserResponse =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamUserResponse
export type ConsoleCreateIamUserRequest =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleCreateIamUserRequest
export type ConsoleUpdateIamUserRequest =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleUpdateIamUserRequest
export type ConsoleResetIamUserPasswordRequest =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleResetIamUserPasswordRequest
export type ConsoleIamRoleResponse =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamRoleResponse
export type ConsoleCreateIamRoleRequest =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleCreateIamRoleRequest
export type ConsoleUpdateIamRolePermissionsRequest =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleUpdateIamRolePermissionsRequest
export type ConsoleIamPermissionCatalogResponse =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamPermissionCatalogResponse
export type ConsoleIamPermissionResponse =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamPermissionResponse
export type ConsoleIamSessionResponse =
  NervIipPlatformGatewayWebApplicationIamAdminConsoleIamSessionResponse
export type ConsoleIamUsersPage =
  NervIipPlatformGatewayWebApplicationIamAdminPagedListResponseOfConsoleIamUserResponse
export type ConsoleIamRolesPage =
  NervIipPlatformGatewayWebApplicationIamAdminPagedListResponseOfConsoleIamRoleResponse
export type ConsoleIamSessionsPage =
  NervIipPlatformGatewayWebApplicationIamAdminPagedListResponseOfConsoleIamSessionResponse
export type ConsoleIamUserEnvelope =
  NetCorePalExtensionsDtoResponseDataOfConsoleIamUserResponse
export type ConsoleIamRoleEnvelope =
  NetCorePalExtensionsDtoResponseDataOfConsoleIamRoleResponse
export type ConsoleIamUsersEnvelope =
  NetCorePalExtensionsDtoResponseDataOfPagedListResponseOfConsoleIamUserResponse
export type ConsoleIamRolesEnvelope =
  NetCorePalExtensionsDtoResponseDataOfPagedListResponseOfConsoleIamRoleResponse
export type ConsoleIamSessionsEnvelope =
  NetCorePalExtensionsDtoResponseDataOfPagedListResponseOfConsoleIamSessionResponse
export type ConsoleIamPermissionsEnvelope =
  NetCorePalExtensionsDtoResponseDataOfConsoleIamPermissionCatalogResponse
