export const EQUIPMENT_DEVICE_NAME_SIZE_PX = 14
export const EQUIPMENT_ROW_HEIGHT_PX = 122
export const EQUIPMENT_ROW_GAP_PX = 12
export const EQUIPMENT_ROW_ITEM_HEIGHT_PX = EQUIPMENT_ROW_HEIGHT_PX + EQUIPMENT_ROW_GAP_PX
export const EQUIPMENT_ROW_OVERSCAN = 2
